// ═══════════════════════════════════════════════════════════════════════════════════════════════
// build-image.mjs — BUILD THE WORLD ONCE, HERE, instead of in every player's tab
// ═══════════════════════════════════════════════════════════════════════════════════════════════
//
// ── THE DEFECT (docs/RESUME.md:125, docs/DEV_LOG.md:177) ────────────────────────────────────────
//   "Cold boot 78.8 s measured with 243 goods. The world builds in the player's tab."
// The chain is a pure function of the repository: replaying it in a browser produces the same
// world every time, at the cost of 45 migrations, 52,002 derived price rows and a re-measured sea.
// This script runs that once, at build time, and ships the resulting PostgreSQL data directory.
//
// ── THE THING THAT MATTERS MORE THAN THE SPEED ──────────────────────────────────────────────────
// A shipped image is a SECOND COPY OF THE WORLD, and this project lost a working day to exactly
// that class of defect (docs/DEV_LOG.md D23): migration 0003 was edited after production had
// applied it, "production kept the ORIGINAL 70 goods / 214 harbours while every fresh rebuild got
// 243", and — the sentence to keep — "Nothing red happened anywhere. Everything stayed green
// while the worlds diverged."
//
// So the image is built to be IMPOSSIBLE TO SHIP STALE, by four separate mechanisms:
//
//   1. IT IS GENERATED, NEVER COMMITTED. vite.config.ts calls `ensureWorldImage()` during
//      `npm run build`, from the chain in supabase/migrations at that moment. Nothing under
//      version control has to be regenerated by a human who might forget.
//   2. ITS NAME IS ITS FINGERPRINT. The cache file and the emitted asset are both
//      `world-<fingerprintChain(files)>.tar.gz`, so an image built from another chain is a file
//      the client never asks for. A moved chain is a 404, and a 404 applies the chain.
//   3. IT CARRIES THE FINGERPRINT INSIDE IT. `recordChain()` stamps app_local.chain in the image
//      itself, with the same DDL a browser-applied world gets; the browser reads it back with the
//      same query and refuses a mismatch OUT LOUD (`imageRefusal()` in src/lib/db/appLocal.ts).
//   4. IT IS CERTIFIED BY THE SAME AUTHORITY AS EVERY OTHER APPLY. `assertWorldMatchesData()` —
//      scripts/db/world-guard.mjs, the guard D23 installed, positive control and all — is run
//      against the database RESTORED FROM THE TARBALL, not merely against the one that was
//      dumped. No new comparator was written for images; there is one comparator.
//
// ── WHY IT APPLIES THE CHAIN THE *BROWSER'S* WAY, NOT apply-chain.mjs's ──────────────────────────
// `scripts/db/apply-chain.mjs` applies `supabase-preamble.sql` first — a TEST FIXTURE whose own
// header says "NOT A MIGRATION. NEVER DEPLOY THIS." Shipping a database built through it would
// deliver that fixture's roles and default ACLs into every player's browser. So this script uses
// `src/lib/db/applyChain.ts` — the very module the browser runs, imported directly (Node 24 strips
// the types) — over `chainSource.node.mjs`'s files. The image is therefore byte-for-byte what the
// browser would have built for itself, which is the only thing that makes it a legitimate
// substitute for building it there.
//
// ── USAGE ───────────────────────────────────────────────────────────────────────────────────────
//   npm run db:image              build (if the cache has no image for this chain) and certify
//   npm run db:image -- --force   rebuild even if the cache has one
//   import { ensureWorldImage, certifyWorldImage } from './build-image.mjs'
// ═══════════════════════════════════════════════════════════════════════════════════════════════

import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

import { loadChain } from '../../src/lib/db/chainSource.node.mjs'
import { fingerprintChain } from '../../src/lib/db/chain.ts'
import { imageRefusal, readStoredChain, recordChain } from '../../src/lib/db/appLocal.ts'
import { WORLD_IMAGE_DIR, worldImageFileName } from '../../src/lib/db/worldImage.ts'
import { assertWorldMatchesData } from './world-guard.mjs'

// Re-exported so vite.config.ts and the spec take the naming rule from the SAME module the browser
// does, without either of them having to import a .ts file of their own.
export { WORLD_IMAGE_DIR, worldImageFileName }

const HERE = path.dirname(fileURLToPath(import.meta.url))
export const REPO_ROOT = path.resolve(HERE, '..', '..')

/**
 * Where a built image waits between builds. Under node_modules/.cache, because it is a build
 * artefact of the same standing as a compiled bundle: never committed, and thrown away with
 * `npm ci`. The FILE NAME carries the fingerprint, so a cache entry cannot go stale — a moved
 * chain simply misses and builds a new one.
 */
export const IMAGE_CACHE_DIR = path.join(REPO_ROOT, 'node_modules', '.cache', 'byeharu-world-image')

/** The chain as the browser will see it, and its fingerprint. One loader, one fingerprint. */
export async function chainAndFingerprint() {
  const files = await loadChain()
  return { files, fingerprint: fingerprintChain(files) }
}

/**
 * Apply the chain to a fresh PostgreSQL, certify the world, stamp the chain into it, and hand
 * back a compressed data directory.
 *
 * `--wal-segsize=1` is not a tuning knob, it is half of the difference between a 35 MB download
 * and a usable one: PostgreSQL's default 16 MB WAL segments left 144 MB of write-ahead log in a
 * 232 MB tarball (measured, 2026-08-25). One-megabyte segments, `vacuum full`, and the trim below
 * took the shipped image from 35.61 MB gzipped to 4.75 MB. The segment size is baked into
 * pg_control at initdb time and travels with the image; nothing else in the shipped configuration
 * is altered, and a 1 MB segment is if anything the friendlier size for a browser.
 */
export async function buildWorldImage({ log = console.log } = {}) {
  const { PGlite } = await import('@electric-sql/pglite')
  const { applyChain } = await import('../../src/lib/db/applyChain.ts')
  const { files, fingerprint } = await chainAndFingerprint()

  const t0 = Date.now()
  const pg = await PGlite.create({ initDbStartParams: ['--wal-segsize=1'] })

  const result = await applyChain(pg, files, (step) => {
    if (step.index % 10 === 0 || step.index === step.total - 1) {
      log(`  applying ${step.index + 1}/${step.total}: ${step.name}`)
    }
  })
  const applyMs = Date.now() - t0

  // THE SAME NON-VACUITY FLOOR apply-chain.mjs enforces. A chain whose migrations stopped printing
  // their receipts is a chain whose self-asserts may have quietly stopped asserting — and this one
  // is about to be frozen into an artefact and handed to every player.
  if (result.receipts < result.applied.length) {
    throw new Error(
      `IMAGE REFUSED: ${result.applied.length} migration(s) applied but only ${result.receipts} ` +
        'printed a "self-assert ok:" receipt. Every migration must prove itself out loud before ' +
        'its result is frozen into a shipped artefact.',
    )
  }

  // The world this image will carry must equal data/*.json — the standing guard, positive control
  // and all. Run here as well as after the round trip, so a failure names the CHAIN rather than
  // the tarball.
  await assertWorldMatchesData(pg, { log })

  // The stamp the browser reads back. Same DDL, same row, same reader as a browser-applied world.
  // `auth_uid` stays null: an image is a WORLD, not a house. §K.1's opening is founded in the
  // player's own browser, by the chain's own `new_house()`, exactly as it always was.
  await recordChain(pg, { fingerprint, names: files.map((f) => f.name), authUid: null })

  // Compact, then trim the log. `vacuum full` matters: the chain UPDATEs port_goods repeatedly
  // (drift, re-derivation), and the dead tuples left behind were 49 MB of the 65 MB database.
  await pg.query('vacuum full')
  await pg.query('vacuum analyze')
  await pg.query('checkpoint')
  await pg.query('checkpoint')

  // The write-ahead log a player downloads is the log of a build they did not watch. A restored
  // database replays from the last checkpoint, so exactly one range of segments is live —
  // [checkpoint, current]. Everything else in pg_wal is PostgreSQL's own scratch: segments RENAMED
  // TO FUTURE NAMES so they can be written again on a machine that will never write to this
  // database. That was 64 of the 67 retained megabytes (measured, 2026-08-25).
  //
  // The window is read AFTER the dump, never before: the dump is a snapshot of an earlier moment,
  // so a `current` read afterwards can only be too generous, which is the safe direction.
  const dumped = new Uint8Array(await (await pg.dumpDataDir('none')).arrayBuffer())
  const wal = (
    await pg.query(
      `select pg_walfile_name(checkpoint_lsn) as needed,
              pg_walfile_name(pg_current_wal_lsn()) as current
         from pg_control_checkpoint()`,
    )
  ).rows[0]
  await pg.close()
  const tar = dropSurplusWal(dumped, wal.needed, wal.current)

  // gzip level 9 rather than PGlite's own CompressionStream default: this runs once per build and
  // every player pays for the bytes.
  const bytes = new Uint8Array(gzipSync(tar, { level: 9 }))
  return {
    bytes,
    tarBytes: tar.length,
    dumpedBytes: dumped.length,
    fingerprint,
    files,
    applyMs,
    ms: Date.now() - t0,
    migrations: result.applied.length,
    receipts: result.receipts,
  }
}

/**
 * Rebuild the tarball with only the write-ahead-log segments a restored database can read:
 * those from the last checkpoint's own file through the current one, inclusive.
 *
 * IT DOES NOT GUESS. `first`/`last` are PostgreSQL's own answers, via `pg_walfile_name()` over
 * `pg_control_checkpoint()` and `pg_current_wal_lsn()`. Segments outside that window are either
 * spent or — the bulk of them — RECYCLED: renamed to future names, still full of the log of the
 * migrations that already ran, waiting to be overwritten by writes this shipped copy will never
 * see.
 *
 * AND IT IS NOT TRUSTED. `certifyWorldImage()` restores THIS tarball and plays the opening of the
 * game in it, so a trim that removed something the engine needed cannot reach a filename, let
 * alone a player. Entries are copied block-for-block, so every tar header and checksum in the
 * output was written by PGlite's own dumper.
 */
export function dropSurplusWal(tar, first, last) {
  const dec = new TextDecoder()
  const kept = []
  let off = 0
  let dropped = 0
  while (off + 512 <= tar.length) {
    const nameBytes = tar.subarray(off, off + 100)
    const nul = nameBytes.indexOf(0)
    const name = dec.decode(nul === -1 ? nameBytes : nameBytes.subarray(0, nul))
    if (!name) break // the two zero blocks that end a tar
    const size =
      parseInt(dec.decode(tar.subarray(off + 124, off + 136)).replace(/\0.*$/, '').trim(), 8) || 0
    const total = 512 + Math.ceil(size / 512) * 512
    const segment = /^\/?pg_wal\/([0-9A-F]{24})$/.exec(name)
    if (segment && (segment[1] < first || segment[1] > last)) {
      dropped += size
    } else {
      kept.push(tar.subarray(off, off + total))
    }
    off += total
  }
  if (dropped === 0) return tar

  const end = new Uint8Array(1024) // a tar ends with two zero blocks
  const out = new Uint8Array(kept.reduce((n, b) => n + b.length, 0) + end.length)
  let at = 0
  for (const block of kept) {
    out.set(block, at)
    at += block.length
  }
  out.set(end, at)
  return out
}

/**
 * THE ROUND-TRIP PROOF. Restore the tarball into a fresh PostgreSQL and ask the two questions that
 * matter: is this the chain the caller thinks it is, and is the world in it the world data/*.json
 * describes?
 *
 * Both answers come from authorities that already existed — `imageRefusal()` (the same function
 * the browser boots through) and `assertWorldMatchesData()` (the same guard `npm run db:apply` and
 * CI run). Nothing here is a second comparator, which is the whole point: a bespoke image checker
 * would be one more thing that can agree with itself while disagreeing with the game.
 *
 * THROWS on any disagreement. Used by the builder before an image is allowed to reach a filename,
 * and by tests/db.image.spec.ts against whatever the build actually emitted.
 */
export async function certifyWorldImage(bytes, { fingerprint, log = () => {} } = {}) {
  const { PGlite } = await import('@electric-sql/pglite')
  const file = new File([bytes], worldImageFileName(fingerprint ?? 'unknown'), {
    type: 'application/gzip',
  })

  let pg
  try {
    pg = await PGlite.create({ loadDataDir: file })
  } catch (err) {
    throw new Error(
      `IMAGE REFUSED: it could not be restored into PostgreSQL at all (${
        err instanceof Error ? err.message : String(err)
      }).`,
    )
  }

  try {
    const stored = await readStoredChain(pg)
    if (fingerprint !== undefined) {
      const refusal = imageRefusal(stored, fingerprint)
      if (refusal) throw new Error(`IMAGE REFUSED: ${refusal}`)
    }
    await assertWorldMatchesData(pg, { log })
    const ports = (await pg.query('select count(*)::int as n from public.ports')).rows[0].n
    const harbours = (
      await pg.query("select count(*)::int as n from public.ports where kind = 'HARBOUR'")
    ).rows[0].n
    const goods = (await pg.query('select count(*)::int as n from public.goods')).rows[0].n
    const market = (await pg.query('select count(*)::int as n from public.port_goods')).rows[0].n

    // ── IT MUST BE PLAYABLE, NOT MERELY READABLE ────────────────────────────────────────────────
    // A restored data directory can satisfy every read above and still be a database that cannot
    // be WRITTEN to — which is the failure mode a mis-trimmed write-ahead log would produce, and
    // the one a player would meet three seconds after the world opened. So the certification plays
    // §K.1's opening in the restored copy, through the chain's own founding function, and requires
    // the purse and the hull it promises. The copy is thrown away with the engine.
    const uid = '00000000-0000-4000-8000-0000000000ce'
    await pg.query('select public.new_house($1, $2, $3)', [uid, 'Certification', 'PRT'])
    const house = (
      await pg.query(
        `select p.ducats::int as ducats, count(s.id)::int as ships
           from public.players p
           left join public.fleets f on f.player_id = p.id
           left join public.ships s on s.fleet_id = f.id
          where p.auth_uid = $1
          group by p.ducats`,
        [uid],
      )
    ).rows[0]
    if (!house || house.ducats !== 8000 || house.ships !== 1) {
      throw new Error(
        'IMAGE REFUSED: the restored world could not open a house — expected 8,000 ducats and one ' +
          `hull, got ${JSON.stringify(house ?? null)}. A world that reads back correctly but ` +
          'cannot be written to is not a world anybody can play.',
      )
    }
    await pg.query('checkpoint')

    return {
      fingerprint: stored?.fingerprint ?? null,
      files: stored?.files ?? 0,
      ports,
      harbours,
      goods,
      market,
    }
  } finally {
    await pg.close()
  }
}

/**
 * The image for the chain in this repository, built if the cache has none.
 *
 * A file only ever reaches its final name AFTER `certifyWorldImage()` has passed over it, so the
 * existence of `world-<fingerprint>.tar.gz` in the cache means "these bytes were certified against
 * this chain". That is what lets a rebuild skip the certification without weakening it — and why
 * the write is a rename over a temporary file rather than a write in place.
 */
export async function ensureWorldImage({ log = console.log, cacheDir = IMAGE_CACHE_DIR, force = false } = {}) {
  const { files, fingerprint } = await chainAndFingerprint()
  const file = path.join(cacheDir, worldImageFileName(fingerprint))

  if (!force && existsSync(file)) {
    const bytes = await readFile(file)
    log(`world image: reusing ${path.relative(REPO_ROOT, file)} (${mb(bytes.length)})`)
    return { file, fingerprint, bytes, built: false, migrations: files.length }
  }

  log(`world image: building from ${files.length} migration(s), chain ${fingerprint}`)
  const built = await buildWorldImage({ log })
  log(
    `world image: chain applied in ${(built.applyMs / 1000).toFixed(1)} s; ` +
      `${mb(built.dumpedBytes)} dumped, ${mb(built.tarBytes)} after the log trim, ` +
      `${mb(built.bytes.length)} gzipped`,
  )

  const receipt = await certifyWorldImage(built.bytes, { fingerprint, log })
  log(
    `world image: certified — ${receipt.ports} port row(s), ${receipt.goods} good(s), ` +
      `${receipt.market} market row(s), chain ${receipt.fingerprint}`,
  )

  await mkdir(cacheDir, { recursive: true })
  const tmp = `${file}.${process.pid}.tmp`
  await writeFile(tmp, built.bytes)
  await rename(tmp, file)
  log(`world image: ${path.relative(REPO_ROOT, file)} (${mb(built.bytes.length)})`)

  return { file, fingerprint, bytes: built.bytes, built: true, migrations: built.migrations }
}

/** Throw away every cached image. Only the CLI's --clean asks for this. */
export async function clearWorldImageCache(cacheDir = IMAGE_CACHE_DIR) {
  await rm(cacheDir, { recursive: true, force: true })
}

function mb(bytes) {
  return `${(bytes / 1048576).toFixed(2)} MB`
}

const isMain =
  process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))
if (isMain) {
  try {
    if (process.argv.includes('--clean')) await clearWorldImageCache()
    const out = await ensureWorldImage({ force: process.argv.includes('--force') })
    console.log('')
    console.log('═══════════════════════════════════════════════════════════════════════')
    console.log(`WORLD IMAGE ${out.built ? 'BUILT' : 'CACHED'}: ${mb(out.bytes.length)}`)
    console.log(`  chain ${out.fingerprint} over ${out.migrations} migration(s)`)
    console.log(`  ${out.file}`)
    console.log('═══════════════════════════════════════════════════════════════════════')
    process.exit(0)
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err))
    process.exit(1)
  }
}
