import { readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// base '/byeharu-voyage/' = served as a GitHub Pages project site at
// https://<owner>.github.io/byeharu-voyage/. BrowserRouter reads this via BASE_URL
// (src/app/App.tsx passes import.meta.env.BASE_URL as its basename), and public/404.html
// encodes deep links back through index.html's decoder.

// ═══════════════════════════════════════════════════════════════════════════════════════════════
// THE PRE-BUILT WORLD — generated by the build, never committed
// ═══════════════════════════════════════════════════════════════════════════════════════════════
//
// Replaying 45 migrations in the player's tab cost 78.8 s on a cold boot (docs/DEV_LOG.md:177).
// The chain is a pure function of the repository, so this plugin runs it ONCE, here, and emits the
// resulting PostgreSQL data directory as `dist/db/world-<fingerprint>.tar.gz`.
//
// WHY IT IS A BUILD STEP AND NOT A CHECKED-IN FILE. A committed image is a second copy of the
// world that a human must remember to regenerate, and this project has already lost a working day
// to precisely that (docs/DEV_LOG.md D23: an edited migration left production on 70 goods while
// every fresh rebuild got 243, and "nothing red happened anywhere"). Generated at build time from
// the chain in `supabase/migrations` at that moment, keyed by that chain's fingerprint, there is
// nothing to forget: change a migration and the next build makes a new image under a new name,
// which is the only name the client will ever ask for.
//
// The emitted name is deterministic — no content hash — because the client derives the URL from
// `fingerprintChain(files)` at run time (src/lib/db/worldImage.ts). If the two ever disagree the
// fetch is a 404 and the boot applies the chain, which is the behaviour this optimisation replaced.
//
// In `vite dev` nothing is generated (one chain apply is minutes of CPU and dev reloads
// constantly); the middleware below serves an image only if a previous `npm run build` or
// `npm run db:image` already put one in the cache for exactly this chain.
//
// EVERY IMPORT OF THE BUILDER IS DYNAMIC AND ITS PATH IS COMPUTED. Vite bundles this config file
// with esbuild into a temporary module, and a literal relative import would be INLINED into that
// temporary file — where `import.meta.url` no longer points at scripts/db/, and the builder's
// REPO_ROOT (and with it supabase/migrations and data/) would resolve somewhere else entirely. A
// computed specifier is left alone and loaded by Node from where it actually lives.
// ═══════════════════════════════════════════════════════════════════════════════════════════════
function worldImage(): Plugin {
  let root = process.cwd()
  let building = false

  const builder = async () => {
    const file = path.join(root, 'scripts', 'db', 'build-image.mjs')
    if (!existsSync(file)) throw new Error(`world image: ${file} is missing`)
    return (await import(pathToFileURL(file).href)) as typeof import('./scripts/db/build-image.mjs')
  }

  return {
    name: 'byeharu:world-image',
    configResolved(config) {
      root = config.root
      // Only a real build generates one. `vite dev` and `vite preview` read what a build left.
      building = config.command === 'build'
    },
    async buildStart() {
      if (!building) return
      const { ensureWorldImage, WORLD_IMAGE_DIR, worldImageFileName } = await builder()
      const image = await ensureWorldImage({ log: (...args) => this.info(args.join(' ')) })
      this.emitFile({
        type: 'asset',
        fileName: `${WORLD_IMAGE_DIR}/${worldImageFileName(image.fingerprint)}`,
        source: image.bytes,
      })
    },
    async configureServer(server) {
      const { IMAGE_CACHE_DIR, WORLD_IMAGE_DIR, chainAndFingerprint, worldImageFileName } =
        await builder()
      server.middlewares.use(async (req, res, next) => {
        const url = (req.url ?? '').split('?')[0]
        if (!url.includes(`/${WORLD_IMAGE_DIR}/world-`)) return next()
        const { fingerprint } = await chainAndFingerprint()
        const name = worldImageFileName(fingerprint)
        const file = path.join(IMAGE_CACHE_DIR, name)
        // A cache entry is named for the chain that built it, so this can only ever serve THIS
        // chain's image. Anything else is a 404, and a 404 makes the boot apply the chain.
        if (!url.endsWith(name) || !existsSync(file)) return next()
        res.setHeader('Content-Type', 'application/gzip')
        res.end(await readFile(file))
      })
    },
  }
}

export default defineConfig({
  base: '/byeharu-voyage/',
  plugins: [react(), tailwindcss(), worldImage()],
})
