// Port roster — the Americas.
export default [
  // ---------- Caribbean & the Spanish Main ----------
  { id: 'havana', name: 'Havana', localName: 'La Habana', wiki: 'Havana', country: 'CU', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['San Cristóbal de La Habana'],
    goods: ['sugar', 'tobacco', 'hides', 'silver', 'timber'],
    notes: 'Assembly point where the New Spain and Tierra Firme fleets joined before the convoy run home to Seville.' },
  { id: 'santiago-de-cuba', name: 'Santiago de Cuba', localName: 'Santiago de Cuba', wiki: 'Santiago de Cuba', country: 'CU', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Santiago de Cuba'],
    goods: ['copper', 'sugar', 'hides', 'tobacco'],
    notes: 'Founded 1515 as Cuba’s first capital; its El Cobre mines were among the earliest worked in the Americas.' },
  { id: 'santo-domingo', name: 'Santo Domingo', localName: 'Santo Domingo', wiki: 'Santo Domingo', country: 'DO', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Santo Domingo de Guzmán'],
    goods: ['sugar', 'hides', 'ginger', 'brazilwood'],
    notes: 'Founded 1496, the oldest continuously inhabited European city in the Americas and seat of the first audiencia.' },
  { id: 'san-juan', name: 'San Juan', localName: 'San Juan', wiki: 'San Juan, Puerto Rico', country: 'PR', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Puerto Rico', 'San Juan Bautista'],
    goods: ['sugar', 'ginger', 'hides', 'timber'],
    notes: 'Its El Morro castle, begun 1539, guarded the first Spanish landfall on the run in from the Atlantic.' },
  { id: 'port-royal', name: 'Port Royal', localName: 'Port Royal', wiki: 'Port Royal', country: 'JM', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Cagway', 'Point Cagway'],
    goods: ['sugar', 'logwood', 'wine', 'hides'],
    notes: 'English base on Jamaica after the 1655 conquest; a buccaneer haven until the earthquake of 1692 sank most of it.' },
  { id: 'willemstad', name: 'Willemstad', localName: 'Willemstad', wiki: 'Willemstad', country: 'CW', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Willemstad', 'Curaçao'],
    goods: ['salt', 'hides', 'tobacco', 'logwood'],
    notes: 'Dutch West India Company took Curacao in 1634 for its salt pans and its deep Schottegat harbour.' },
  { id: 'bridgetown', name: 'Bridgetown', localName: 'Bridgetown', wiki: 'Bridgetown', country: 'BB', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Indian Bridge', 'St Michael’s Town'],
    goods: ['sugar', 'cotton-raw', 'tobacco', 'wine'],
    notes: 'English settlement of 1628; Barbados turned to sugar in the 1640s and became the model plantation colony.' },
  { id: 'port-of-spain', name: 'Port of Spain', localName: 'Puerto de España', wiki: 'Port of Spain', country: 'TT', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Puerto de España', 'Conquerabia'],
    goods: ['tobacco', 'cacao', 'tar', 'hides'],
    notes: 'Trinidad’s Gulf of Paria anchorage; Raleigh careened here in 1595 and used the Pitch Lake for his ships.' },
  { id: 'cumana', name: 'Cumana', localName: 'Cumaná', wiki: 'Cumaná', country: 'VE', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Nueva Toledo', 'Cumaná'],
    goods: ['pearls', 'salt', 'cacao', 'tobacco'],
    notes: 'Founded 1515 on the pearl coast opposite Cubagua, the earliest mainland Spanish town in South America.' },
  { id: 'maracaibo', name: 'Maracaibo', localName: 'Maracaibo', wiki: 'Maracaibo', country: 'VE', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Nueva Zamora de Maracaibo'],
    goods: ['cacao', 'hides', 'tobacco', 'logwood'],
    notes: 'Lake Maracaibo town whose narrow bar made it a repeated buccaneer target in the 17th century.' },
  { id: 'cartagena', name: 'Cartagena', localName: 'Cartagena de Indias', wiki: 'Cartagena, Colombia', country: 'CO', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['Cartagena de Indias'],
    goods: ['gold', 'diamonds', 'hides', 'sugar'],
    notes: 'Founded 1533; the fortified treasure port of the Tierra Firme fleet, sacked by Drake in 1586.' },
  { id: 'portobelo', name: 'Portobelo', localName: 'Portobelo', wiki: 'Portobelo', country: 'PA', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Puerto Bello', 'Nombre de Dios'],
    goods: ['silver', 'gold', 'pearls', 'cacao'],
    notes: 'Caribbean end of the isthmus mule road; its trade fairs handled the Peruvian silver from 1597.' },
  { id: 'veracruz', name: 'Veracruz', localName: 'Veracruz', wiki: 'Veracruz (city)', country: 'MX', sea: 'gulf-of-mexico', region: 'caribbean', tier: 1,
    historicalNames: ['La Villa Rica de la Vera Cruz', 'San Juan de Ulúa'],
    goods: ['silver', 'cochineal', 'sugar', 'cacao', 'hides'],
    notes: 'New Spain’s Atlantic port, where Cortes landed in 1519 and the fortress of San Juan de Ulua sheltered the fleets.' },
  { id: 'campeche', name: 'Campeche', localName: 'San Francisco de Campeche', wiki: 'Campeche (city)', country: 'MX', sea: 'gulf-of-mexico', region: 'caribbean', tier: 3,
    historicalNames: ['San Francisco de Campeche', 'Can Pech'],
    goods: ['logwood', 'salt', 'hides', 'wax'],
    notes: 'Yucatan port shipping the logwood dye that drew buccaneers and eventually English cutters to the coast.' },

  // ---------- North America, Atlantic ----------
  { id: 'st-augustine', name: 'St. Augustine', localName: 'San Agustín', wiki: 'St. Augustine, Florida', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['San Agustín'],
    goods: ['hides', 'timber', 'gum-arabic'],
    notes: 'Founded 1565 to guard the Bahama Channel where the treasure fleets turned north; oldest European city in the United States.' },
  { id: 'jamestown', name: 'Jamestown', localName: 'Jamestown', wiki: 'Jamestown', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['James Fort', 'Jamestown'],
    goods: ['tobacco', 'timber', 'gum-arabic', 'furs'],
    notes: 'Established 1607 on the James river; the first English settlement in America to survive, on tobacco after 1614.' },
  { id: 'new-york', name: 'New York', localName: 'New York', wiki: 'New York City', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['New Amsterdam', 'Nieuw Amsterdam'],
    goods: ['furs', 'timber', 'wheat', 'tobacco'],
    notes: 'New Amsterdam, chartered 1625 at the Hudson mouth as the Dutch West India Company’s beaver-trade capital.' },
  { id: 'boston', name: 'Boston', localName: 'Boston', wiki: 'Boston', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Shawmut', 'Boston'],
    goods: ['dried-fish', 'timber', 'furs', 'naval-timber'],
    notes: 'Founded 1630 by the Massachusetts Bay Company; its cod and shipbuilding drove the early New England economy.' },
  { id: 'plymouth-ma', name: 'Plymouth', localName: 'Plymouth', wiki: 'Plymouth, Massachusetts', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['Patuxet', 'New Plymouth'],
    goods: ['furs', 'dried-fish', 'timber'],
    notes: 'Landing place of the Mayflower in 1620 and capital of the separate Plymouth Colony until 1691.' },
  { id: 'st-georges-bermuda', name: "St. George's", localName: "St. George's", wiki: "St. George's, Bermuda", country: 'BM', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ["St George's Town", 'Somers Isles'],
    goods: ['tobacco', 'ambergris', 'timber', 'salt'],
    notes: 'Settled after the Sea Venture wreck of 1609; a mid-Atlantic waypoint on the homeward sailing route from the Caribbean.' },
  { id: 'annapolis-royal', name: 'Annapolis Royal', localName: 'Annapolis Royal', wiki: 'Annapolis Royal', country: 'CA', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['Port-Royal', 'Annapolis Royal'],
    goods: ['furs', 'dried-fish', 'timber'],
    notes: 'Port-Royal, founded 1605 in the Annapolis Basin, was the first lasting French settlement in Acadia.' },
  { id: 'quebec-city', name: 'Quebec City', localName: 'Ville de Québec', wiki: 'Quebec City', country: 'CA', sea: 'gulf-of-saint-lawrence', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Québec', 'Stadacona'],
    goods: ['furs', 'timber', 'wheat'],
    notes: 'Champlain’s habitation of 1608 at the narrowing of the St Lawrence, the capital of New France.' },
  { id: 'tadoussac', name: 'Tadoussac', localName: 'Tadoussac', wiki: 'Tadoussac', country: 'CA', sea: 'gulf-of-saint-lawrence', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['Tadoussac'],
    goods: ['furs', 'whale-oil', 'dried-fish'],
    notes: 'Saguenay river trading post from 1600, the oldest French fur-trade station in North America.' },
  { id: 'st-johns-nl', name: "St. John's", localName: "St. John's", wiki: "St. John's, Newfoundland and Labrador", country: 'CA', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ["St John's", 'Sam Johns'],
    goods: ['dried-fish', 'whale-oil', 'furs'],
    notes: 'Sheltered harbour used by fishing fleets from the early 1500s; Gilbert claimed it for England in 1583.' },

  // ---------- South America, Atlantic ----------
  { id: 'belem', name: 'Belem', localName: 'Belém', wiki: 'Belém', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santa Maria de Belém do Grão-Pará'],
    goods: ['cacao', 'gum-arabic', 'timber', 'cloves'],
    notes: 'Founded 1616 at the Amazon mouth to shut French and Dutch traders out of the river.' },
  { id: 'sao-luis', name: 'Sao Luis', localName: 'São Luís', wiki: 'São Luís, Maranhão', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['São Luís', 'Saint-Louis de Maragnan'],
    goods: ['cotton-raw', 'sugar', 'timber'],
    notes: 'Founded by the French as Saint-Louis in 1612 and taken by Portugal in 1615, the only French-founded Brazilian capital.' },
  { id: 'recife', name: 'Recife', localName: 'Recife', wiki: 'Recife', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Recife', 'Mauritsstad'],
    goods: ['sugar', 'brazilwood', 'tobacco', 'cotton-raw'],
    notes: 'Reef-sheltered port of Pernambuco and capital of Dutch Brazil under Johan Maurits, 1637-1644.' },
  { id: 'olinda', name: 'Olinda', localName: 'Olinda', wiki: 'Olinda', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Olinda'],
    goods: ['sugar', 'brazilwood', 'cotton-raw'],
    notes: 'Captaincy seat of Pernambuco, the richest sugar district of 16th-century Brazil; burned by the Dutch in 1631.' },
  { id: 'salvador', name: 'Salvador', localName: 'Salvador', wiki: 'Salvador, Bahia', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 1,
    historicalNames: ['São Salvador da Bahia de Todos os Santos'],
    goods: ['sugar', 'tobacco', 'brazilwood', 'hides'],
    notes: 'Founded 1549 in the Bay of All Saints as the first capital of Brazil; briefly Dutch-held in 1624-1625.' },
  { id: 'rio-de-janeiro', name: 'Rio de Janeiro', localName: 'Rio de Janeiro', wiki: 'Rio de Janeiro', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['São Sebastião do Rio de Janeiro', 'France Antarctique'],
    goods: ['sugar', 'brazilwood', 'hides', 'whale-oil'],
    notes: 'Founded 1565 in Guanabara Bay after the expulsion of the French colony of France Antarctique.' },
  { id: 'santos', name: 'Santos', localName: 'Santos', wiki: 'Santos, São Paulo', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santos'],
    goods: ['sugar', 'brazilwood', 'hides'],
    notes: 'Founded 1546 on the estuary below the Serra do Mar; Cavendish raided it during his 1591 voyage.' },
  { id: 'sao-vicente', name: 'Sao Vicente', localName: 'São Vicente', wiki: 'São Vicente, São Paulo', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['São Vicente'],
    goods: ['sugar', 'brazilwood', 'cotton-raw'],
    notes: 'Established 1532 by Martim Afonso de Sousa, the first permanent Portuguese town in Brazil.' },
  { id: 'buenos-aires', name: 'Buenos Aires', localName: 'Buenos Aires', wiki: 'Buenos Aires', country: 'AR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Santa María del Buen Ayre'],
    goods: ['hides', 'wax', 'silver', 'salted-beef'],
    notes: 'Refounded 1580 on the Rio de la Plata; a legal backwater that thrived on contraband silver from Potosi.' },
  { id: 'paramaribo', name: 'Paramaribo', localName: 'Paramaribo', wiki: 'Paramaribo', country: 'SR', sea: 'north-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Paramaribo', 'Willoughbyland'],
    goods: ['sugar', 'tobacco', 'logwood', 'cochineal'],
    notes: 'Suriname river settlement founded by the English in 1651 and ceded to the Dutch in 1667.' },

  // ---------- Pacific Americas ----------
  { id: 'panama-city', name: 'Panama City', localName: 'Ciudad de Panamá', wiki: 'Panama City', country: 'PA', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Panamá Viejo', 'Nuestra Señora de la Asunción de Panamá'],
    goods: ['silver', 'gold', 'pearls', 'cacao'],
    notes: 'Founded 1519 as the Pacific end of the isthmus crossing; Morgan destroyed the old city in 1671.' },
  { id: 'guayaquil', name: 'Guayaquil', localName: 'Guayaquil', wiki: 'Guayaquil', country: 'EC', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Santiago de Guayaquil'],
    goods: ['cacao', 'timber', 'hides', 'gum-arabic'],
    notes: 'Guayas river port and the main shipyard of the Spanish Pacific, using local guachapelí hardwood.' },
  { id: 'callao', name: 'Callao', localName: 'Callao', wiki: 'Callao', country: 'PE', sea: 'south-pacific', region: 'pacific-americas', tier: 1,
    historicalNames: ['El Callao'],
    goods: ['silver', 'wine', 'cacao'],
    notes: 'Port of Lima from 1537 and the loading point of the Potosi silver bound north for the Panama fairs.' },
  { id: 'arica', name: 'Arica', localName: 'Arica', wiki: 'Arica', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['San Marcos de Arica'],
    goods: ['silver', 'wine', 'cotton-raw'],
    notes: 'Shipping point where Potosi silver reached the Pacific after the mule descent from the altiplano.' },
  { id: 'valparaiso', name: 'Valparaiso', localName: 'Valparaíso', wiki: 'Valparaíso', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Valparaíso'],
    goods: ['wheat', 'wine', 'hides', 'wax'],
    notes: 'Port of Santiago from 1544, sending Chilean wheat north to Peru; raided by Drake in 1578.' },
  { id: 'acapulco', name: 'Acapulco', localName: 'Acapulco', wiki: 'Acapulco', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Acapulco de Juárez'],
    goods: ['silver', 'silk-cloth', 'porcelain', 'cacao'],
    notes: 'American terminus of the Manila galleon from 1565; its annual fair traded Mexican silver for Asian goods.' },
];
