// Port roster — the Americas.
export default [
  // ---------- Caribbean & the Spanish Main ----------
  { id: 'havana', name: 'Havana', localName: 'La Habana', wiki: 'Havana', country: 'CU', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['San Cristóbal de La Habana'],
    goods: ['sugar', 'tobacco', 'hides', 'silver', 'timber', 'salted-beef', 'salt', 'cedar'],
    notes: 'Assembly point where the New Spain and Tierra Firme fleets joined before the convoy run home to Seville.' },
  { id: 'santo-domingo', name: 'Santo Domingo', localName: 'Santo Domingo', wiki: 'Santo Domingo', country: 'DO', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Santo Domingo de Guzmán'],
    goods: ['sugar', 'hides', 'ginger', 'maize', 'tallow', 'guaiacum', 'cacao'],
    notes: 'Founded 1496, the oldest continuously inhabited European city in the Americas and seat of the first audiencia.' },
  { id: 'san-juan', name: 'San Juan', localName: 'San Juan', wiki: 'San Juan, Puerto Rico', country: 'PR', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Puerto Rico', 'San Juan Bautista'],
    goods: ['sugar', 'ginger', 'hides', 'timber', 'cacao'],
    notes: 'Its El Morro castle, begun 1539, guarded the first Spanish landfall on the run in from the Atlantic.' },
  { id: 'port-royal', name: 'Port Royal', localName: 'Port Royal', wiki: 'Port Royal', country: 'JM', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Cagway', 'Point Cagway'],
    goods: ['sugar', 'rum', 'allspice', 'tortoiseshell', 'logwood'],
    notes: 'English base on Jamaica after the 1655 conquest; a buccaneer haven until the earthquake of 1692 sank most of it.' },
  { id: 'willemstad', name: 'Willemstad', localName: 'Willemstad', wiki: 'Willemstad', country: 'CW', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Willemstad', 'Curaçao'],
    goods: ['salt', 'hides', 'guaiacum', 'salted-beef', 'logwood'],
    notes: 'Dutch West India Company took Curacao in 1634 for its salt pans and its deep Schottegat harbour.' },
  { id: 'bridgetown', name: 'Bridgetown', localName: 'Bridgetown', wiki: 'Bridgetown', country: 'BB', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Indian Bridge', 'St Michael’s Town'],
    goods: ['sugar', 'cotton-raw', 'tobacco', 'rum', 'molasses'],
    notes: 'English settlement of 1628; Barbados turned to sugar in the 1640s and became the model plantation colony.' },
  { id: 'cumana', name: 'Cumana', localName: 'Cumaná', wiki: 'Cumaná', country: 'VE', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Nueva Toledo', 'Cumaná'],
    goods: ['pearls', 'salt', 'cacao', 'tobacco', 'annatto'],
    notes: 'Founded 1515 on the pearl coast opposite Cubagua, the earliest mainland Spanish town in South America.' },
  { id: 'cartagena', name: 'Cartagena', localName: 'Cartagena de Indias', wiki: 'Cartagena, Colombia', country: 'CO', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['Cartagena de Indias'],
    goods: ['gold', 'diamonds', 'hides', 'sugar', 'chillies', 'emeralds', 'tobacco', 'pearls', 'cacao'],
    notes: 'Founded 1533; the fortified treasure port of the Tierra Firme fleet, sacked by Drake in 1586.' },
  { id: 'portobelo', name: 'Portobelo', localName: 'Portobelo', wiki: 'Portobelo', country: 'PA', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Puerto Bello', 'Nombre de Dios'],
    goods: ['silver', 'gold', 'pearls', 'cacao', 'sarsaparilla', 'hides'],
    notes: 'Caribbean end of the isthmus mule road; its trade fairs handled the Peruvian silver from 1597.' },
  { id: 'veracruz', name: 'Veracruz', localName: 'Veracruz', wiki: 'Veracruz (city)', country: 'MX', sea: 'gulf-of-mexico', region: 'caribbean', tier: 1,
    historicalNames: ['La Villa Rica de la Vera Cruz', 'San Juan de Ulúa'],
    goods: ['silver', 'cochineal', 'cacao', 'chillies', 'vanilla', 'maize', 'sarsaparilla', 'jalap', 'indigo'],
    notes: 'New Spain’s Atlantic port, where Cortes landed in 1519 and the fortress of San Juan de Ulua sheltered the fleets.' },

  // ---------- North America, Atlantic ----------
  { id: 'st-augustine', name: 'St. Augustine', localName: 'San Agustín', wiki: 'St. Augustine, Florida', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['San Agustín'],
    goods: ['hides', 'timber', 'sassafras', 'salt'],
    notes: 'Founded 1565 to guard the Bahama Channel where the treasure fleets turned north; oldest European city in the United States.' },
  { id: 'jamestown', name: 'Jamestown', localName: 'Jamestown', wiki: 'Jamestown', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['James Fort', 'Jamestown'],
    goods: ['tobacco', 'timber', 'sassafras', 'furs', 'dried-fish'],
    notes: 'Established 1607 on the James river; the first English settlement in America to survive, on tobacco after 1614.' },
  { id: 'new-york', name: 'New York', localName: 'New York', wiki: 'New York City', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['New Amsterdam', 'Nieuw Amsterdam'],
    goods: ['furs', 'timber', 'wheat', 'tobacco', 'hides', 'naval-timber'],
    notes: 'New Amsterdam, chartered 1625 at the Hudson mouth as the Dutch West India Company’s beaver-trade capital.' },
  { id: 'boston', name: 'Boston', localName: 'Boston', wiki: 'Boston', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Shawmut', 'Boston'],
    goods: ['dried-fish', 'timber', 'furs', 'naval-timber', 'salted-beef'],
    notes: 'Founded 1630 by the Massachusetts Bay Company; its cod and shipbuilding drove the early New England economy.' },
  { id: 'st-georges-bermuda', name: "St. George's", localName: "St. George's", wiki: "St. George's, Bermuda", country: 'BM', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ["St George's Town", 'Somers Isles'],
    goods: ['tobacco', 'ambergris', 'cedar', 'salt', 'dried-fish'],
    notes: 'Settled after the Sea Venture wreck of 1609; a mid-Atlantic waypoint on the homeward sailing route from the Caribbean.' },
  { id: 'quebec-city', name: 'Quebec City', localName: 'Ville de Québec', wiki: 'Quebec City', country: 'CA', sea: 'gulf-of-saint-lawrence', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Québec', 'Stadacona'],
    goods: ['furs', 'timber', 'wheat', 'dried-fish', 'naval-timber'],
    notes: 'Champlain’s habitation of 1608 at the narrowing of the St Lawrence, the capital of New France.' },
  { id: 'st-johns-nl', name: "St. John's", localName: "St. John's", wiki: "St. John's, Newfoundland and Labrador", country: 'CA', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ["St John's", 'Sam Johns'],
    goods: ['dried-fish', 'whale-oil', 'furs', 'timber', 'baleen'],
    notes: 'Sheltered harbour used by fishing fleets from the early 1500s; Gilbert claimed it for England in 1583.' },

  // ---------- South America, Atlantic ----------
  { id: 'belem', name: 'Belem', localName: 'Belém', wiki: 'Belém', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santa Maria de Belém do Grão-Pará'],
    goods: ['cacao', 'annatto', 'parrots', 'rice', 'timber'],
    notes: 'Founded 1616 at the Amazon mouth to shut French and Dutch traders out of the river.' },
  { id: 'recife', name: 'Recife', localName: 'Recife', wiki: 'Recife', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Recife', 'Mauritsstad'],
    goods: ['sugar', 'brazilwood', 'tobacco', 'cotton-raw', 'cassava', 'molasses', 'hides'],
    notes: 'Reef-sheltered port of Pernambuco and capital of Dutch Brazil under Johan Maurits, 1637-1644.' },
  { id: 'salvador', name: 'Salvador', localName: 'Salvador', wiki: 'Salvador, Bahia', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 1,
    historicalNames: ['São Salvador da Bahia de Todos os Santos'],
    goods: ['sugar', 'tobacco', 'brazilwood', 'hides', 'cassava', 'cotton-raw', 'whale-oil', 'ginger'],
    notes: 'Founded 1549 in the Bay of All Saints as the first capital of Brazil; briefly Dutch-held in 1624-1625.' },
  { id: 'rio-de-janeiro', name: 'Rio de Janeiro', localName: 'Rio de Janeiro', wiki: 'Rio de Janeiro', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['São Sebastião do Rio de Janeiro', 'France Antarctique'],
    goods: ['sugar', 'brazilwood', 'hides', 'whale-oil', 'cotton-raw', 'cassava'],
    notes: 'Founded 1565 in Guanabara Bay after the expulsion of the French colony of France Antarctique.' },
  { id: 'santos', name: 'Santos', localName: 'Santos', wiki: 'Santos, São Paulo', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santos'],
    goods: ['sugar', 'brazilwood', 'hides', 'cotton-raw'],
    notes: 'Founded 1546 on the estuary below the Serra do Mar; Cavendish raided it during his 1591 voyage.' },
  { id: 'buenos-aires', name: 'Buenos Aires', localName: 'Buenos Aires', wiki: 'Buenos Aires', country: 'AR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Santa María del Buen Ayre'],
    goods: ['hides', 'wax', 'silver', 'salted-beef', 'tallow', 'wheat', 'tobacco'],
    notes: 'Refounded 1580 on the Rio de la Plata; a legal backwater that thrived on contraband silver from Potosi.' },
  { id: 'paramaribo', name: 'Paramaribo', localName: 'Paramaribo', wiki: 'Paramaribo', country: 'SR', sea: 'north-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Paramaribo', 'Willoughbyland'],
    goods: ['sugar', 'tobacco', 'logwood', 'cochineal', 'cotton-raw'],
    notes: 'Suriname river settlement founded by the English in 1651 and ceded to the Dutch in 1667.' },

  // ---------- Pacific Americas ----------
  { id: 'panama-city', name: 'Panama City', localName: 'Ciudad de Panamá', wiki: 'Panama City', country: 'PA', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Panamá Viejo', 'Nuestra Señora de la Asunción de Panamá'],
    goods: ['silver', 'gold', 'pearls', 'cacao', 'hides'],
    notes: 'Founded 1519 as the Pacific end of the isthmus crossing; Morgan destroyed the old city in 1671.' },
  { id: 'callao', name: 'Callao', localName: 'Callao', wiki: 'Callao', country: 'PE', sea: 'south-pacific', region: 'pacific-americas', tier: 1,
    historicalNames: ['El Callao'],
    goods: ['silver', 'wine', 'cacao', 'quicksilver', 'cinchona-bark', 'vicuna-wool', 'wheat', 'hides'],
    notes: 'Port of Lima from 1537 and the loading point of the Potosi silver bound north for the Panama fairs.' },
  { id: 'valparaiso', name: 'Valparaiso', localName: 'Valparaíso', wiki: 'Valparaíso', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Valparaíso'],
    goods: ['wheat', 'wine', 'hides', 'wax', 'copper'],
    notes: 'Port of Santiago from 1544, sending Chilean wheat north to Peru; raided by Drake in 1578.' },
  { id: 'acapulco', name: 'Acapulco', localName: 'Acapulco', wiki: 'Acapulco', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Acapulco de Juárez'],
    goods: ['silver', 'silk-cloth', 'porcelain', 'cacao', 'peru-balsam', 'hides'],
    notes: 'American terminus of the Manila galleon from 1565; its annual fair traded Mexican silver for Asian goods.' },

  // ---------- Pacific Americas, the 2026-09-14 growth (owner: "I see no cities on the left side
  // of america") ----------
  // These entries carry NO `goods`: since 0058/0062/0065 a port's roster is authored in
  // data/ports.json and nowhere else (scripts/build-ports.mjs refuses to run for that reason).
  // Here a port is only what scripts/fetch-coords.mjs needs to resolve its Wikidata coordinate.
  { id: 'san-francisco', name: 'San Francisco', localName: 'San Francisco', wiki: 'San Francisco', country: 'US', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Yerba Buena', 'San Francisco de Asís'],
    notes: 'The bay inside the Golden Gate; the presidio and mission date from 1776 and the Yerba Buena anchorage from 1835, outside the 1500-1650 era.' },
  { id: 'monterey', name: 'Monterey', localName: 'Monterey', wiki: 'Monterey, California', country: 'US', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Puerto de Monterrey'],
    notes: 'Vizcaíno surveyed and named the bay in 1602 as a haven for the Manila galleon; the presidio and capital of Alta California followed in 1770.' },
  { id: 'san-diego', name: 'San Diego', localName: 'San Diego', wiki: 'San Diego', country: 'US', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['San Miguel', 'San Diego de Alcalá'],
    notes: 'Cabrillo anchored in the bay in 1542 and Vizcaíno named it in 1602; the presidio and first Alta California mission were founded in 1769.' },
  { id: 'mazatlan', name: 'Mazatlan', localName: 'Mazatlán', wiki: 'Mazatlán', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Mazatlán', 'Puerto de Mazatlán'],
    notes: 'Spanish landing of 1531 below the Sierra Madre silver camps of Copala and Rosario; a working harbour from the 18th century.' },
  { id: 'barra-de-navidad', name: 'Navidad', localName: 'Barra de Navidad', wiki: 'Barra de Navidad', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Puerto de la Navidad'],
    notes: 'The shipyard bay from which Villalobos sailed for the Philippines in 1542 and Legazpi in 1564, before Acapulco took the galleon.' },
  { id: 'huatulco', name: 'Huatulco', localName: 'Santa Cruz Huatulco', wiki: 'Huatulco', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Santa Cruz Huatulco', 'Guatulco'],
    notes: 'The chief Pacific port of New Spain in the 1530s-1570s, shipping Oaxaca cochineal and cacao to Peru; sacked by Drake in 1579 and Cavendish in 1587.' },
  { id: 'el-realejo', name: 'Realejo', localName: 'El Realejo', wiki: 'El Realejo', country: 'NI', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['El Realejo', 'Puerto de la Posesión'],
    notes: 'Founded 1532; the shipyard of the Pacific coast of Central America, building galleons from Nicaraguan cedar and pitch, and its main port until the 19th century.' },
  { id: 'buenaventura', name: 'Buenaventura', localName: 'Buenaventura', wiki: 'Buenaventura, Valle del Cauca', country: 'CO', sea: 'north-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['San Buenaventura'],
    notes: 'Founded 1540 as the Pacific outlet of Cali and the Chocó gold placers; a mangrove harbour that stayed small under the isthmus route.' },
  { id: 'guayaquil', name: 'Guayaquil', localName: 'Guayaquil', wiki: 'Guayaquil', country: 'EC', sea: 'south-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Santiago de Guayaquil'],
    notes: 'Founded 1537 up the Guayas river; the shipyard of the South Sea, building the Armada del Mar del Sur, and the outlet of Ecuador cacao.' },
  { id: 'paita', name: 'Paita', localName: 'Paita', wiki: 'Paita', country: 'PE', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['San Francisco de Paita'],
    notes: 'The northern port of Peru from 1532, where ships on the Lima-Panama run watered; burned by Cavendish in 1587 and Anson in 1741.' },
  { id: 'arica', name: 'Arica', localName: 'Arica', wiki: 'Arica', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['San Marcos de Arica'],
    notes: 'The port of Potosí from 1545: the silver came down by llama train to Arica and went north to Callao and the Panama fairs.' },
  { id: 'coquimbo', name: 'Coquimbo', localName: 'Coquimbo', wiki: 'Coquimbo', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['La Serena', 'Puerto de Coquimbo'],
    notes: 'The bay below La Serena, founded 1544; the copper and gold outlet of the Norte Chico, raided by Drake in 1578 and Sharp in 1680.' },
  { id: 'concepcion', name: 'Concepcion', localName: 'Concepción', wiki: 'Penco', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Concepción del Nuevo Extremo', 'Penco'],
    notes: 'Founded 1550 at Penco on the Bay of Concepción, the southern garrison of Chile against the Mapuche; the city moved inland to the Biobío after the earthquake of 1751.' },
  { id: 'hobart', name: 'Hobart', localName: 'Hobart', wiki: 'Hobart', country: 'AU', sea: 'tasman-sea', region: 'oceania', tier: 3,
    historicalNames: ['Hobart Town', 'Sullivans Cove'],
    notes: 'Settled 1804 on the Derwent estuary; a whaling and sealing port of the southern ocean, outside the 1500-1650 era like Sydney.' },
];
