// Port roster — the Americas.
export default [
  // ---------- Caribbean & the Spanish Main ----------
  { id: 'havana', name: 'Havana', localName: 'La Habana', wiki: 'Havana', country: 'CU', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['San Cristóbal de La Habana'],
    goods: ['sugar', 'tobacco', 'hides', 'silver', 'timber', 'salted-beef', 'logwood', 'cacao', 'salt'],
    notes: 'Assembly point where the New Spain and Tierra Firme fleets joined before the convoy run home to Seville.' },
  { id: 'santo-domingo', name: 'Santo Domingo', localName: 'Santo Domingo', wiki: 'Santo Domingo', country: 'DO', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Santo Domingo de Guzmán'],
    goods: ['sugar', 'hides', 'ginger', 'brazilwood', 'cacao', 'salted-beef'],
    notes: 'Founded 1496, the oldest continuously inhabited European city in the Americas and seat of the first audiencia.' },
  { id: 'san-juan', name: 'San Juan', localName: 'San Juan', wiki: 'San Juan, Puerto Rico', country: 'PR', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Puerto Rico', 'San Juan Bautista'],
    goods: ['sugar', 'ginger', 'hides', 'timber'],
    notes: 'Its El Morro castle, begun 1539, guarded the first Spanish landfall on the run in from the Atlantic.' },
  { id: 'port-royal', name: 'Port Royal', localName: 'Port Royal', wiki: 'Port Royal', country: 'JM', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Cagway', 'Point Cagway'],
    goods: ['sugar', 'logwood', 'wine', 'hides'],
    notes: 'English base on Jamaica after the 1655 conquest; a buccaneer haven until the earthquake of 1692 sank most of it.' },
  { id: 'willemstad', name: 'Willemstad', localName: 'Willemstad', wiki: 'Willemstad', country: 'CW', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Willemstad', 'Curaçao'],
    goods: ['salt', 'hides', 'tobacco', 'logwood'],
    notes: 'Dutch West India Company took Curacao in 1634 for its salt pans and its deep Schottegat harbour.' },
  { id: 'bridgetown', name: 'Bridgetown', localName: 'Bridgetown', wiki: 'Bridgetown', country: 'BB', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Indian Bridge', 'St Michael’s Town'],
    goods: ['sugar', 'cotton-raw', 'tobacco', 'wine'],
    notes: 'English settlement of 1628; Barbados turned to sugar in the 1640s and became the model plantation colony.' },
  { id: 'cumana', name: 'Cumana', localName: 'Cumaná', wiki: 'Cumaná', country: 'VE', sea: 'caribbean-sea', region: 'caribbean', tier: 3,
    historicalNames: ['Nueva Toledo', 'Cumaná'],
    goods: ['pearls', 'salt', 'cacao', 'tobacco'],
    notes: 'Founded 1515 on the pearl coast opposite Cubagua, the earliest mainland Spanish town in South America.' },
  { id: 'cartagena', name: 'Cartagena', localName: 'Cartagena de Indias', wiki: 'Cartagena, Colombia', country: 'CO', sea: 'caribbean-sea', region: 'caribbean', tier: 1,
    historicalNames: ['Cartagena de Indias'],
    goods: ['gold', 'diamonds', 'hides', 'sugar', 'pearls', 'tobacco', 'cacao', 'indigo', 'logwood'],
    notes: 'Founded 1533; the fortified treasure port of the Tierra Firme fleet, sacked by Drake in 1586.' },
  { id: 'portobelo', name: 'Portobelo', localName: 'Portobelo', wiki: 'Portobelo', country: 'PA', sea: 'caribbean-sea', region: 'caribbean', tier: 2,
    historicalNames: ['Puerto Bello', 'Nombre de Dios'],
    goods: ['silver', 'gold', 'pearls', 'cacao', 'hides', 'logwood'],
    notes: 'Caribbean end of the isthmus mule road; its trade fairs handled the Peruvian silver from 1597.' },
  { id: 'veracruz', name: 'Veracruz', localName: 'Veracruz', wiki: 'Veracruz (city)', country: 'MX', sea: 'gulf-of-mexico', region: 'caribbean', tier: 1,
    historicalNames: ['La Villa Rica de la Vera Cruz', 'San Juan de Ulúa'],
    goods: ['silver', 'cochineal', 'sugar', 'cacao', 'hides', 'indigo', 'logwood', 'tobacco', 'cotton-raw'],
    notes: 'New Spain’s Atlantic port, where Cortes landed in 1519 and the fortress of San Juan de Ulua sheltered the fleets.' },

  // ---------- North America, Atlantic ----------
  { id: 'st-augustine', name: 'St. Augustine', localName: 'San Agustín', wiki: 'St. Augustine, Florida', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ['San Agustín'],
    goods: ['hides', 'timber', 'gum-arabic', 'tar'],
    notes: 'Founded 1565 to guard the Bahama Channel where the treasure fleets turned north; oldest European city in the United States.' },
  { id: 'jamestown', name: 'Jamestown', localName: 'Jamestown', wiki: 'Jamestown', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['James Fort', 'Jamestown'],
    goods: ['tobacco', 'timber', 'gum-arabic', 'furs', 'hides', 'tar'],
    notes: 'Established 1607 on the James river; the first English settlement in America to survive, on tobacco after 1614.' },
  { id: 'new-york', name: 'New York', localName: 'New York', wiki: 'New York City', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['New Amsterdam', 'Nieuw Amsterdam'],
    goods: ['furs', 'timber', 'wheat', 'tobacco', 'whale-oil', 'hides'],
    notes: 'New Amsterdam, chartered 1625 at the Hudson mouth as the Dutch West India Company’s beaver-trade capital.' },
  { id: 'boston', name: 'Boston', localName: 'Boston', wiki: 'Boston', country: 'US', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Shawmut', 'Boston'],
    goods: ['dried-fish', 'timber', 'furs', 'naval-timber', 'salted-beef', 'whale-oil'],
    notes: 'Founded 1630 by the Massachusetts Bay Company; its cod and shipbuilding drove the early New England economy.' },
  { id: 'st-georges-bermuda', name: "St. George's", localName: "St. George's", wiki: "St. George's, Bermuda", country: 'BM', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 3,
    historicalNames: ["St George's Town", 'Somers Isles'],
    goods: ['tobacco', 'ambergris', 'timber', 'salt'],
    notes: 'Settled after the Sea Venture wreck of 1609; a mid-Atlantic waypoint on the homeward sailing route from the Caribbean.' },
  { id: 'quebec-city', name: 'Quebec City', localName: 'Ville de Québec', wiki: 'Quebec City', country: 'CA', sea: 'gulf-of-saint-lawrence', region: 'north-america-atlantic', tier: 2,
    historicalNames: ['Québec', 'Stadacona'],
    goods: ['furs', 'timber', 'wheat', 'dried-fish', 'hides', 'tar'],
    notes: 'Champlain’s habitation of 1608 at the narrowing of the St Lawrence, the capital of New France.' },
  { id: 'st-johns-nl', name: "St. John's", localName: "St. John's", wiki: "St. John's, Newfoundland and Labrador", country: 'CA', sea: 'north-atlantic', region: 'north-america-atlantic', tier: 2,
    historicalNames: ["St John's", 'Sam Johns'],
    goods: ['dried-fish', 'whale-oil', 'furs', 'timber', 'salt', 'tar'],
    notes: 'Sheltered harbour used by fishing fleets from the early 1500s; Gilbert claimed it for England in 1583.' },

  // ---------- South America, Atlantic ----------
  { id: 'belem', name: 'Belem', localName: 'Belém', wiki: 'Belém', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santa Maria de Belém do Grão-Pará'],
    goods: ['cacao', 'gum-arabic', 'timber', 'cloves'],
    notes: 'Founded 1616 at the Amazon mouth to shut French and Dutch traders out of the river.' },
  { id: 'recife', name: 'Recife', localName: 'Recife', wiki: 'Recife', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Recife', 'Mauritsstad'],
    goods: ['sugar', 'brazilwood', 'tobacco', 'cotton-raw', 'hides', 'timber'],
    notes: 'Reef-sheltered port of Pernambuco and capital of Dutch Brazil under Johan Maurits, 1637-1644.' },
  { id: 'salvador', name: 'Salvador', localName: 'Salvador', wiki: 'Salvador, Bahia', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 1,
    historicalNames: ['São Salvador da Bahia de Todos os Santos'],
    goods: ['sugar', 'tobacco', 'brazilwood', 'hides', 'cotton-raw', 'ginger', 'timber', 'salted-beef', 'cacao'],
    notes: 'Founded 1549 in the Bay of All Saints as the first capital of Brazil; briefly Dutch-held in 1624-1625.' },
  { id: 'rio-de-janeiro', name: 'Rio de Janeiro', localName: 'Rio de Janeiro', wiki: 'Rio de Janeiro', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['São Sebastião do Rio de Janeiro', 'France Antarctique'],
    goods: ['sugar', 'brazilwood', 'hides', 'whale-oil', 'salted-beef', 'timber'],
    notes: 'Founded 1565 in Guanabara Bay after the expulsion of the French colony of France Antarctique.' },
  { id: 'santos', name: 'Santos', localName: 'Santos', wiki: 'Santos, São Paulo', country: 'BR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Santos'],
    goods: ['sugar', 'brazilwood', 'hides', 'tobacco'],
    notes: 'Founded 1546 on the estuary below the Serra do Mar; Cavendish raided it during his 1591 voyage.' },
  { id: 'buenos-aires', name: 'Buenos Aires', localName: 'Buenos Aires', wiki: 'Buenos Aires', country: 'AR', sea: 'south-atlantic', region: 'south-america-atlantic', tier: 2,
    historicalNames: ['Santa María del Buen Ayre'],
    goods: ['hides', 'wax', 'silver', 'salted-beef', 'wool-raw', 'horses'],
    notes: 'Refounded 1580 on the Rio de la Plata; a legal backwater that thrived on contraband silver from Potosi.' },
  { id: 'paramaribo', name: 'Paramaribo', localName: 'Paramaribo', wiki: 'Paramaribo', country: 'SR', sea: 'north-atlantic', region: 'south-america-atlantic', tier: 3,
    historicalNames: ['Paramaribo', 'Willoughbyland'],
    goods: ['sugar', 'tobacco', 'logwood', 'cochineal'],
    notes: 'Suriname river settlement founded by the English in 1651 and ceded to the Dutch in 1667.' },

  // ---------- Pacific Americas ----------
  { id: 'panama-city', name: 'Panama City', localName: 'Ciudad de Panamá', wiki: 'Panama City', country: 'PA', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Panamá Viejo', 'Nuestra Señora de la Asunción de Panamá'],
    goods: ['silver', 'gold', 'pearls', 'cacao', 'hides', 'timber'],
    notes: 'Founded 1519 as the Pacific end of the isthmus crossing; Morgan destroyed the old city in 1671.' },
  { id: 'callao', name: 'Callao', localName: 'Callao', wiki: 'Callao', country: 'PE', sea: 'south-pacific', region: 'pacific-americas', tier: 1,
    historicalNames: ['El Callao'],
    goods: ['silver', 'wine', 'cacao', 'wheat', 'hides', 'wool-raw', 'sugar', 'olive-oil', 'cotton-raw'],
    notes: 'Port of Lima from 1537 and the loading point of the Potosi silver bound north for the Panama fairs.' },
  { id: 'valparaiso', name: 'Valparaiso', localName: 'Valparaíso', wiki: 'Valparaíso', country: 'CL', sea: 'south-pacific', region: 'pacific-americas', tier: 3,
    historicalNames: ['Valparaíso'],
    goods: ['wheat', 'wine', 'hides', 'wax'],
    notes: 'Port of Santiago from 1544, sending Chilean wheat north to Peru; raided by Drake in 1578.' },
  { id: 'acapulco', name: 'Acapulco', localName: 'Acapulco', wiki: 'Acapulco', country: 'MX', sea: 'north-pacific', region: 'pacific-americas', tier: 2,
    historicalNames: ['Acapulco de Juárez'],
    goods: ['silver', 'silk-cloth', 'porcelain', 'cacao', 'hides', 'indigo'],
    notes: 'American terminus of the Manila galleon from 1565; its annual fair traded Mexican silver for Asian goods.' },
];
