// Port roster — Southeast Asia, China, Korea, Japan and the Pacific.
export default [
  // ---------- Southeast Asia ----------
  { id: 'malacca', name: 'Malacca', localName: 'Melaka', wiki: 'Malacca City', country: 'MY', sea: 'strait-of-malacca', region: 'southeast-asia', tier: 1,
    historicalNames: ['Melaka', 'Malaca'],
    goods: ['cloves', 'nutmeg', 'black-pepper', 'tin', 'porcelain', 'bezoar', 'rice'],
    notes: 'Sultanate taken by Albuquerque in 1511; the strait chokepoint between the Indian Ocean and the China seas.' },
  { id: 'banda-aceh', name: 'Banda Aceh', localName: 'Banda Aceh', wiki: 'Banda Aceh', country: 'ID', sea: 'strait-of-malacca', region: 'southeast-asia', tier: 2,
    historicalNames: ['Aceh Darussalam', 'Achin'],
    goods: ['black-pepper', 'sandalwood', 'gold', 'camphor', 'benzoin', 'rice'],
    notes: 'Sultanate at Sumatra’s northern tip, at its height under Iskandar Muda, 1607-1636, and a rival to Portuguese Malacca.' },
  { id: 'jakarta', name: 'Jakarta', localName: 'Jakarta', wiki: 'Jakarta', country: 'ID', sea: 'java-sea', region: 'southeast-asia', tier: 1,
    historicalNames: ['Batavia', 'Jayakarta', 'Sunda Kelapa'],
    goods: ['cloves', 'nutmeg', 'black-pepper', 'porcelain', 'sugar', 'batik', 'arrack', 'rice'],
    notes: 'Jan Pieterszoon Coen razed Jayakarta in 1619 and built Batavia, the VOC capital in Asia.' },
  { id: 'banten', name: 'Banten', localName: 'Banten', wiki: 'Banten (town)', country: 'ID', sea: 'java-sea', region: 'southeast-asia', tier: 2,
    historicalNames: ['Bantam', 'Banten Girang'],
    goods: ['black-pepper', 'rice', 'sandalwood', 'cubeb', 'batik', 'palm-sugar', 'camphor'],
    notes: 'West Java pepper sultanate where the first Dutch fleet arrived in 1596 and the English opened a factory in 1603.' },
  { id: 'surabaya', name: 'Surabaya', localName: 'Surabaya', wiki: 'Surabaya', country: 'ID', sea: 'java-sea', region: 'southeast-asia', tier: 3,
    historicalNames: ['Surabaya'],
    goods: ['rice', 'cubeb', 'batik', 'rattan', 'sugar'],
    notes: 'East Java river port and shipbuilding town, subdued by Sultan Agung of Mataram in 1625.' },
  { id: 'makassar', name: 'Makassar', localName: 'Makassar', wiki: 'Makassar', country: 'ID', sea: 'makassar-strait', region: 'southeast-asia', tier: 2,
    historicalNames: ['Macassar', 'Ujung Pandang'],
    goods: ['cloves', 'sandalwood', 'coral', 'rice', 'sago', 'birds-nests', 'trepang'],
    notes: 'Gowa sultanate’s free port, where Portuguese, English and Danish traders evaded the Dutch spice monopoly until 1667.' },
  { id: 'ternate', name: 'Ternate', localName: 'Ternate', wiki: 'Ternate', country: 'ID', sea: 'molucca-sea', region: 'southeast-asia', tier: 2,
    historicalNames: ['Ternate', 'Gapi'],
    goods: ['cloves', 'rice', 'coral', 'paradise-plumes', 'sago'],
    notes: 'Clove sultanate; the Portuguese fort of 1522 was expelled in 1575 and the Dutch took over from 1607.' },
  { id: 'banda-neira', name: 'Banda Neira', localName: 'Banda Neira', wiki: 'Banda Neira', country: 'ID', sea: 'banda-sea', region: 'southeast-asia', tier: 2,
    historicalNames: ['Bandaneira'],
    goods: ['nutmeg', 'mace', 'rice', 'paradise-plumes', 'sago'],
    notes: 'The Banda islands were the world’s only source of nutmeg and mace; Coen’s conquest of 1621 destroyed their society.' },
  { id: 'ambon', name: 'Ambon', localName: 'Ambon', wiki: 'Ambon, Maluku', country: 'ID', sea: 'banda-sea', region: 'southeast-asia', tier: 2,
    historicalNames: ['Amboina', 'Amboyna'],
    goods: ['cloves', 'rice', 'nutmeg', 'sago', 'coconuts'],
    notes: 'VOC headquarters in the Moluccas from 1605; site of the Amboyna executions of English merchants in 1623.' },
  { id: 'kupang', name: 'Kupang', localName: 'Kupang', wiki: 'Kupang', country: 'ID', sea: 'timor-sea', region: 'oceania', tier: 3,
    historicalNames: ['Coepang'],
    goods: ['sandalwood', 'wax', 'rice', 'sharks-fin', 'trepang'],
    notes: 'West Timor harbour where the VOC built Fort Concordia in 1653 to contest the sandalwood trade.' },
  { id: 'dili', name: 'Dili', localName: 'Díli', wiki: 'Dili', country: 'TL', sea: 'banda-sea', region: 'oceania', tier: 3,
    historicalNames: ['Dilly'],
    goods: ['sandalwood', 'wax', 'barkcloth', 'trepang', 'rice'],
    notes: 'Portuguese Timor’s coast, worked for sandalwood from the 1510s; Dili became the capital in 1769.' },
  { id: 'ayutthaya', name: 'Ayutthaya', localName: 'พระนครศรีอยุธยา', wiki: 'Phra Nakhon Si Ayutthaya (city)', country: 'TH', sea: 'gulf-of-thailand', region: 'southeast-asia', tier: 2,
    historicalNames: ['Ayutthaya', 'Judea', 'Siam'],
    goods: ['sappanwood', 'hides', 'rice', 'galangal', 'celadon', 'benzoin', 'gamboge'],
    notes: 'Chao Phraya river capital of Siam, reachable by seagoing ships and host to Portuguese, Dutch, Japanese and French quarters.' },
  { id: 'pattani', name: 'Pattani', localName: 'ปัตตานี', wiki: 'Pattani, Thailand', country: 'TH', sea: 'gulf-of-thailand', region: 'southeast-asia', tier: 3,
    historicalNames: ['Patani'],
    goods: ['black-pepper', 'gold', 'sappanwood', 'birds-nests', 'rice'],
    notes: 'Malay sultanate on the Gulf of Siam where the Dutch opened their first Southeast Asian factory in 1602.' },
  { id: 'hoi-an', name: 'Hoi An', localName: 'Hội An', wiki: 'Hội An', qid: 'Q36160', country: 'VN', sea: 'south-china-sea', region: 'southeast-asia', tier: 2,
    historicalNames: ['Faifo', 'Hai Pho'],
    goods: ['silk-raw', 'sandalwood', 'porcelain', 'cassia', 'galangal', 'aloeswood', 'sappanwood'],
    notes: 'Nguyen-ruled Cochinchina port with permanent Japanese and Chinese quarters, thriving on the shuinsen trade.' },
  { id: 'hanoi', name: 'Hanoi', localName: 'Hà Nội', wiki: 'Hanoi', country: 'VN', sea: 'gulf-of-tonkin', region: 'southeast-asia', tier: 3,
    historicalNames: ['Thăng Long', 'Kẻ Chợ', 'Tonkin'],
    goods: ['silk-raw', 'lacquerware', 'cassia', 'star-anise', 'rice'],
    notes: 'Red River capital of Trinh-ruled Tonkin; Dutch and English factories traded here through the downstream port of Pho Hien.' },
  { id: 'manila', name: 'Manila', localName: 'Maynila', wiki: 'Manila', country: 'PH', sea: 'south-china-sea', region: 'southeast-asia', tier: 1,
    historicalNames: ['Maynila', 'Intramuros'],
    goods: ['silver', 'silk-cloth', 'porcelain', 'wax', 'gold', 'abaca', 'rice', 'tortoiseshell', 'mother-of-pearl'],
    notes: 'Spanish capital from 1571 and Asian terminus of the Acapulco galleon, exchanging American silver for Chinese silk.' },
  { id: 'cebu', name: 'Cebu', localName: 'Sugbo', wiki: 'Cebu City', country: 'PH', sea: 'visayan-sea', region: 'southeast-asia', tier: 3,
    historicalNames: ['Sugbo', 'Villa de San Miguel'],
    goods: ['gold', 'tortoiseshell', 'sharks-fin', 'mother-of-pearl', 'abaca'],
    notes: 'Magellan was killed on nearby Mactan in 1521; Legazpi founded the first Spanish settlement here in 1565.' },

  // ---------- China & Taiwan ----------
  { id: 'guangzhou', name: 'Guangzhou', localName: '廣州', wiki: 'Guangzhou', country: 'CN', sea: 'south-china-sea', region: 'china-coast', tier: 1,
    historicalNames: ['Canton', 'Panyu'],
    goods: ['silk-cloth', 'porcelain', 'tea', 'ginseng', 'lacquerware', 'cassia', 'star-anise', 'vermilion', 'sugar'],
    notes: 'Pearl River city whose twice-yearly fairs were the licensed point of contact for foreign trade with China.' },
  { id: 'macau', name: 'Macau', localName: '澳門', wiki: 'Macau', country: 'MO', sea: 'south-china-sea', region: 'china-coast', tier: 1,
    historicalNames: ['Macao', 'Amacao'],
    goods: ['silk-raw', 'porcelain', 'gold', 'silver', 'musk', 'china-root', 'tea'],
    notes: 'Portuguese settlement tolerated from 1557; the pivot of the Macau-Nagasaki silk-for-silver run.' },
  { id: 'hong-kong', name: 'Hong Kong', localName: '香港', wiki: 'Hong Kong', country: 'HK', sea: 'south-china-sea', region: 'china-coast', tier: 3,
    historicalNames: ['Hong Kong', 'Tuen Mun'],
    goods: ['salt', 'frankincense', 'pearls', 'dried-fish', 'porcelain'],
    notes: 'Its name derives from the incense trade of the harbour; a salt and fishing district until British occupation in 1841.' },
  { id: 'quanzhou', name: 'Quanzhou', localName: '泉州', wiki: 'Quanzhou', country: 'CN', sea: 'taiwan-strait', region: 'china-coast', tier: 2,
    historicalNames: ['Zayton', 'Citong'],
    goods: ['silk-cloth', 'porcelain', 'tea', 'sugar', 'copper-cash', 'rhubarb', 'iron'],
    notes: 'The Zayton praised by Marco Polo; its harbour silted and Ming sea bans pushed trade to neighbouring ports.' },
  { id: 'xiamen', name: 'Xiamen', localName: '廈門', wiki: 'Xiamen', country: 'CN', sea: 'taiwan-strait', region: 'china-coast', tier: 2,
    historicalNames: ['Amoy', 'Zhongzuo'],
    goods: ['silk-cloth', 'porcelain', 'sugar', 'tea', 'lychees', 'china-root', 'copper-cash'],
    notes: 'Fujian island harbour and the base from which Zheng Chenggong ran his maritime empire in the 1650s.' },
  { id: 'fuzhou', name: 'Fuzhou', localName: '福州', wiki: 'Fuzhou', country: 'CN', sea: 'taiwan-strait', region: 'china-coast', tier: 3,
    historicalNames: ['Foochow', 'Minhou'],
    goods: ['tea', 'lacquerware', 'cassia', 'lychees', 'sugar'],
    notes: 'Min river port designated by the Ming for tribute missions arriving from the Ryukyu kingdom.' },
  { id: 'ningbo', name: 'Ningbo', localName: '寧波', wiki: 'Ningbo', country: 'CN', sea: 'east-china-sea', region: 'china-coast', tier: 2,
    historicalNames: ['Liampo', 'Mingzhou'],
    goods: ['silk-raw', 'porcelain', 'copper-cash', 'paper', 'ink-sticks', 'rhubarb', 'tea'],
    notes: 'Ming-designated port for Japanese tribute missions and the base of the smuggling entrepot at Shuangyu, destroyed in 1548.' },
  { id: 'tainan', name: 'Tainan', localName: '臺南', wiki: 'Tainan', country: 'TW', sea: 'taiwan-strait', region: 'china-coast', tier: 2,
    historicalNames: ['Tayouan', 'Anping', 'Fort Zeelandia'],
    goods: ['hides', 'sugar', 'silk-raw', 'timber', 'rice'],
    notes: 'The VOC built Fort Zeelandia here in 1624; Zheng Chenggong expelled the Dutch in 1662.' },

  // ---------- Korea ----------
  { id: 'busan', name: 'Busan', localName: '부산', wiki: 'Busan', country: 'KR', sea: 'korea-strait', region: 'korea', tier: 1,
    historicalNames: ['Pusan', '東萊 Dongnae', '釜山浦 Busanpo'],
    goods: ['ginseng', 'ramie-cloth', 'rice', 'dried-fish', 'silver', 'celadon', 'tiger-skins', 'cotton-cloth'],
    notes: 'Site of the Waegwan, the walled Japan House that was Joseon Korea’s only licensed trading post with Tsushima.' },
  { id: 'incheon', name: 'Incheon', localName: '인천', wiki: 'Incheon', country: 'KR', sea: 'yellow-sea', region: 'korea', tier: 2,
    historicalNames: ['Jemulpo', '仁川 Incheon', 'Michuhol'],
    goods: ['rice', 'salt', 'ramie-cloth', 'ginseng', 'paper', 'ink-sticks', 'hides'],
    notes: 'Yellow Sea approach to Hanyang, the Joseon capital; the sea road for envoys and tribute to Ming China.' },
  { id: 'ulsan', name: 'Ulsan', localName: '울산', wiki: 'Ulsan', country: 'KR', sea: 'sea-of-japan', region: 'korea', tier: 3,
    historicalNames: ['Yeompo', '蔚山 Ulsan'],
    goods: ['whale-oil', 'dried-fish', 'salt', 'iron', 'rice'],
    notes: 'One of the three ports opened to Japanese traders in 1426; besieged during the Imjin War in 1597-98.' },
  { id: 'yeosu', name: 'Yeosu', localName: '여수', wiki: 'Yeosu', country: 'KR', sea: 'korea-strait', region: 'korea', tier: 2,
    historicalNames: ['麗水 Yeosu', 'Jeolla Jwasuyeong'],
    goods: ['dried-fish', 'salt', 'timber', 'rice', 'seaweed'],
    notes: 'Headquarters of Yi Sun-sin’s Left Jeolla naval command, from which the turtle ships sailed in 1592.' },
  { id: 'tongyeong', name: 'Tongyeong', localName: '통영', wiki: 'Tongyeong', country: 'KR', sea: 'korea-strait', region: 'korea', tier: 3,
    historicalNames: ['統營 Tongyeong', 'Samdo Sugun Tongjeyeong'],
    goods: ['dried-fish', 'lacquerware', 'salt', 'rice'],
    notes: 'Seat of the combined Three Provinces Naval Command from 1604, in the strait where the battle of Hansando was fought.' },
  { id: 'mokpo', name: 'Mokpo', localName: '목포', wiki: 'Mokpo', country: 'KR', sea: 'yellow-sea', region: 'korea', tier: 3,
    historicalNames: ['木浦 Mokpo'],
    goods: ['rice', 'cotton-cloth', 'salt', 'seaweed', 'ramie-cloth'],
    notes: 'Southwestern harbour among the Jeolla islands; a Joseon garrison post guarding the grain-tribute sea route.' },
  { id: 'jeju', name: 'Jeju', localName: '제주', wiki: 'Jeju City', country: 'KR', sea: 'east-china-sea', region: 'korea', tier: 3,
    historicalNames: ['濟州 Jeju', 'Tamna'],
    goods: ['horses', 'dried-abalone', 'dried-fish', 'seaweed'],
    notes: 'Former kingdom of Tamna, a royal horse-pasture island; Hendrick Hamel’s Dutch crew was wrecked here in 1653.' },
  { id: 'nampo', name: 'Nampo', localName: '남포', wiki: 'Nampo', country: 'KP', sea: 'yellow-sea', region: 'korea', tier: 3,
    historicalNames: ['Chinnampo', '南浦'],
    goods: ['iron', 'ginseng', 'tiger-skins', 'wheat', 'hides'],
    notes: 'Taedong river approach to Pyongyang, on the Yellow Sea route between Korea and Shandong.' },

  // ---------- Japan & Ryukyu ----------
  { id: 'nagasaki', name: 'Nagasaki', localName: '長崎', wiki: 'Nagasaki', country: 'JP', sea: 'east-china-sea', region: 'japan', tier: 1,
    historicalNames: ['Nagasaki', 'Dejima'],
    goods: ['silver', 'copper', 'lacquerware', 'porcelain', 'sandalwood', 'soy-sauce', 'tea', 'dried-fish'],
    notes: 'Opened to Portuguese ships in 1571; after 1641 the Dejima island factory was Japan’s only European window.' },
  { id: 'hirado', name: 'Hirado', localName: '平戸', wiki: 'Hirado, Nagasaki', country: 'JP', sea: 'east-china-sea', region: 'japan', tier: 2,
    historicalNames: ['Firando', '平戸'],
    goods: ['silver', 'silk-raw', 'copper', 'porcelain', 'dried-abalone', 'dried-fish'],
    notes: 'Held the Dutch factory from 1609 and the English from 1613, until both were moved or closed by 1641.' },
  { id: 'sakai', name: 'Sakai', localName: '堺', wiki: 'Sakai', country: 'JP', sea: 'seto-inland-sea', region: 'japan', tier: 2,
    historicalNames: ['Sakai'],
    goods: ['firearms', 'folding-fans', 'sword-blades', 'sake', 'iron', 'silk-cloth', 'tea'],
    notes: 'Self-governing merchant city and gun-founding centre, absorbed under Oda and Toyotomi rule after 1568.' },
  { id: 'osaka', name: 'Osaka', localName: '大阪', wiki: 'Osaka', country: 'JP', sea: 'seto-inland-sea', region: 'japan', tier: 1,
    historicalNames: ['Ōzaka', 'Naniwa'],
    goods: ['rice', 'silver', 'sake', 'cotton-cloth', 'folding-fans', 'soy-sauce', 'iron', 'copper', 'lacquerware'],
    notes: 'Hideyoshi’s castle town of 1583, which became the rice market and "kitchen" of Tokugawa Japan.' },
  { id: 'tokyo', name: 'Tokyo', localName: '東京', wiki: 'Tokyo', country: 'JP', sea: 'north-pacific', region: 'japan', tier: 1,
    historicalNames: ['Edo', '江戸'],
    goods: ['rice', 'lacquerware', 'timber', 'copper', 'dried-fish'],
    notes: 'Edo, seat of the Tokugawa shogunate from 1603 and supplied by coastal shipping into Edo Bay.' },
  { id: 'fukuoka', name: 'Fukuoka', localName: '福岡', wiki: 'Fukuoka', country: 'JP', sea: 'korea-strait', region: 'japan', tier: 2,
    historicalNames: ['Hakata', '博多'],
    goods: ['silk-raw', 'copper', 'porcelain', 'sake', 'rice', 'dried-fish'],
    notes: 'Hakata was Japan’s oldest China-trade harbour and the landing point of the Mongol invasions of 1274 and 1281.' },
  { id: 'kagoshima', name: 'Kagoshima', localName: '鹿児島', wiki: 'Kagoshima', country: 'JP', sea: 'east-china-sea', region: 'japan', tier: 3,
    historicalNames: ['Kagoshima'],
    goods: ['sulphur', 'sugar', 'silver', 'rice', 'timber'],
    notes: 'Satsuma’s castle port, where Francis Xavier landed in 1549 and from which Ryukyu was invaded in 1609.' },
  { id: 'shimonoseki', name: 'Shimonoseki', localName: '下関', wiki: 'Shimonoseki', country: 'JP', sea: 'seto-inland-sea', region: 'japan', tier: 3,
    historicalNames: ['Akamagaseki', 'Bakan'],
    goods: ['rice', 'dried-fish', 'salt', 'seaweed', 'iron'],
    notes: 'Guards the Kanmon Strait between Honshu and Kyushu, the funnel for all Inland Sea coastal traffic.' },
  { id: 'naha', name: 'Naha', localName: '那覇', wiki: 'Naha', country: 'JP', sea: 'east-china-sea', region: 'japan', tier: 2,
    historicalNames: ['Naha', 'Ryukyu'],
    goods: ['sulphur', 'horses', 'lacquerware', 'sappanwood', 'tortoiseshell', 'sugar', 'mother-of-pearl'],
    notes: 'Port of the Ryukyu kingdom, whose ships carried an entrepot trade between China, Japan and Southeast Asia.' },
  { id: 'tsushima', name: 'Tsushima', localName: '対馬', wiki: 'Tsushima, Nagasaki', country: 'JP', sea: 'korea-strait', region: 'japan', tier: 3,
    historicalNames: ['Tsushima', '對馬'],
    goods: ['ginseng', 'silver', 'ramie-cloth', 'dried-fish', 'rice'],
    notes: 'The So clan’s island domain held the sole licence for Japan’s trade and diplomacy with Joseon Korea.' },

  // ---------- Pacific & Oceania ----------
  { id: 'hagatna', name: 'Hagatna', localName: 'Hagåtña', wiki: 'Hagåtña, Guam', country: 'GU', sea: 'philippine-sea', region: 'oceania', tier: 3,
    historicalNames: ['Agaña', 'Hagåtña'],
    goods: ['coconuts', 'hemp', 'rice', 'dried-fish'],
    notes: 'Guam was the Manila galleon’s mid-Pacific watering stop; a Spanish mission was established in 1668.' },
  { id: 'honolulu', name: 'Honolulu', localName: 'Honolulu', wiki: 'Honolulu', country: 'US', sea: 'north-pacific', region: 'oceania', tier: 3,
    historicalNames: ['Honolulu', 'Kou'],
    goods: ['sandalwood', 'salt', 'coconuts', 'barkcloth', 'dried-fish'],
    notes: 'Oahu harbour unknown to Europeans until Cook’s 1778 landfall; included as a Pacific waypoint, outside the 1500-1650 era.' },
  { id: 'sydney', name: 'Sydney', localName: 'Sydney', wiki: 'Sydney', country: 'AU', sea: 'tasman-sea', region: 'oceania', tier: 3,
    historicalNames: ['Port Jackson', 'Warrane'],
    goods: ['timber', 'furs', 'wool-raw', 'dried-fish'],
    notes: 'Port Jackson was settled in 1788; Dutch ships charted Australia’s west and north coasts from 1606, not this shore.' },

  // ---------- islands (added 2026-08-24) ----------
  // Real places with real coordinates, resolved through Wikidata like every other
  // port here. They are tier 3, so four offers each under the owner's 4-9 rule, and
  // every good they name exists in the 243-good catalogue - checked, not assumed.
  { id: 'matsumae', name: 'Matsumae', localName: '松前', wiki: 'Matsumae, Hokkaido', country: 'JP', sea: 'sea-of-japan', region: 'japan', tier: 3,
    historicalNames: ['Fukuyama', 'Ezo'],
    goods: ['furs', 'dried-fish', 'timber', 'hides'],
    notes: 'The Matsumae clan’s gate to Ezo: all Ainu trade — furs, salmon, deer hides, hawks — passed through this southernmost harbour of Hokkaido.' },
];
