// Port roster — Europe.
// `wiki` is the English Wikipedia article title used to resolve the Wikidata QID,
// from which the coordinate (P625) and country (P17 -> P297 ISO 3166-1 alpha-2)
// are fetched by scripts/fetch-coords.mjs. No coordinate is typed by hand.

export default [
  // ---------- Iberia ----------
  { id: 'lisbon', name: 'Lisbon', localName: 'Lisboa', wiki: 'Lisbon', country: 'PT', sea: 'north-atlantic', region: 'iberia', tier: 1,
    historicalNames: ['Lisboa', 'Olisipo', 'al-Ushbuna'],
    goods: ['wine', 'salt', 'olive-oil', 'black-pepper', 'porcelain'],
    notes: 'Seat of the Casa da Índia; terminus of the Portuguese Carreira da Índia from 1501.' },
  { id: 'porto', name: 'Porto', localName: 'Porto', wiki: 'Porto', country: 'PT', sea: 'north-atlantic', region: 'iberia', tier: 2,
    historicalNames: ['Oporto', 'Portus Cale'],
    goods: ['wine', 'olive-oil', 'dried-fish', 'timber'],
    notes: 'Douro river port whose shipyards at Vila Nova de Gaia built vessels for the India voyages.' },
  { id: 'lagos-pt', name: 'Lagos', localName: 'Lagos', wiki: 'Lagos, Portugal', country: 'PT', sea: 'north-atlantic', region: 'iberia', tier: 3,
    historicalNames: ['Lacobriga'],
    goods: ['dried-fish', 'salt', 'wine', 'gold'],
    notes: 'Algarve harbour that outfitted the earliest 15th-century Portuguese voyages down the African coast.' },
  { id: 'setubal', name: 'Setubal', localName: 'Setúbal', wiki: 'Setúbal', country: 'PT', sea: 'north-atlantic', region: 'iberia', tier: 3,
    historicalNames: ['Cetobriga'],
    goods: ['salt', 'wine', 'dried-fish', 'olive-oil'],
    notes: 'Sado estuary salt pans supplied the salt that preserved northern European herring and cod catches.' },
  { id: 'seville', name: 'Seville', localName: 'Sevilla', wiki: 'Seville', country: 'ES', sea: 'north-atlantic', region: 'iberia', tier: 1,
    historicalNames: ['Sevilla', 'Hispalis', 'Ishbiliya'],
    goods: ['silver', 'olive-oil', 'wine', 'cochineal', 'wheat'],
    notes: 'Guadalquivir river port holding the Crown monopoly on the Indies trade through the Casa de Contratacion, 1503-1717.' },
  { id: 'cadiz', name: 'Cadiz', localName: 'Cádiz', wiki: 'Cádiz', country: 'ES', sea: 'north-atlantic', region: 'iberia', tier: 1,
    historicalNames: ['Gades', 'Qadis'],
    goods: ['silver', 'wine', 'salt', 'olive-oil'],
    notes: 'Atlantic outport of Seville and assembly point for the treasure fleets; raided by Drake in 1587.' },
  { id: 'sanlucar', name: 'Sanlucar de Barrameda', localName: 'Sanlúcar de Barrameda', wiki: 'Sanlúcar de Barrameda', country: 'ES', sea: 'north-atlantic', region: 'iberia', tier: 3,
    historicalNames: ['Sanlúcar'],
    goods: ['wine', 'salt', 'dried-fish'],
    notes: 'Mouth of the Guadalquivir; Magellan sailed from here in 1519 and Elcano returned to it in 1522.' },
  { id: 'malaga', name: 'Malaga', localName: 'Málaga', wiki: 'Málaga', country: 'ES', sea: 'mediterranean-sea', region: 'iberia', tier: 2,
    historicalNames: ['Malaqa', 'Malaca'],
    goods: ['wine', 'dried-fruit', 'olive-oil'],
    notes: 'Chief Mediterranean outlet of Andalusia, exporting sweet wine and dried fruit across Europe.' },
  { id: 'barcelona', name: 'Barcelona', localName: 'Barcelona', wiki: 'Barcelona', country: 'ES', sea: 'mediterranean-sea', region: 'iberia', tier: 1,
    historicalNames: ['Barcino'],
    goods: ['wool-cloth', 'coral', 'wine', 'iron'],
    notes: 'Catalan maritime capital whose medieval Consolat de Mar code shaped Mediterranean commercial law.' },
  { id: 'valencia', name: 'Valencia', localName: 'València', wiki: 'Valencia', country: 'ES', sea: 'mediterranean-sea', region: 'iberia', tier: 2,
    historicalNames: ['Balansiya', 'Valentia'],
    goods: ['silk-raw', 'dried-fruit', 'rice', 'porcelain'],
    notes: 'Silk-weaving city; its Llotja de la Seda commodity exchange was completed in 1548.' },
  { id: 'bilbao', name: 'Bilbao', localName: 'Bilbo', wiki: 'Bilbao', country: 'ES', sea: 'bay-of-biscay', region: 'iberia', tier: 2,
    historicalNames: ['Bilbo'],
    goods: ['iron', 'wool-raw', 'timber'],
    notes: 'Outlet for Biscayan iron and Castilian wool; its Consulado governed trade with Flanders and England.' },
  { id: 'a-coruna', name: 'A Coruna', localName: 'A Coruña', wiki: 'A Coruña', country: 'ES', sea: 'north-atlantic', region: 'iberia', tier: 3,
    historicalNames: ['La Coruña', 'Brigantium'],
    goods: ['dried-fish', 'wine', 'timber'],
    notes: 'Galician harbour from which the Spanish Armada sailed in 1588.' },
  { id: 'palma', name: 'Palma de Mallorca', localName: 'Palma', wiki: 'Palma de Mallorca', country: 'ES', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 3,
    historicalNames: ['Ciutat de Mallorca', 'Palma'],
    goods: ['olive-oil', 'wine', 'salt', 'wool-cloth'],
    notes: 'Balearic base of the medieval Majorcan chart-making school that supplied portolan charts to Atlantic pilots.' },
  { id: 'gibraltar', name: 'Gibraltar', localName: 'Gibraltar', wiki: 'Gibraltar', country: 'GI', sea: 'mediterranean-sea', region: 'iberia', tier: 3,
    historicalNames: ['Jabal Tariq', 'Calpe'],
    goods: ['dried-fish', 'wine'],
    notes: 'Fortified rock commanding the strait between the Atlantic and the Mediterranean; Spanish-held until 1704.' },
  { id: 'ceuta', name: 'Ceuta', localName: 'Ceuta', wiki: 'Ceuta', country: 'ES', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Sabta', 'Septem'],
    goods: ['gold', 'wheat', 'wool-cloth'],
    notes: 'Taken by Portugal in 1415, the first European foothold in North Africa; passed to Spain in 1668.' },

  // ---------- Atlantic isles ----------
  { id: 'funchal', name: 'Funchal', localName: 'Funchal', wiki: 'Funchal', country: 'PT', sea: 'north-atlantic', region: 'atlantic-isles', tier: 2,
    historicalNames: ['Funchal'],
    goods: ['sugar', 'wine', 'timber'],
    notes: 'Madeiran capital settled from 1424; Europe’s first plantation sugar economy before Brazil eclipsed it.' },
  { id: 'ponta-delgada', name: 'Ponta Delgada', localName: 'Ponta Delgada', wiki: 'Ponta Delgada', country: 'PT', sea: 'north-atlantic', region: 'atlantic-isles', tier: 2,
    historicalNames: ['Ponta Delgada'],
    goods: ['indigo', 'wheat', 'wine'],
    notes: 'Azorean port where returning India and Indies fleets took on water and awaited naval escort.' },
  { id: 'las-palmas', name: 'Las Palmas', localName: 'Las Palmas de Gran Canaria', wiki: 'Las Palmas', country: 'ES', sea: 'north-atlantic', region: 'atlantic-isles', tier: 2,
    historicalNames: ['Las Palmas'],
    goods: ['sugar', 'wine', 'indigo'],
    notes: 'Founded 1478; standard first watering stop for Spanish fleets bound for the Americas.' },
  { id: 'santa-cruz-tenerife', name: 'Santa Cruz de Tenerife', localName: 'Santa Cruz de Tenerife', wiki: 'Santa Cruz de Tenerife', country: 'ES', sea: 'north-atlantic', region: 'atlantic-isles', tier: 3,
    historicalNames: ['Santa Cruz de Santiago'],
    goods: ['wine', 'sugar', 'indigo'],
    notes: 'Canary roadstead exporting the malmsey wine English writers called "Canary sack".' },
  { id: 'cidade-velha', name: 'Cidade Velha', localName: 'Cidade Velha', wiki: 'Cidade Velha', country: 'CV', sea: 'north-atlantic', region: 'atlantic-isles', tier: 3,
    historicalNames: ['Ribeira Grande'],
    goods: ['salt', 'cotton-cloth', 'hides'],
    notes: 'Founded 1462 on Santiago, the first European city in the tropics and Portugal’s Cape Verde entrepot.' },

  // ---------- British Isles ----------
  { id: 'london', name: 'London', localName: 'London', wiki: 'London', country: 'GB', sea: 'north-sea', region: 'british-isles', tier: 1,
    historicalNames: ['Londinium', 'Lundenwic'],
    goods: ['wool-cloth', 'tin', 'iron', 'black-pepper'],
    notes: 'Thames river port; the Royal Exchange opened 1571 and the English East India Company was chartered here in 1600.' },
  { id: 'bristol', name: 'Bristol', localName: 'Bristol', wiki: 'Bristol', country: 'GB', sea: 'north-atlantic', region: 'british-isles', tier: 2,
    historicalNames: ['Brycgstow'],
    goods: ['wool-cloth', 'dried-fish', 'wine', 'iron'],
    notes: 'Avon river port; John Cabot sailed from here in 1497 and its ships worked the Newfoundland fishery.' },
  { id: 'plymouth', name: 'Plymouth', localName: 'Plymouth', wiki: 'Plymouth', country: 'GB', sea: 'english-channel', region: 'british-isles', tier: 2,
    historicalNames: ['Sutton'],
    goods: ['tin', 'dried-fish', 'wool-cloth'],
    notes: 'Devon naval harbour; Drake’s circumnavigation began and ended here (1577-1580).' },
  { id: 'portsmouth', name: 'Portsmouth', localName: 'Portsmouth', wiki: 'Portsmouth', country: 'GB', sea: 'english-channel', region: 'british-isles', tier: 2,
    historicalNames: ['Portsmouth'],
    goods: ['naval-timber', 'hemp', 'iron'],
    notes: 'Site of the first known dry dock in England, built for Henry VII in 1495.' },
  { id: 'southampton', name: 'Southampton', localName: 'Southampton', wiki: 'Southampton', country: 'GB', sea: 'english-channel', region: 'british-isles', tier: 3,
    historicalNames: ['Hamwic', 'Southampton'],
    goods: ['wool-cloth', 'wine', 'alum'],
    notes: 'Terminal of the Venetian and Genoese galley voyages to England in the 15th and early 16th centuries.' },
  { id: 'falmouth', name: 'Falmouth', localName: 'Falmouth', wiki: 'Falmouth, Cornwall', country: 'GB', sea: 'english-channel', region: 'british-isles', tier: 3,
    historicalNames: ['Smithwick', 'Penny-come-quick'],
    goods: ['tin', 'dried-fish', 'wool-cloth'],
    notes: 'Deep natural anchorage on the Carrick Roads, one of the first landfalls for ships from the Atlantic.' },
  { id: 'kingston-upon-hull', name: 'Kingston upon Hull', localName: 'Kingston upon Hull', wiki: 'Kingston upon Hull', country: 'GB', sea: 'north-sea', region: 'british-isles', tier: 3,
    historicalNames: ['Hull', 'Wyke upon Hull'],
    goods: ['wool-cloth', 'timber', 'tar', 'herring'],
    notes: 'Humber port handling English trade with the Baltic and, from the 1610s, Arctic whaling voyages.' },
  { id: 'newcastle', name: 'Newcastle upon Tyne', localName: 'Newcastle upon Tyne', wiki: 'Newcastle upon Tyne', country: 'GB', sea: 'north-sea', region: 'british-isles', tier: 3,
    historicalNames: ['Novum Castellum', 'Pons Aelius'],
    goods: ['iron', 'salt'],
    notes: 'The Tyne coal trade to London was the largest bulk shipping route in 17th-century Europe.' },
  { id: 'leith', name: 'Leith', localName: 'Leith', wiki: 'Leith', country: 'GB', sea: 'north-sea', region: 'british-isles', tier: 3,
    historicalNames: ['Inverleith'],
    goods: ['wool-raw', 'salt', 'herring', 'timber'],
    notes: 'Port of Edinburgh and the hub of Scotland’s Baltic and Low Countries trade.' },
  { id: 'aberdeen', name: 'Aberdeen', localName: 'Aberdeen', wiki: 'Aberdeen', country: 'GB', sea: 'north-sea', region: 'british-isles', tier: 3,
    historicalNames: ['Aberdon'],
    goods: ['dried-fish', 'wool-raw', 'hides'],
    notes: 'Dee and Don estuary burgh exporting cured salmon and plaiding to the Baltic.' },
  { id: 'dublin', name: 'Dublin', localName: 'Baile Átha Cliath', wiki: 'Dublin', country: 'IE', sea: 'irish-sea', region: 'british-isles', tier: 2,
    historicalNames: ['Dyflin', 'Baile Átha Cliath'],
    goods: ['hides', 'wool-raw', 'salted-beef', 'timber'],
    notes: 'Viking-founded Liffey port and seat of English administration in Ireland.' },
  { id: 'cork', name: 'Cork', localName: 'Corcaigh', wiki: 'Cork (city)', country: 'IE', sea: 'north-atlantic', region: 'british-isles', tier: 3,
    historicalNames: ['Corcach Mór Mumhan'],
    goods: ['salted-beef', 'cheese', 'hides', 'wool-raw'],
    notes: 'Lee estuary harbour that provisioned Atlantic shipping with salt beef and butter.' },
  { id: 'galway', name: 'Galway', localName: 'Gaillimh', wiki: 'Galway', country: 'IE', sea: 'north-atlantic', region: 'british-isles', tier: 3,
    historicalNames: ['Gaillimh'],
    goods: ['wine', 'hides', 'dried-fish'],
    notes: 'Western Irish town whose merchant tribes traded directly with Iberia for wine and salt.' },

  // ---------- France & Low Countries ----------
  { id: 'bordeaux', name: 'Bordeaux', localName: 'Bordeaux', wiki: 'Bordeaux', country: 'FR', sea: 'bay-of-biscay', region: 'france-low-countries', tier: 1,
    historicalNames: ['Burdigala', 'Bordèu'],
    goods: ['wine', 'indigo', 'salt'],
    notes: 'Garonne river port and the historic source of the claret shipped to England in bulk.' },
  { id: 'nantes', name: 'Nantes', localName: 'Nantes', wiki: 'Nantes', country: 'FR', sea: 'bay-of-biscay', region: 'france-low-countries', tier: 2,
    historicalNames: ['Namnetes', 'Naoned'],
    goods: ['salt', 'wine', 'linen', 'sugar'],
    notes: 'Loire estuary port and the outlet for Bay of Bourgneuf salt and Breton linen.' },
  { id: 'la-rochelle', name: 'La Rochelle', localName: 'La Rochelle', wiki: 'La Rochelle', country: 'FR', sea: 'bay-of-biscay', region: 'france-low-countries', tier: 2,
    historicalNames: ['La Rochelle'],
    goods: ['salt', 'wine', 'furs', 'dried-fish'],
    notes: 'Huguenot merchant stronghold and the main French base for the Canadian fur trade until its 1628 siege.' },
  { id: 'saint-malo', name: 'Saint-Malo', localName: 'Saint-Malo', wiki: 'Saint-Malo', country: 'FR', sea: 'english-channel', region: 'france-low-countries', tier: 2,
    historicalNames: ['Saint-Malo'],
    goods: ['dried-fish', 'linen', 'furs'],
    notes: 'Corsair port; Jacques Cartier sailed from here to the St Lawrence in 1534.' },
  { id: 'le-havre', name: 'Le Havre', localName: 'Le Havre', wiki: 'Le Havre', country: 'FR', sea: 'english-channel', region: 'france-low-countries', tier: 3,
    historicalNames: ['Le Havre-de-Grâce', 'Franciscopolis'],
    goods: ['wine', 'wool-cloth', 'salt'],
    notes: 'Founded by Francis I in 1517 as a purpose-built royal harbour at the Seine mouth.' },
  { id: 'dieppe', name: 'Dieppe', localName: 'Dieppe', wiki: 'Dieppe', country: 'FR', sea: 'english-channel', region: 'france-low-countries', tier: 3,
    historicalNames: ['Dieppe'],
    goods: ['ivory', 'brazilwood', 'dried-fish', 'linen'],
    notes: 'Norman port whose Dieppe school produced lavish world maps in the 1540s-1560s.' },
  { id: 'brest', name: 'Brest', localName: 'Brest', wiki: 'Brest, France', country: 'FR', sea: 'north-atlantic', region: 'france-low-countries', tier: 3,
    historicalNames: ['Brest'],
    goods: ['naval-timber', 'hemp', 'dried-fish'],
    notes: 'Sheltered Breton roadstead at the western tip of France, later the Atlantic naval arsenal.' },
  { id: 'marseille', name: 'Marseille', localName: 'Marseille', wiki: 'Marseille', country: 'FR', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 1,
    historicalNames: ['Massalia', 'Marselha'],
    goods: ['olive-oil', 'coral', 'wool-cloth', 'wheat', 'coffee'],
    notes: 'France’s Mediterranean gateway and the base of its Levant trade under the Ottoman capitulations of 1536.' },
  { id: 'toulon', name: 'Toulon', localName: 'Toulon', wiki: 'Toulon', country: 'FR', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 3,
    historicalNames: ['Telo Martius'],
    goods: ['naval-timber', 'olive-oil', 'wine'],
    notes: 'French royal galley base on the Provencal coast from the early 16th century.' },
  { id: 'calais', name: 'Calais', localName: 'Calais', wiki: 'Calais', country: 'FR', sea: 'english-channel', region: 'france-low-countries', tier: 3,
    historicalNames: ['Calais', 'Kales'],
    goods: ['wool-raw', 'wool-cloth', 'herring'],
    notes: 'English-held wool staple town from 1347 until its recapture by France in 1558.' },
  { id: 'antwerp', name: 'Antwerp', localName: 'Antwerpen', wiki: 'Antwerp', country: 'BE', sea: 'north-sea', region: 'france-low-countries', tier: 1,
    historicalNames: ['Antwerpen', 'Anvers'],
    goods: ['wool-cloth', 'black-pepper', 'copper', 'diamonds', 'sugar'],
    notes: 'Scheldt river port and Europe’s dominant commodity market until the 1585 Spanish siege and blockade.' },
  { id: 'bruges', name: 'Bruges', localName: 'Brugge', wiki: 'Bruges', country: 'BE', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Brugge'],
    goods: ['wool-cloth', 'linen', 'alum', 'wine'],
    notes: 'Hanseatic kontor city whose Zwin channel silted up, shifting its trade to Antwerp by 1500.' },
  { id: 'ostend', name: 'Ostend', localName: 'Oostende', wiki: 'Ostend', country: 'BE', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Oostende'],
    goods: ['herring', 'wool-cloth', 'salt'],
    notes: 'Flemish fishing and privateering harbour, besieged for three years from 1601 to 1604.' },
  { id: 'amsterdam', name: 'Amsterdam', localName: 'Amsterdam', wiki: 'Amsterdam', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 1,
    historicalNames: ['Amstelredamme'],
    goods: ['black-pepper', 'cloves', 'nutmeg', 'herring', 'wheat', 'timber'],
    notes: 'Seat of the VOC chamber and the 1602 stock exchange; the Wisselbank followed in 1609.' },
  { id: 'rotterdam', name: 'Rotterdam', localName: 'Rotterdam', wiki: 'Rotterdam', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 2,
    historicalNames: ['Rotterdam'],
    goods: ['herring', 'wheat', 'wine', 'timber'],
    notes: 'Maas river port and one of the six VOC chambers established in 1602.' },
  { id: 'middelburg', name: 'Middelburg', localName: 'Middelburg', wiki: 'Middelburg, Zeeland', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Middelburg in Zeeland'],
    goods: ['wine', 'sugar', 'cloves', 'salt'],
    notes: 'Zeeland capital, seat of the second-largest VOC chamber and a hub of the West India Company.' },
  { id: 'vlissingen', name: 'Vlissingen', localName: 'Vlissingen', wiki: 'Vlissingen', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Flushing'],
    goods: ['salt', 'sugar', 'wine'],
    notes: 'Scheldt-mouth harbour held as an English cautionary town from 1585 to 1616.' },
  { id: 'hoorn', name: 'Hoorn', localName: 'Hoorn', wiki: 'Hoorn', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Hoorn'],
    goods: ['cheese', 'herring', 'timber', 'nutmeg'],
    notes: 'Zuiderzee VOC chamber town; Cape Horn is named after it by Schouten and Le Maire in 1616.' },
  { id: 'enkhuizen', name: 'Enkhuizen', localName: 'Enkhuizen', wiki: 'Enkhuizen', country: 'NL', sea: 'north-sea', region: 'france-low-countries', tier: 3,
    historicalNames: ['Enkhuizen'],
    goods: ['herring', 'salt', 'timber'],
    notes: 'Herring-fleet town and VOC chamber; home of the navigator Jan Huyghen van Linschoten.' },

  // ---------- Baltic & the Hanse ----------
  { id: 'copenhagen', name: 'Copenhagen', localName: 'København', wiki: 'Copenhagen', country: 'DK', sea: 'baltic-sea', region: 'baltic', tier: 1,
    historicalNames: ['Køpmannæhafn', 'Hafnia'],
    goods: ['herring', 'wheat', 'salted-beef', 'amber'],
    notes: 'Danish capital commanding the Sound, where the Oresund toll was levied on all Baltic traffic from 1429.' },
  { id: 'lubeck', name: 'Lubeck', localName: 'Lübeck', wiki: 'Lübeck', country: 'DE', sea: 'baltic-sea', region: 'baltic', tier: 1,
    historicalNames: ['Lübeck'],
    goods: ['salt', 'herring', 'wax', 'furs', 'wheat'],
    notes: 'Leading city of the Hanseatic League and the seat of its diets on the Trave river.' },
  { id: 'hamburg', name: 'Hamburg', localName: 'Hamburg', wiki: 'Hamburg', country: 'DE', sea: 'north-sea', region: 'baltic', tier: 1,
    historicalNames: ['Hammaburg'],
    goods: ['wine', 'wheat', 'wool-cloth', 'sugar', 'copper'],
    notes: 'Elbe river port that absorbed much Antwerp trade after 1585; its Bank opened in 1619.' },
  { id: 'bremen', name: 'Bremen', localName: 'Bremen', wiki: 'Bremen', country: 'DE', sea: 'north-sea', region: 'baltic', tier: 3,
    historicalNames: ['Bremen'],
    goods: ['wool-cloth', 'wheat', 'wine', 'timber'],
    notes: 'Weser river Hansestadt trading with England and the Low Countries.' },
  { id: 'rostock', name: 'Rostock', localName: 'Rostock', wiki: 'Rostock', country: 'DE', sea: 'baltic-sea', region: 'baltic', tier: 3,
    historicalNames: ['Rostock'],
    goods: ['wheat', 'wine', 'herring', 'timber'],
    notes: 'Wendish Hanseatic town on the Warnow exporting Mecklenburg grain.' },
  { id: 'gdansk', name: 'Gdansk', localName: 'Gdańsk', wiki: 'Gdańsk', country: 'PL', sea: 'baltic-sea', region: 'baltic', tier: 1,
    historicalNames: ['Danzig', 'Gyddanyzc'],
    goods: ['wheat', 'timber', 'tar', 'alum', 'amber'],
    notes: 'Vistula outlet through which Polish rye and naval stores fed the Dutch grain trade.' },
  { id: 'kaliningrad', name: 'Kaliningrad', localName: 'Калининград', wiki: 'Kaliningrad', country: 'RU', sea: 'baltic-sea', region: 'baltic', tier: 3,
    historicalNames: ['Königsberg', 'Twangste'],
    goods: ['amber', 'wheat', 'timber', 'flax'],
    notes: 'Founded 1255 as Konigsberg; ducal Prussian capital holding the Baltic amber monopoly.' },
  { id: 'klaipeda', name: 'Klaipeda', localName: 'Klaipėda', wiki: 'Klaipėda', country: 'LT', sea: 'baltic-sea', region: 'baltic', tier: 3,
    historicalNames: ['Memel'],
    goods: ['timber', 'flax', 'hemp', 'tar'],
    notes: 'Memel, the northernmost Prussian harbour, shipping Lithuanian timber and hemp.' },
  { id: 'riga', name: 'Riga', localName: 'Rīga', wiki: 'Riga', country: 'LV', sea: 'baltic-sea', region: 'baltic', tier: 2,
    historicalNames: ['Riga'],
    goods: ['flax', 'hemp', 'timber', 'tar', 'furs'],
    notes: 'Daugava river Hansestadt and the principal source of masts and cordage fibre for western navies.' },
  { id: 'tallinn', name: 'Tallinn', localName: 'Tallinn', wiki: 'Tallinn', country: 'EE', sea: 'baltic-sea', region: 'baltic', tier: 2,
    historicalNames: ['Reval', 'Lyndanisse'],
    goods: ['furs', 'wax', 'flax', 'wheat'],
    notes: 'Reval, the Hanseatic outlet for Russian goods coming west from Novgorod.' },
  { id: 'stockholm', name: 'Stockholm', localName: 'Stockholm', wiki: 'Stockholm', country: 'SE', sea: 'baltic-sea', region: 'baltic', tier: 2,
    historicalNames: ['Stockholm'],
    goods: ['copper', 'iron', 'tar', 'timber'],
    notes: 'Swedish capital exporting Falun copper, which financed the crown through the Thirty Years War.' },
  { id: 'gothenburg', name: 'Gothenburg', localName: 'Göteborg', wiki: 'Gothenburg', country: 'SE', sea: 'north-sea', region: 'baltic', tier: 3,
    historicalNames: ['Göteborg'],
    goods: ['iron', 'timber', 'herring'],
    notes: 'Chartered 1621 to give Sweden a North Sea harbour outside the Danish Sound toll.' },
  { id: 'visby', name: 'Visby', localName: 'Visby', wiki: 'Visby', country: 'SE', sea: 'baltic-sea', region: 'baltic', tier: 3,
    historicalNames: ['Visby'],
    goods: ['wax', 'furs', 'tar', 'salt'],
    notes: 'Gotland town whose sea law circulated across the Baltic; sacked by Denmark in 1361 and in decline thereafter.' },
  { id: 'turku', name: 'Turku', localName: 'Turku', wiki: 'Turku', country: 'FI', sea: 'baltic-sea', region: 'baltic', tier: 3,
    historicalNames: ['Åbo'],
    goods: ['tar', 'timber', 'furs', 'dried-fish'],
    notes: 'Abo, the administrative and trading centre of Swedish Finland at the Aura river mouth.' },

  // ---------- Scandinavia & the Arctic ----------
  { id: 'bergen', name: 'Bergen', localName: 'Bergen', wiki: 'Bergen', country: 'NO', sea: 'norwegian-sea', region: 'scandinavia-arctic', tier: 2,
    historicalNames: ['Bjørgvin'],
    goods: ['dried-fish', 'whale-oil', 'timber', 'furs'],
    notes: 'Site of the Hanseatic Bryggen kontor, which controlled the northern stockfish trade until 1754.' },
  { id: 'oslo', name: 'Oslo', localName: 'Oslo', wiki: 'Oslo', country: 'NO', sea: 'north-sea', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Christiania', 'Ánslo'],
    goods: ['timber', 'iron', 'dried-fish'],
    notes: 'Rebuilt as Christiania after the 1624 fire; outlet for eastern Norwegian sawn timber.' },
  { id: 'trondheim', name: 'Trondheim', localName: 'Trondheim', wiki: 'Trondheim', country: 'NO', sea: 'norwegian-sea', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Nidaros', 'Trondhjem'],
    goods: ['dried-fish', 'copper', 'timber', 'whale-oil'],
    notes: 'Nidaros, medieval seat of the Norwegian archbishopric and outlet for Roros copper from 1644.' },
  { id: 'vardo', name: 'Vardo', localName: 'Vardø', wiki: 'Vardø (town)', country: 'NO', sea: 'barents-sea', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Vardøhus'],
    goods: ['dried-fish', 'whale-oil', 'furs'],
    notes: 'Norway’s northeasternmost fortress town, meeting point of Pomor traders and Arctic passage-seekers.' },
  { id: 'arkhangelsk', name: 'Arkhangelsk', localName: 'Архангельск', wiki: 'Arkhangelsk', country: 'RU', sea: 'white-sea', region: 'scandinavia-arctic', tier: 2,
    historicalNames: ['Archangel', 'Novo-Kholmogory'],
    goods: ['furs', 'wax', 'hemp', 'timber'],
    notes: 'Founded 1584 on the Dvina; Russia’s only sea outlet to the west, opened by Chancellor’s 1553 voyage.' },
  { id: 'reykjavik', name: 'Reykjavik', localName: 'Reykjavík', wiki: 'Reykjavík', country: 'IS', sea: 'north-atlantic', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Reykjavík'],
    goods: ['dried-fish', 'wool-cloth', 'sulphur', 'whale-oil'],
    notes: 'Icelandic farm settlement under the Danish trade monopoly of 1602; chartered as a town in 1786.' },
  { id: 'hafnarfjordur', name: 'Hafnarfjordur', localName: 'Hafnarfjörður', wiki: 'Hafnarfjörður', country: 'IS', sea: 'north-atlantic', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Hafnarfjörður'],
    goods: ['dried-fish', 'sulphur', 'wool-cloth'],
    notes: 'Iceland’s chief harbour in the 15th and 16th centuries, worked by English and then Hanseatic merchants.' },
  { id: 'torshavn', name: 'Torshavn', localName: 'Tórshavn', wiki: 'Tórshavn', country: 'FO', sea: 'norwegian-sea', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Tórshavn'],
    goods: ['dried-fish', 'wool-cloth', 'whale-oil'],
    notes: 'Faroese Tinganes assembly site and the islands’ single licensed trading harbour under Danish rule.' },
  { id: 'nuuk', name: 'Nuuk', localName: 'Nuuk', wiki: 'Nuuk', country: 'GL', sea: 'north-atlantic', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Godthåb'],
    goods: ['whale-oil', 'ivory', 'furs'],
    notes: 'Near the Norse Western Settlement abandoned in the 14th century; refounded as Godthaab in 1728.' },
  { id: 'qaqortoq', name: 'Qaqortoq', localName: 'Qaqortoq', wiki: 'Qaqortoq', country: 'GL', sea: 'north-atlantic', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Julianehåb'],
    goods: ['ivory', 'whale-oil', 'furs'],
    notes: 'Sits in the fjord district of the Norse Eastern Settlement, whose last record dates from 1408.' },
  { id: 'longyearbyen', name: 'Longyearbyen', localName: 'Longyearbyen', wiki: 'Longyearbyen', country: 'NO', sea: 'arctic-ocean', region: 'scandinavia-arctic', tier: 3,
    historicalNames: ['Spitsbergen'],
    goods: ['whale-oil', 'furs'],
    notes: 'On Spitsbergen, sighted by Barentsz in 1596 and the base of Dutch and English whaling from 1611; the town itself dates from 1906.' },

  // ---------- Western Mediterranean & Italy ----------
  { id: 'genoa', name: 'Genoa', localName: 'Genova', wiki: 'Genoa', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 1,
    historicalNames: ['Genova', 'Zena', 'Ianua'],
    goods: ['silk-cloth', 'alum', 'coral', 'linen', 'silver'],
    notes: 'Republic whose Casa di San Giorgio financiers underwrote much of Habsburg Spain’s war debt.' },
  { id: 'venice', name: 'Venice', localName: 'Venezia', wiki: 'Venice', country: 'IT', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 1,
    historicalNames: ['Venezia', 'Venexia'],
    goods: ['glassware', 'black-pepper', 'silk-cloth', 'salt', 'olive-oil'],
    notes: 'Lagoon republic whose state Arsenal could fit out a galley in a day at its 16th-century peak.' },
  { id: 'naples', name: 'Naples', localName: 'Napoli', wiki: 'Naples', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 2,
    historicalNames: ['Napoli', 'Neapolis'],
    goods: ['wheat', 'wine', 'olive-oil', 'silk-raw'],
    notes: 'Capital of the Spanish viceroyalty and one of Europe’s largest cities in 1600.' },
  { id: 'livorno', name: 'Livorno', localName: 'Livorno', wiki: 'Livorno', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 2,
    historicalNames: ['Leghorn', 'Liburna'],
    goods: ['wool-cloth', 'coral', 'wheat', 'alum'],
    notes: 'Made a free port by the Medici Livornine laws of 1591-1593, drawing foreign merchant colonies.' },
  { id: 'amalfi', name: 'Amalfi', localName: 'Amalfi', wiki: 'Amalfi', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 3,
    historicalNames: ['Amalfi'],
    goods: ['linen', 'wine', 'dried-fruit', 'coral'],
    notes: 'Former maritime republic remembered for the Tabula Amalphitana, a medieval code of sea law.' },
  { id: 'palermo', name: 'Palermo', localName: 'Palermo', wiki: 'Palermo', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 2,
    historicalNames: ['Balarm', 'Panormus'],
    goods: ['wheat', 'sugar', 'silk-raw', 'salt'],
    notes: 'Sicilian capital and the shipping point for the island grain that fed much of the Mediterranean.' },
  { id: 'messina', name: 'Messina', localName: 'Messina', wiki: 'Messina', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 3,
    historicalNames: ['Messana', 'Zancle'],
    goods: ['silk-raw', 'dried-fruit', 'wine', 'wheat'],
    notes: 'Guards the strait between Sicily and Calabria; the Holy League fleet sailed from here to Lepanto in 1571.' },
  { id: 'cagliari', name: 'Cagliari', localName: 'Cagliari', wiki: 'Cagliari', country: 'IT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 3,
    historicalNames: ['Casteddu', 'Karalis'],
    goods: ['salt', 'wheat', 'coral', 'cheese'],
    notes: 'Sardinian capital under the Crown of Aragon, exporting salt and coral from its lagoons and reefs.' },
  { id: 'valletta', name: 'Valletta', localName: 'Valletta', wiki: 'Valletta', country: 'MT', sea: 'mediterranean-sea', region: 'western-mediterranean', tier: 2,
    historicalNames: ['Valletta', 'Il-Belt'],
    goods: ['cotton-cloth', 'wheat', 'salt'],
    notes: 'Founded 1566 by the Knights of St John after the Great Siege; corsairing base against Ottoman shipping.' },
  { id: 'ancona', name: 'Ancona', localName: 'Ancona', wiki: 'Ancona', country: 'IT', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Ancona', 'Ankon'],
    goods: ['wool-cloth', 'wax', 'hides', 'wheat'],
    notes: 'Papal free port on the Adriatic, linked by overland routes to Ragusa and the Ottoman Balkans.' },
  { id: 'bari', name: 'Bari', localName: 'Bari', wiki: 'Bari', country: 'IT', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Barium'],
    goods: ['olive-oil', 'wheat', 'dried-fruit', 'wine'],
    notes: 'Apulian harbour exporting the olive oil that lit lamps and fulled cloth across northern Europe.' },
  { id: 'trieste', name: 'Trieste', localName: 'Trieste', wiki: 'Trieste', country: 'IT', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Tergeste', 'Trst'],
    goods: ['salt', 'iron', 'wine', 'timber'],
    notes: 'Habsburg harbour at the head of the Adriatic, a persistent commercial rival to Venice.' },
  { id: 'dubrovnik', name: 'Dubrovnik', localName: 'Dubrovnik', wiki: 'Dubrovnik', country: 'HR', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 2,
    historicalNames: ['Ragusa'],
    goods: ['wool-cloth', 'silver', 'wax', 'salt', 'hides'],
    notes: 'Ragusa, a tribute-paying republic under Ottoman protection whose neutral flag carried Balkan trade.' },
  { id: 'split', name: 'Split', localName: 'Split', wiki: 'Split, Croatia', country: 'HR', sea: 'adriatic-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Spalato', 'Aspalathos'],
    goods: ['wool-cloth', 'wax', 'hides', 'wine'],
    notes: 'Venetian-held Dalmatian town; its scala from 1592 funnelled Ottoman caravan goods to Venice.' },
  { id: 'corfu', name: 'Corfu', localName: 'Κέρκυρα', wiki: 'Corfu (city)', country: 'GR', sea: 'ionian-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Kerkyra', 'Corcyra'],
    goods: ['olive-oil', 'wine', 'dried-fruit', 'salt'],
    notes: 'Venetian fortress guarding the Adriatic entrance; withstood the Ottoman siege of 1537.' },
  { id: 'patras', name: 'Patras', localName: 'Πάτρα', wiki: 'Patras', country: 'GR', sea: 'ionian-sea', region: 'adriatic-ionian', tier: 3,
    historicalNames: ['Patrai', 'Balibadra'],
    goods: ['dried-fruit', 'olive-oil', 'wine', 'silk-raw'],
    notes: 'Ottoman-held Gulf of Corinth port; English ships loaded currants here for the London market.' },

  // ---------- Aegean, Anatolia & Black Sea ----------
  { id: 'istanbul', name: 'Istanbul', localName: 'İstanbul', wiki: 'Istanbul', country: 'TR', sea: 'sea-of-marmara', region: 'aegean-anatolia', tier: 1,
    historicalNames: ['Constantinople', 'Konstantiniyye', 'Byzantion'],
    goods: ['silk-cloth', 'carpets', 'wheat', 'furs', 'black-pepper'],
    notes: 'Ottoman capital from 1453, straddling the Bosphorus between the Mediterranean and Black Sea trades.' },
  { id: 'izmir', name: 'Izmir', localName: 'İzmir', wiki: 'İzmir', country: 'TR', sea: 'aegean-sea', region: 'aegean-anatolia', tier: 2,
    historicalNames: ['Smyrna'],
    goods: ['dried-fruit', 'cotton-raw', 'silk-raw', 'carpets'],
    notes: 'Smyrna, which grew in the 17th century into the chief Levant Company outlet for Anatolian produce.' },
  { id: 'antalya', name: 'Antalya', localName: 'Antalya', wiki: 'Antalya', country: 'TR', sea: 'mediterranean-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['Attaleia', 'Satalia'],
    goods: ['timber', 'wheat', 'wax', 'carpets'],
    notes: 'Ottoman naval harbour on the Pamphylian coast and outlet for Taurus cedar and pine.' },
  { id: 'thessaloniki', name: 'Thessaloniki', localName: 'Θεσσαλονίκη', wiki: 'Thessaloniki', country: 'GR', sea: 'aegean-sea', region: 'aegean-anatolia', tier: 2,
    historicalNames: ['Salonica', 'Selanik'],
    goods: ['wool-cloth', 'wheat', 'tobacco', 'hides'],
    notes: 'Ottoman Balkan port whose Sephardic community, settled after 1492, made it a woollen-cloth centre.' },
  { id: 'heraklion', name: 'Heraklion', localName: 'Ηράκλειο', wiki: 'Heraklion', country: 'GR', sea: 'mediterranean-sea', region: 'aegean-anatolia', tier: 2,
    historicalNames: ['Candia', 'Chandax'],
    goods: ['wine', 'olive-oil', 'cheese', 'salt'],
    notes: 'Candia, Venice’s Cretan capital, besieged by the Ottomans from 1648 and lost in 1669.' },
  { id: 'chania', name: 'Chania', localName: 'Χανιά', wiki: 'Chania', country: 'GR', sea: 'mediterranean-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['La Canea', 'Kydonia'],
    goods: ['olive-oil', 'wine'],
    notes: 'Venetian-walled western Cretan harbour, the first to fall to the Ottoman invasion of 1645.' },
  { id: 'rhodes', name: 'Rhodes', localName: 'Ρόδος', wiki: 'Rhodes (city)', country: 'GR', sea: 'aegean-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['Rodos'],
    goods: ['wine', 'olive-oil', 'coral', 'wheat'],
    notes: 'Base of the Knights Hospitaller until Suleiman took the fortress in 1522.' },
  { id: 'trabzon', name: 'Trabzon', localName: 'Trabzon', wiki: 'Trabzon', country: 'TR', sea: 'black-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['Trebizond', 'Trapezous'],
    goods: ['silk-raw', 'copper', 'carpets', 'dried-fruit'],
    notes: 'Black Sea terminus of the Tabriz caravan road; the Byzantine successor empire here fell in 1461.' },
  { id: 'feodosia', name: 'Feodosia', localName: 'Феодосія', wiki: 'Feodosia', country: 'UA', sea: 'black-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['Caffa', 'Kefe', 'Theodosia'],
    goods: ['wheat', 'salt', 'furs', 'wax'],
    notes: 'Caffa, the Genoese Crimean colony taken by the Ottomans in 1475 and thereafter their Black Sea seat.' },
  { id: 'sinop', name: 'Sinop', localName: 'Sinop', wiki: 'Sinop, Turkey', country: 'TR', sea: 'black-sea', region: 'aegean-anatolia', tier: 3,
    historicalNames: ['Sinope'],
    goods: ['timber', 'copper', 'wheat', 'tar'],
    notes: 'Only sheltered natural harbour on the northern Anatolian coast; a major Ottoman shipbuilding yard.' },

  // ---------- Levant & Egypt ----------
  { id: 'alexandria', name: 'Alexandria', localName: 'الإسكندرية', wiki: 'Alexandria', country: 'EG', sea: 'mediterranean-sea', region: 'levant', tier: 1,
    historicalNames: ['al-Iskandariyya', 'Alexandreia'],
    goods: ['black-pepper', 'flax', 'wheat', 'sugar', 'alum'],
    notes: 'Mediterranean outlet of the Red Sea spice route until the Cape route drew the trade away after 1500.' },
  { id: 'damietta', name: 'Damietta', localName: 'دمياط', wiki: 'Damietta', country: 'EG', sea: 'mediterranean-sea', region: 'levant', tier: 3,
    historicalNames: ['Dumyat', 'Damiata'],
    goods: ['linen', 'rice', 'sugar', 'coffee'],
    notes: 'Nile-branch port long known for its fine linen and, later, for handling Yemeni coffee.' },
  { id: 'beirut', name: 'Beirut', localName: 'بيروت', wiki: 'Beirut', country: 'LB', sea: 'mediterranean-sea', region: 'levant', tier: 2,
    historicalNames: ['Bayrut', 'Berytus'],
    goods: ['silk-raw', 'cotton-raw', 'olive-oil'],
    notes: 'Outlet for Mount Lebanon raw silk, promoted by the Druze emir Fakhr al-Din II in the early 1600s.' },
  { id: 'tripoli-lb', name: 'Tripoli', localName: 'طرابلس', wiki: 'Tripoli, Lebanon', country: 'LB', sea: 'mediterranean-sea', region: 'levant', tier: 3,
    historicalNames: ['Tarabulus al-Sham', 'Tripolis'],
    goods: ['silk-raw', 'olive-oil', 'coral'],
    notes: 'Levant Company factory town and outlet for the caravan road running inland to Aleppo.' },
  { id: 'latakia', name: 'Latakia', localName: 'اللاذقية', wiki: 'Latakia', country: 'SY', sea: 'mediterranean-sea', region: 'levant', tier: 3,
    historicalNames: ['Laodicea', 'al-Ladhiqiyah'],
    goods: ['tobacco', 'silk-raw', 'cotton-raw', 'wine'],
    notes: 'Northern Syrian roadstead serving Aleppo, the great inland market of the Ottoman Levant.' },
  { id: 'acre', name: 'Acre', localName: 'עכו', wiki: 'Acre, Israel', country: 'IL', sea: 'mediterranean-sea', region: 'levant', tier: 3,
    historicalNames: ['Akka', 'Saint-Jean-d’Acre', 'Ptolemais'],
    goods: ['cotton-raw', 'wheat', 'olive-oil'],
    notes: 'Last crusader capital, lost in 1291; a modest Ottoman grain and cotton harbour thereafter.' },
  { id: 'famagusta', name: 'Famagusta', localName: 'Ammochostos', wiki: 'Famagusta', country: 'CY', sea: 'mediterranean-sea', region: 'levant', tier: 3,
    historicalNames: ['Ammochostos', 'Magusa'],
    goods: ['sugar', 'cotton-raw', 'salt', 'wine'],
    notes: 'Venetian Cyprus’s fortified harbour, which fell after an eleven-month Ottoman siege in 1571.' },

  // ---------- Maghreb ----------
  { id: 'tangier', name: 'Tangier', localName: 'طنجة', wiki: 'Tangier', country: 'MA', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Tanja', 'Tingis'],
    goods: ['hides', 'wax', 'wheat', 'wool-raw'],
    notes: 'Held by Portugal from 1471; passed to England in 1661 as part of Catherine of Braganza’s dowry.' },
  { id: 'sale', name: 'Sale', localName: 'سلا', wiki: 'Salé', country: 'MA', sea: 'north-atlantic', region: 'maghreb', tier: 3,
    historicalNames: ['Sala', 'New Salé'],
    goods: ['hides', 'wax', 'wool-raw', 'dried-fruit'],
    notes: 'Bou Regreg corsair republic of the 1620s-1660s, manned partly by Moriscos expelled from Spain.' },
  { id: 'safi', name: 'Safi', localName: 'آسفي', wiki: 'Safi, Morocco', country: 'MA', sea: 'north-atlantic', region: 'maghreb', tier: 3,
    historicalNames: ['Asfi'],
    goods: ['sugar', 'copper', 'wool-raw', 'hides'],
    notes: 'Portuguese-held 1508-1541; the Atlantic outlet for Marrakesh and its Sous sugar refineries.' },
  { id: 'agadir', name: 'Agadir', localName: 'أݣادير', wiki: 'Agadir', country: 'MA', sea: 'north-atlantic', region: 'maghreb', tier: 3,
    historicalNames: ['Santa Cruz do Cabo de Gué'],
    goods: ['sugar', 'gold', 'wax', 'dried-fruit'],
    notes: 'Portuguese fort from 1505 until the Saadians stormed it in 1541, opening the Sous to their sugar trade.' },
  { id: 'algiers', name: 'Algiers', localName: 'الجزائر', wiki: 'Algiers', country: 'DZ', sea: 'mediterranean-sea', region: 'maghreb', tier: 2,
    historicalNames: ['al-Jaza’ir', 'Icosium'],
    goods: ['wheat', 'hides', 'wax', 'coral'],
    notes: 'Ottoman regency from 1516 and the leading Barbary corsair base in the western Mediterranean.' },
  { id: 'oran', name: 'Oran', localName: 'وهران', wiki: 'Oran', country: 'DZ', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Wahran'],
    goods: ['wheat', 'wool-raw', 'hides', 'salt'],
    notes: 'Spanish presidio from 1509, holding a bridgehead on the Algerian coast for nearly two centuries.' },
  { id: 'bejaia', name: 'Bejaia', localName: 'بجاية', wiki: 'Béjaïa', country: 'DZ', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Bougie', 'Saldae'],
    goods: ['wax', 'hides', 'olive-oil', 'coral'],
    notes: 'Its beeswax exports gave French the word "bougie" for a candle; Spanish-held 1510-1555.' },
  { id: 'tunis', name: 'Tunis', localName: 'تونس', wiki: 'Tunis', country: 'TN', sea: 'mediterranean-sea', region: 'maghreb', tier: 2,
    historicalNames: ['Tunis'],
    goods: ['wool-cloth', 'olive-oil', 'coral', 'wax', 'dried-fruit'],
    notes: 'Hafsid then Ottoman capital whose harbour of La Goulette was taken by Charles V in 1535.' },
  { id: 'tripoli-ly', name: 'Tripoli', localName: 'طرابلس', wiki: 'Tripoli, Libya', country: 'LY', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Tarabulus al-Gharb', 'Oea'],
    goods: ['gold', 'ivory', 'dried-fruit', 'hides'],
    notes: 'Mediterranean terminus of the Fezzan caravan route; held by the Knights of Malta 1530-1551.' },
  { id: 'benghazi', name: 'Benghazi', localName: 'بنغازي', wiki: 'Benghazi', country: 'LY', sea: 'mediterranean-sea', region: 'maghreb', tier: 3,
    historicalNames: ['Berenice', 'Marsa ibn Ghazi'],
    goods: ['wheat', 'dried-fruit', 'wool-raw', 'salt'],
    notes: 'Cyrenaican roadstead on the Gulf of Sidra, a minor Ottoman grain and caravan outlet.' },
];
