#!/usr/bin/env node
// Validator for data/ports.json, data/seas.json, data/regions.json and data/goods.json.
// Exits non-zero on any FAIL. Run: node scripts/check-ports.mjs
//
// The country bounding boxes below were generated by scripts/build-world.mjs from
// Natural Earth 1:10m Admin 0 Countries (public domain), as [minLon, minLat, maxLon, maxLat].
// They are sovereign-territory boxes, so a few are very wide (France reaches French
// Polynesia, Norway reaches Bouvet Island); the check is a sanity net, not a coastline test.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DATA = join(dirname(fileURLToPath(import.meta.url)), '..', 'data');
const read = f => JSON.parse(readFileSync(join(DATA, f), 'utf8'));

const COUNTRY_BBOX = {
  AO: [11.6694, -18.0314, 24.0617, -4.3912],   // Angola
  AR: [-73.5727, -55.052, -53.6616, -21.7869], // Argentina
  AU: [96.8215, -54.7504, 159.1065, -9.2402],  // Australia
  BB: [-59.6542, 13.0512, -59.4269, 13.3446],  // Barbados
  BD: [88.0218, 20.7387, 92.6429, 26.6235],    // Bangladesh
  BE: [2.5218, 49.4952, 6.3745, 51.4962],      // Belgium
  BH: [50.3805, 25.5799, 50.8199, 26.2874],    // Bahrain
  BJ: [0.7599, 6.2139, 3.8374, 12.3992],       // Benin
  BM: [-64.886, 32.2481, -64.6476, 32.3887],   // Bermuda
  BR: [-74.0185, -33.7423, -28.8771, 5.2672],  // Brazil
  CA: [-141.0056, 41.6691, -52.6166, 83.1165], // Canada
  CL: [-109.4537, -55.9185, -66.4208, -17.5066], // Chile
  CN: [73.6023, 15.7754, 134.7726, 53.5694],   // China
  CO: [-81.7237, -4.2365, -66.8751, 13.5784],  // Colombia
  CU: [-84.9496, 19.8278, -74.1329, 23.2656],  // Cuba
  CV: [-25.3604, 14.8039, -22.6666, 17.1966],  // Cape Verde
  CW: [-69.1717, 12.0413, -68.7397, 12.3915],  // Curaçao
  CY: [32.2717, 34.625, 34.0991, 35.1871],     // Cyprus
  DE: [5.8525, 47.2711, 15.0221, 55.0653],     // Germany
  DK: [8.094, 54.5686, 15.1514, 57.7512],      // Denmark
  DO: [-72.0098, 17.5456, -68.3286, 19.9377],  // Dominican Republic
  DZ: [-8.6824, 18.9756, 11.9689, 37.0939],    // Algeria
  EE: [21.8324, 57.5158, 28.1865, 59.6709],    // Estonia
  EG: [24.6883, 21.9944, 36.8992, 31.6565],    // Egypt
  ER: [36.4236, 12.36, 43.1239, 18.0048],      // Eritrea
  ES: [-18.1672, 27.6422, 4.3371, 43.7934],    // Spain (incl. Canaries, Ceuta)
  FI: [20.6232, 59.8112, 31.5695, 70.0753],    // Finland
  FO: [-7.6442, 61.3941, -6.2758, 62.3989],    // Faroe Islands
  FR: [-109.2342, -21.3708, 55.8545, 51.0875], // France (incl. overseas territories)
  GB: [-13.6913, 49.9096, 1.7712, 60.8479],    // United Kingdom
  GH: [-3.2625, 4.7371, 1.188, 11.1629],       // Ghana
  GI: [-5.3584, 36.1105, -5.3388, 36.1411],    // Gibraltar
  GL: [-73.0572, 59.7926, -11.3768, 83.6341],  // Greenland
  GR: [19.6265, 34.815, 28.2398, 41.7505],     // Greece
  GU: [144.6242, 13.241, 144.9522, 13.6541],   // Guam
  HK: [113.8373, 22.1771, 114.4013, 22.5639],  // Hong Kong
  HR: [13.5015, 42.4163, 19.4078, 46.547],     // Croatia
  ID: [95.0127, -10.9226, 140.9776, 5.9101],   // Indonesia
  IE: [-10.4782, 51.4457, -5.9935, 55.3864],   // Ireland
  IN: [68.1434, 6.7456, 97.3623, 35.4954],     // India
  IQ: [38.7745, 29.0631, 48.5593, 37.3755],    // Iraq
  IR: [44.0149, 25.0594, 63.3196, 39.7715],    // Iran
  IS: [-24.5399, 63.3967, -13.5029, 66.5642],  // Iceland
  IT: [6.6027, 35.4892, 18.5174, 47.0852],     // Italy
  JM: [-78.3747, 17.7032, -76.188, 18.5251],   // Jamaica
  JP: [122.9382, 24.2121, 153.9856, 45.5204],  // Japan (incl. Okinawa)
  KE: [33.8905, -4.6775, 41.885, 5.0304],      // Kenya
  KP: [124.2113, 37.6756, 130.7, 43.0103],     // North Korea
  KR: [124.6136, 33.1976, 131.8625, 38.6243],  // South Korea (incl. Jeju)
  LB: [35.0996, 33.0556, 36.6041, 34.6875],    // Lebanon
  LK: [79.6558, 5.9237, 81.8903, 9.8296],      // Sri Lanka
  LV: [20.9686, 55.667, 28.2173, 58.0751],     // Latvia
  LY: [9.2865, 19.4961, 25.1563, 33.1812],     // Libya
  MA: [-17.0137, 21.42, -1.032, 35.9265],      // Morocco
  MM: [92.175, 9.7907, 101.1739, 28.5385],     // Myanmar
  MO: [113.5199, 22.1054, 113.5875, 22.2208],  // Macau
  MT: [14.1836, 35.8012, 14.5671, 36.0756],    // Malta
  MU: [56.5242, -20.5173, 63.4939, -10.3239],  // Mauritius (incl. outer islands)
  MV: [72.6848, -0.6886, 73.7532, 7.1072],     // Maldives
  MX: [-118.3688, 14.5463, -86.7006, 32.7128], // Mexico
  MY: [99.6452, 0.8514, 119.2781, 7.3558],     // Malaysia
  MZ: [30.2138, -26.8603, 40.848, -10.469],    // Mozambique
  NG: [2.6711, 4.2722, 14.6699, 13.8803],      // Nigeria
  NL: [-68.4174, 12.022, 7.1985, 53.5581],     // Netherlands (incl. Caribbean)
  NO: [-9.1174, -54.4625, 33.6404, 80.7701],   // Norway (incl. Svalbard, Bouvet)
  OM: [51.9786, 16.6424, 59.8446, 26.386],     // Oman
  PA: [-83.0532, 7.2057, -77.1633, 9.6293],    // Panama
  PE: [-81.3376, -18.3377, -68.6843, -0.0291], // Peru
  PH: [116.9549, 4.6557, 126.6177, 21.1224],   // Philippines
  PK: [60.8444, 23.6945, 77.049, 37.0545],     // Pakistan
  PL: [14.1239, 48.994, 24.1432, 54.8383],     // Poland
  PR: [-67.9378, 17.9229, -65.2446, 18.5228],  // Puerto Rico
  PT: [-31.2849, 30.0292, -6.2059, 42.1536],   // Portugal (incl. Azores, Madeira)
  RU: [-180, 41.1927, 180, 81.8587],           // Russia (spans the antimeridian)
  SA: [34.5728, 16.371, 55.6376, 32.1213],     // Saudi Arabia
  SD: [21.8094, 8.6816, 38.6039, 22.227],      // Sudan
  SE: [11.1082, 55.3427, 24.1634, 69.0364],    // Sweden
  SN: [-17.536, 12.3056, -11.3778, 16.6914],   // Senegal
  SO: [40.9654, -1.6963, 51.417, 11.9891],     // Somalia
  SR: [-58.0677, 1.8335, -53.9864, 6.0116],    // Suriname
  ST: [6.4617, 0.0241, 7.4627, 1.6998],        // São Tomé and Príncipe
  TH: [97.3514, 5.6299, 105.651, 20.445],      // Thailand
  TL: [124.03, -9.5012, 127.3132, -8.135],     // Timor-Leste
  TN: [7.4798, 30.2289, 11.5641, 37.3452],     // Tunisia
  TR: [25.6633, 35.8198, 44.807, 42.0988],     // Turkey
  TW: [118.2796, 21.9046, 122.0054, 25.2874],  // Taiwan
  TZ: [29.321, -11.7313, 40.4494, -0.9858],    // Tanzania
  UA: [22.1328, 44.381, 40.1595, 52.3689],     // Ukraine (unioned with NE's Ukrainian POV file, so Crimea is included)
  US: [-179.1435, 18.9061, 179.7809, 71.4125], // United States (spans the antimeridian)
  VE: [-73.3911, 0.6493, -59.8156, 15.7029],   // Venezuela
  VN: [102.1187, 8.5656, 109.4724, 23.3663],   // Vietnam
  YE: [42.5457, 12.1114, 54.5403, 18.9956],    // Yemen
  ZA: [16.47, -46.9658, 37.9778, -22.1265],    // South Africa
};

// Allowance for coastline generalisation in Natural Earth's outlines. A port sitting on a
// mole or a river bar can fall a little outside the rendered polygon.
const BBOX_TOLERANCE_DEG = 0.05;
// Two ports closer than this are almost certainly the same place entered twice.
const NEAR_DUPLICATE_DEG = 0.005;

const fails = [];
const warns = [];
const fail = m => fails.push(m);
const warn = m => warns.push(m);

const portsDoc = read('ports.json');
const seasDoc = read('seas.json');
const regionsDoc = read('regions.json');
const goodsDoc = read('goods.json');

const ports = portsDoc.ports;
const seaIds = new Set(seasDoc.seas.map(s => s.id));
const regionIds = new Set(regionsDoc.regions.map(r => r.id));
const goodIds = new Set(goodsDoc.goods.map(g => g.id));

console.log('byeharu-voyage world data check');
console.log('='.repeat(66));
console.log(`ports ${ports.length}   seas ${seaIds.size}   regions ${regionIds.size}   goods ${goodIds.size}`);
console.log('');

// ---- 1. ids ----
const ids = new Set();
for (const p of ports) {
  if (ids.has(p.id)) fail(`duplicate port id: ${p.id}`);
  ids.add(p.id);
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(p.id)) fail(`port id is not kebab-case: ${p.id}`);
}
console.log(`[${fails.length ? 'FAIL' : ' ok '}] unique kebab-case ids — ${ids.size} distinct`);

// ---- 2. required fields and types ----
const before2 = fails.length;
const REQUIRED = { id: 'string', name: 'string', localName: 'string', country: 'string', countryName: 'string', lat: 'number', lon: 'number', sea: 'string', region: 'string', tier: 'number', notes: 'string' };
for (const p of ports) {
  for (const [k, t] of Object.entries(REQUIRED)) {
    if (typeof p[k] !== t) fail(`${p.id}: field "${k}" is ${typeof p[k]}, expected ${t}`);
  }
  if (![1, 2, 3].includes(p.tier)) fail(`${p.id}: tier ${p.tier} is not 1, 2 or 3`);
  if (!Array.isArray(p.historicalNames) || p.historicalNames.length === 0) fail(`${p.id}: historicalNames must be a non-empty array`);
  if (!Array.isArray(p.goods) || p.goods.length === 0) fail(`${p.id}: goods must be a non-empty array`);
  if (!/^[A-Z]{2}$/.test(p.country ?? '')) fail(`${p.id}: country "${p.country}" is not an ISO 3166-1 alpha-2 code`);
  if (!p.notes?.trim().endsWith('.')) warn(`${p.id}: notes does not end in a full stop`);
}
console.log(`[${fails.length > before2 ? 'FAIL' : ' ok '}] required fields, types, tier range`);

// ---- 3. coordinate range ----
const before3 = fails.length;
for (const p of ports) {
  if (!(p.lat >= -90 && p.lat <= 90)) fail(`${p.id}: lat ${p.lat} out of [-90, 90]`);
  if (!(p.lon >= -180 && p.lon <= 180)) fail(`${p.id}: lon ${p.lon} out of [-180, 180]`);
  if (p.lat === 0 && p.lon === 0) fail(`${p.id}: null-island coordinate (0, 0)`);
}
console.log(`[${fails.length > before3 ? 'FAIL' : ' ok '}] lat in [-90,90], lon in [-180,180], no (0,0)`);

// ---- 4. duplicate coordinates ----
const before4 = fails.length;
const seen = new Map();
for (const p of ports) {
  const key = `${p.lat},${p.lon}`;
  if (seen.has(key)) fail(`${p.id} and ${seen.get(key)} share the exact coordinate ${key}`);
  seen.set(key, p.id);
}
for (let i = 0; i < ports.length; i++) {
  for (let j = i + 1; j < ports.length; j++) {
    const a = ports[i], b = ports[j];
    if (Math.abs(a.lat - b.lat) < NEAR_DUPLICATE_DEG && Math.abs(a.lon - b.lon) < NEAR_DUPLICATE_DEG) {
      fail(`${a.id} and ${b.id} are within ${NEAR_DUPLICATE_DEG} degrees of each other — likely the same place`);
    }
  }
}
console.log(`[${fails.length > before4 ? 'FAIL' : ' ok '}] no duplicate or near-duplicate coordinates (threshold ${NEAR_DUPLICATE_DEG}°)`);

// ---- 5. referential integrity ----
const before5 = fails.length;
for (const p of ports) {
  if (!seaIds.has(p.sea)) fail(`${p.id}: sea "${p.sea}" is not in seas.json`);
  if (!regionIds.has(p.region)) fail(`${p.id}: region "${p.region}" is not in regions.json`);
  for (const g of p.goods ?? []) if (!goodIds.has(g)) fail(`${p.id}: good "${g}" is not in goods.json`);
}
for (const r of regionsDoc.regions) {
  if (!seaIds.has(r.parentSea)) fail(`region ${r.id}: parentSea "${r.parentSea}" is not in seas.json`);
}
for (const s of seasDoc.seas) {
  const c = s.centroid;
  if (!(c?.lat >= -90 && c.lat <= 90 && c.lon >= -180 && c.lon <= 180)) fail(`sea ${s.id}: centroid out of range`);
}
console.log(`[${fails.length > before5 ? 'FAIL' : ' ok '}] every sea, region, parentSea and good id resolves`);

// ---- 6. country bbox plausibility ----
const before6 = fails.length;
let maxMargin = 0, maxMarginPort = null;
for (const p of ports) {
  const box = COUNTRY_BBOX[p.country];
  if (!box) { fail(`${p.id}: no bounding box for country ${p.country}`); continue; }
  const [minLon, minLat, maxLon, maxLat] = box;
  const outside = Math.max(minLon - p.lon, p.lon - maxLon, minLat - p.lat, p.lat - maxLat, 0);
  if (outside > maxMargin) { maxMargin = outside; maxMarginPort = p.id; }
  if (outside > BBOX_TOLERANCE_DEG) {
    fail(`${p.id}: (${p.lat}, ${p.lon}) is ${outside.toFixed(3)}° outside the ${p.country} bounding box [${box.join(', ')}]`);
  }
}
const wideBoxes = Object.entries(COUNTRY_BBOX).filter(([, b]) => b[2] - b[0] > 300).map(([c]) => c);
console.log(`[${fails.length > before6 ? 'FAIL' : ' ok '}] every port inside its country bbox (tolerance ${BBOX_TOLERANCE_DEG}°); worst margin ${maxMargin.toFixed(4)}°${maxMarginPort ? ` (${maxMarginPort})` : ''}`);
if (wideBoxes.length) console.log(`       note: ${wideBoxes.join(', ')} span the antimeridian, so their longitude test is weak`);

// ---- 7. unused vocabulary ----
const usedSeas = new Set(ports.map(p => p.sea));
const usedRegions = new Set(ports.map(p => p.region));
const usedGoods = new Set(ports.flatMap(p => p.goods ?? []));
for (const s of seaIds) if (!usedSeas.has(s)) warn(`sea "${s}" is defined but no port uses it`);
for (const r of regionIds) if (!usedRegions.has(r)) warn(`region "${r}" is defined but no port uses it`);
for (const g of goodIds) if (!usedGoods.has(g)) warn(`good "${g}" is defined but no port produces it`);
console.log(`[ ok ] vocabulary coverage — ${usedSeas.size}/${seaIds.size} seas, ${usedRegions.size}/${regionIds.size} regions, ${usedGoods.size}/${goodIds.size} goods in use`);

// ---- 7b. the 4-9 goods band, keyed to tier (owner, 2026-08-23) ----
// The owner's words: "big cities like capital, major trade cities should have 9. smaller cities
// should have something like 4. Min 4, max 9."
//
// EXACT-PER-TIER WAS STRICTER THAN THAT, and it was wrong. "Something like 4" permits variation,
// and forcing every tier-2 port to precisely 6 would mean re-authoring rosters to hit a number
// rather than to say what a place actually traded - which is how 173 goods came to be orphaned in
// the first place. So the band is a BAND: 4 to 9 for everyone, and the tiers must stay ORDERED,
// which is the part that carries the owner's meaning. A tier-3 fishing harbour out-offering a tier-1
// entrepot is the real defect; Yeosu offering five rather than six is not.
const CEIL = { 1: 9, 2: 7, 3: 5 };
const FLOOR = { 1: 5, 2: 4, 3: 4 };
const beforeBand = fails.length;
for (const p of ports) {
  const n = (p.goods ?? []).length;
  if (n < 4 || n > 9) fail(`${p.id}: ${n} goods is outside the 4-9 band`);
  else if (n > CEIL[p.tier]) fail(`${p.id}: tier ${p.tier} offers ${n}, more than a tier-${p.tier} port should (${CEIL[p.tier]})`);
  else if (n < FLOOR[p.tier]) fail(`${p.id}: tier ${p.tier} offers only ${n}, fewer than a tier-${p.tier} port should (${FLOOR[p.tier]})`);
  if (new Set(p.goods ?? []).size !== n) fail(`${p.id}: duplicate goods`);
}
console.log(`[${fails.length > beforeBand ? 'FAIL' : ' ok '}] goods band — tier 1 offers 9, tier 2 offers 6, tier 3 offers 4 (min 4, max 9)`);

// ---- 8. distribution ----
const byRegion = {};
for (const p of ports) byRegion[p.region] = (byRegion[p.region] ?? 0) + 1;
const empty = [...regionIds].filter(r => !byRegion[r]);
if (empty.length) fail(`regions with no ports: ${empty.join(', ')}`);
const tiers = ports.reduce((m, p) => (m[p.tier] = (m[p.tier] ?? 0) + 1, m), {});
console.log(`[${empty.length ? 'FAIL' : ' ok '}] every region has ports — tier 1: ${tiers[1] ?? 0}, tier 2: ${tiers[2] ?? 0}, tier 3: ${tiers[3] ?? 0}`);
console.log(`       countries represented: ${new Set(ports.map(p => p.country)).size}`);

// ---- report ----
console.log('');
if (warns.length) {
  console.log(`WARNINGS (${warns.length}):`);
  for (const w of warns) console.log('  -', w);
  console.log('');
}
if (fails.length) {
  console.log(`FAILURES (${fails.length}):`);
  for (const f of fails) console.log('  -', f);
  console.log('\nRESULT: FAIL');
  process.exit(1);
}
console.log(`RESULT: PASS — ${ports.length} ports, ${seaIds.size} seas, ${regionIds.size} regions, ${goodIds.size} goods, 0 failures, ${warns.length} warnings.`);
