-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 0047 — THE SEA IS A FREE PLANE
--        ONE mover over open water. The client PROPOSES a course; the server VERIFIES it against
--        its own raster, MEASURES it itself, and sails it. Any water point is a destination.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
--
-- GENERATED by scripts/gen-0047.mjs against the live chain (the slice-and-replace method: every
-- superseded body is edited by hunks that must occur EXACTLY ONCE in the deployed definition,
-- re-asserted at apply time — a drifted deployment refuses rather than half-applies).
--
-- ── THE ASK (docs/OWNER_REQUESTS.md rows 41-43; docs/NAVIGATION_PLAN.md is the approved plan) ──
-- The owner, three times: "it should go by sea without the fixed route — but fastest way
-- possible. Also, in map, i should be able to pinpoint anywhere in the ocean to make a fleet
-- move." The fixed 782-leg graph routed Lisboa→Nagasaki over the North Pole at 88.6°N for 7,565
-- nm (the honest water is ~12,989 round the Cape), drew 532 of its legs over land, and silently
-- teleported 41 river-port approaches. One wrong model, five logged defects.
--
-- ── THE DESIGN, measured not chosen (NAVIGATION_PLAN §3) ───────────────────────────────────────
-- A* in plpgsql costs 302 s for Lisboa→Calicut; the same search in the browser costs ≤166 ms;
-- VERIFYING a path is all water costs 0.02 ms. So the search runs where it is cheap (the client,
-- src/lib/sea — a PROPOSAL), and the authoritative acts run here: voyage.path_refusal samples
-- every segment against public.sea_raster (0046), voyage.path_nm measures the polyline, and the
-- refusal gates (crew, flagship, draft, ice, endurance) stay ONE authority. A client cannot gain
-- by lying: land is refused, a longer course only costs its own player days and stores, and a
-- shorter water-legal course is simply a better route. With no course attached, the straight
-- line is tried (free, and correct exactly when it verifies); otherwise E_NO_COURSE.
--
-- ── REPLACES — never joins (the predecessor's catastrophe was four overlapping movement paths) ──
--   voyage.route, voyage.route_direct, voyage.path_from_nodes    DROPPED — the graph mover
--   voyage.reach_from(uuid, int, uuid)   DROPPED; reach_from(uuid) reads sea_reaches (0046)
--   voyage.sail_refusal(uuid, uuid, numeric)   DROPPED; (fleet, dest, dest_point, nm) supersedes
--       0036's body whole: same gates, and the no-chandler round-trip rule now prices a bare
--       water point (the way back is the way she came) as well as a sea place (nearest harbour
--       by the reach table).
--   voyage.depart(uuid, uuid[], timestamptz)   DROPPED; depart(fleet, segments, origin, dest)
--   voyage.position   DROPPED and re-cut: the point is placed linearly along the SEGMENT — the
--       same interpolation path_refusal samples, so the line judged, sailed and drawn is one.
--   cmd.do_sail   re-cut whole (0019's body): verify → measure → gate → depart.
--   cmd.divert(uuid, uuid)   DROPPED; (fleet, dest, dest_point, path) supersedes 0037: she turns
--       AT HER POSITION (truncate, settle to anchor through the one arrival arm, clear the
--       stale queue, one SAIL through the one parser). 0037's node-turn existed only because
--       routing from a point was impossible; it is not any more.
--   cmd.issue / cmd.preview   DROPPED and re-cut with p_path jsonb (the proposed course rides
--       the ARGS and is verified at execution); preview accepts ANCHORED.
--   world.trade_routes   DROPPED and re-cut: the scan radius is SAILED NM over sea_reaches
--       (sea_scan_radius_nm, default 1,700 = the measured median horizon of the old 2-leg scan),
--       and every quoted nm is now honest water — the Asian trade stops being priced at half its
--       true distance.
--   voyage.settle   SLICED (2 hunks): the arrival arm anchors an open-water end (ANCHORED,
--       lat/lon held) and the report carries from_point/to_point. Wage/ration/hazard arithmetic
--       untouched BY CONSTRUCTION — the slices are the only change, occurs-exactly-once.
--   cmd.advance   SLICED (1 hunk): ANCHORED runs the queue (quay verbs still refuse themselves).
--   cmd.parse   SLICED: SAIL takes a port OR a lat,lon point; VIA retired with the graph.
--   cmd.verb_schema   SLICED: SAIL's dest is type "place"; the composer renders it.
--   world.snapshot   SLICED: the legs block is gone from the wire.
--   world.fleets   SLICED (2 hunks): fleets carry anchor; a voyage serves its whole course,
--       dest_point, and the re-cut position shape.
--   public.client_rpc_entry_points   re-cut whole: issue/preview/divert/trade_routes signatures,
--       plus world.sea_raster and world.reach.
--
-- ── WHAT SURVIVES UNTOUCHED, deliberately ──────────────────────────────────────────────────────
--   voyage.progress_nm / sim_hours / total_days / day_ends_at / delay_before_day / recompute_eta
--   / rng / hazard_roll / leg_at_day — they read only 'nm', 'sea_id', 'hazard_mult', which every
--   new segment carries under the same names. A computed course is still a FIXED course once
--   departed: speed_profile freezes per segment and proof 01's offline equivalence rests exactly
--   where 0006 put it. THE WIND SEAM: a segment has a bearing, so the coming wind slice
--   multiplies the per-segment frozen speed inside voyage.depart by a pure function of
--   (segment, season, world secret) — nothing else will have to move. public.legs stays as
--   history for the moment, with no reader left in the mover — 0049 (the graph is history)
--   drops the table itself: a table nobody reads is drift waiting to be trusted.
--
-- ── CARRIED FORWARD ────────────────────────────────────────────────────────────────────────────
--   Pre-0047 voyages store leg REFERENCES; they are converted in place to legacy-marked segments
--   (same nm, same seas, same frozen speeds — the schedule is byte-identical) so every reader
--   speaks one shape. The land guard reports legacy paths rather than walking them: a straight
--   line between two ports is exactly the shape the old model drew and the new one forbids.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- ── 0. The slice tool: replace hunks that must occur exactly once, else refuse ─────────────────
create or replace function pg_temp.recut(p_fn regprocedure, p_drop boolean, variadic p_edits text[])
returns void
language plpgsql
as $$
declare
  v_def text := pg_get_functiondef(p_fn);
  v_i   int := 1;
  v_n   int;
begin
  while v_i < array_length(p_edits, 1) loop
    v_n := (length(v_def) - length(replace(v_def, p_edits[v_i], ''))) / length(p_edits[v_i]);
    if v_n <> 1 then
      raise exception '0047 slice: hunk % of % occurs % time(s) in %, expected exactly 1 — the deployed body is not what this migration was generated against. Regenerate with scripts/gen-0047.mjs.',
        (v_i + 1) / 2, (array_length(p_edits, 1)) / 2, v_n, p_fn;
    end if;
    v_def := replace(v_def, p_edits[v_i], p_edits[v_i + 1]);
    v_i := v_i + 2;
  end loop;
  if p_drop then
    execute format('drop function %s', p_fn::text);
  end if;
  execute v_def;
end $$;

-- ── 1. The knobs ───────────────────────────────────────────────────────────────────────────────
insert into public.world_config (key, value, description) values
  ('course_join_nm', to_jsonb(15),
   '0047: how far a proposed course''s first/last point may sit from the stated origin/destination (and how far a divert''s course may start from the fleet''s true position before the bridge is prepended). One raster cell is ~15 nm at the equator.'),
  ('sea_scan_radius_nm', to_jsonb(1700),
   '0047: how far out, in SAILED nautical miles over sea_reaches, world.trade_routes looks by default. 1,700 is measured, not chosen: the median horizon of the old 2-leg leg-graph scan across all 214 harbours was 1,669 nm (median 14 destinations). Replaces route_scan_max_legs.')
on conflict (key) do nothing;

-- The 2-leg knob has no reader left; a knob nobody reads is drift waiting to be trusted.
delete from public.world_config where key = 'route_scan_max_legs';

-- ── 2. A fleet can hold a POSITION: the anchor columns and the one status/position law ─────────
alter table public.fleets add column if not exists lat numeric, add column if not exists lon numeric;

do $$
declare v_name text;
begin
  -- 0004's inline position check said "not SAILING means in a port", which ANCHORED breaks.
  -- It was unnamed, so it is found by its own definition rather than by a guessed name.
  select conname into v_name
    from pg_constraint
   where conrelid = 'public.fleets'::regclass and contype = 'c'
     and pg_get_constraintdef(oid) like '%port_id%' and pg_get_constraintdef(oid) like '%SAILING%';
  if v_name is null then
    raise exception '0047 self-assert FAIL: the 0004 fleet position check was not found to supersede';
  end if;
  execute format('alter table public.fleets drop constraint %I', v_name);
end $$;

alter table public.fleets add constraint fleets_position_states check (
  case status
    when 'SAILING'  then port_id is null and lat is null and lon is null
    when 'ANCHORED' then port_id is null and lat is not null and lon is not null
    when 'DOCKED'   then port_id is not null and lat is null and lon is null
    when 'REPAIRING' then port_id is not null and lat is null and lon is null
    -- UNABLE_TO_SAIL / ADRIFT: wherever it happened — a berth, or a held position
    else (port_id is not null and lat is null and lon is null)
      or (port_id is null and lat is not null and lon is not null)
  end);

-- A voyage's ends may now be open water: the port references become nullable; the path itself
-- always carries the coordinates.
alter table public.voyages alter column origin_port_id drop not null,
                           alter column dest_port_id drop not null;

-- ── 3. THE SEAM: which sea is this point in? — COMPOSED, never duplicated ──────────────────────
-- 0040 (every water answers its sea) already holds THE membership authority:
-- voyage.sea_at(lat, lon) over public.sea_cells, boundaries from Natural Earth's marine
-- polygons. The helm cut of this migration shipped an interim nearest-port body and declared
-- the signature a seam for exactly that slice to fill; it landed first here, so this file
-- creates NOTHING for membership — it COMPOSES. What a course segment needs beyond sea_at is
-- tolerance for its own approach: sea_at is strict (null on land, and a harbour's cell is
-- usually land at this resolution), while every segment must carry a sea or hazards lose
-- their spatial dimension. So:
--   voyage.sea_near(lat, lon)  the sea AT the point, else the nearest claimed water by
--                              expanding ring over cell centres — the same 8-ring rule 0040's
--                              own self-assert resolves ports with — each probe answered by
--                              voyage.sea_at itself. It raises beyond 8 rings: a verified
--                              water course through sea nobody claims is a world defect, and
--                              it must never ship as a silent null.
-- Consumers: voyage.segments_from_course (hazard sea per segment); the coming NPC-region
-- system reads voyage.sea_at directly (a fleet at anchor holds a strict water point).
create or replace function voyage.sea_near(p_lat double precision, p_lon double precision)
returns uuid
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_sea  uuid;
  v_ring int; v_dr int; v_dc int;
begin
  v_sea := voyage.sea_at(p_lat, p_lon);
  if v_sea is not null then return v_sea; end if;
  for v_ring in 1 .. 8 loop
    for v_dr in -v_ring .. v_ring loop
      for v_dc in -v_ring .. v_ring loop
        continue when greatest(abs(v_dr), abs(v_dc)) <> v_ring;
        v_sea := voyage.sea_at(p_lat + v_dr * 0.25, p_lon + v_dc * 0.25);
        if v_sea is not null then return v_sea; end if;
      end loop;
    end loop;
  end loop;
  raise exception 'E_NO_SEA: no sea claims the water near %, % within 8 rings — the membership raster (0040) and the passability raster (0046) disagree here', round(p_lat::numeric, 2), round(p_lon::numeric, 2) using errcode = 'P0001';
end $$;

revoke all on function voyage.sea_near(double precision, double precision) from public, anon, authenticated;

-- How far a coordinate sits from sailable water — the MEASURED approach allowance for a course
-- end that is not a port (a fleet's own position, a pinpointed spot). A port's figure lives in
-- sea_reaches.snap_nm, measured the same way at generation; this is the same rule at runtime,
-- so an end's exemption is never a guess. Found the expensive way: a fleet minutes out of
-- Lisboa still stands INSIDE Lisboa's approach — where her verified course legitimately crosses
-- land cells — and a flat 25 nm allowance refused her own turn as E_LAND.
create or replace function voyage.water_snap_nm(p_lat numeric, p_lon numeric)
returns numeric
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  r public.sea_raster%rowtype;
  v_row int; v_col int; ring int; dr int; dc int; rr int; cc int;
  v_best numeric := null;
  v_nm numeric;
begin
  select * into r from public.sea_raster where id = 1;
  v_row := least(r.rows - 1, greatest(0, floor((90 - p_lat) / r.cell_deg)::int));
  v_col := ((floor((p_lon + 180) / r.cell_deg)::int % r.cols) + r.cols) % r.cols;
  if get_bit(r.cells, (v_row * r.cols + v_col) * r.bits_per_cell) = 1 then
    return 0;
  end if;
  for ring in 1 .. 12 loop
    for dr in -ring .. ring loop
      rr := v_row + dr;
      continue when rr < 0 or rr >= r.rows;
      for dc in -ring .. ring loop
        continue when greatest(abs(dr), abs(dc)) <> ring;
        cc := ((v_col + dc) % r.cols + r.cols) % r.cols;
        if get_bit(r.cells, (rr * r.cols + cc) * r.bits_per_cell) = 1 then
          v_nm := voyage.gc_distance_nm(p_lat::float8, p_lon::float8,
                    (90 - (rr + 0.5) * r.cell_deg)::float8, (-180 + (cc + 0.5) * r.cell_deg)::float8)::numeric;
          if v_best is null or v_nm < v_best then v_best := v_nm; end if;
        end if;
      end loop;
    end loop;
    exit when v_best is not null;
  end loop;
  return coalesce(v_best, 999);
end $$;

revoke all on function voyage.water_snap_nm(numeric, numeric) from public, anon, authenticated;

-- ── 4. A verified course becomes THE stored path: segments that carry their own water ──────────
create or replace function voyage.segments_from_course(p_course jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
-- One segment per sub-leg of the polyline, each carrying:
--   nm           its own length (the measure's rule, per piece — the stored total is their sum)
--   sea_id       voyage.sea_near at the midpoint (0040's sea_at composed with the 8-ring
--                approach tolerance), so free water keeps hazard's spatial dimension
--   hazard_mult  SHELTER, derived from the raster: land (or ice) within ~2 cells 0.8 — in sight
--                of refuge; none within ~7 cells 1.2 — days from shelter; else 1.0. The old
--                leg-graph texture keyed on authored endpoints; free segments key on the one
--                fact the raster knows. Sea character (piracy, base rate) stays in seas.*.
-- Segments over 500 nm are SPLIT into equal parts, so an ocean crossing changes sea and shelter
-- as it goes instead of wearing one midpoint's answer for 3,000 nm.
declare
  r        public.sea_raster%rowtype;
  out_segs jsonb := '[]'::jsonb;
  i int; k int; n int; pieces int;
  lat1 float8; lon1 float8; lat2 float8; lon2 float8;
  alat float8; alon float8; blat float8; blon float8;
  seg_nm numeric; mlat float8; mlon float8;
  v_row int; v_col int; ring int; dr int; dc int; rr int; cc int;
  v_land_ring int;
begin
  select * into r from public.sea_raster where id = 1;
  n := coalesce(jsonb_array_length(p_course), 0);
  for i in 0 .. n - 2 loop
    lat1 := (p_course->i->>0)::float8;     lon1 := (p_course->i->>1)::float8;
    lat2 := (p_course->(i+1)->>0)::float8; lon2 := (p_course->(i+1)->>1)::float8;
    pieces := greatest(1, ceil(voyage.gc_distance_nm(lat1, lon1, lat2, lon2) / 500)::int);
    for k in 0 .. pieces - 1 loop
      alat := lat1 + (lat2 - lat1) * k / pieces;       alon := lon1 + (lon2 - lon1) * k / pieces;
      blat := lat1 + (lat2 - lat1) * (k + 1) / pieces; blon := lon1 + (lon2 - lon1) * (k + 1) / pieces;
      seg_nm := round(voyage.gc_distance_nm(alat, alon, blat, blon)::numeric, 2);
      continue when seg_nm <= 0;
      mlat := (alat + blat) / 2; mlon := (alon + blon) / 2;
      v_row := least(r.rows - 1, greatest(0, floor((90 - mlat) / r.cell_deg)::int));
      v_col := ((floor((mlon + 180) / r.cell_deg)::int % r.cols) + r.cols) % r.cols;
      v_land_ring := null;
      for ring in 1 .. 7 loop
        for dr in -ring .. ring loop
          rr := v_row + dr;
          continue when rr < 0 or rr >= r.rows;
          for dc in -ring .. ring loop
            continue when greatest(abs(dr), abs(dc)) <> ring;
            cc := ((v_col + dc) % r.cols + r.cols) % r.cols;
            if get_bit(r.cells, (rr * r.cols + cc) * r.bits_per_cell) = 0 then
              v_land_ring := ring;
              exit;
            end if;
          end loop;
          exit when v_land_ring is not null;
        end loop;
        exit when v_land_ring is not null;
      end loop;
      out_segs := out_segs || jsonb_build_object(
        'a', jsonb_build_array(round(alat::numeric, 4), round(alon::numeric, 4)),
        'b', jsonb_build_array(round(blat::numeric, 4), round(blon::numeric, 4)),
        'nm', seg_nm,
        'sea_id', voyage.sea_near(mlat, mlon),
        'hazard_mult', case when v_land_ring is not null and v_land_ring <= 2 then 0.8
                            when v_land_ring is null then 1.2
                            else 1.0 end);
    end loop;
  end loop;
  return out_segs;
end $$;

revoke all on function voyage.segments_from_course(jsonb) from public, anon, authenticated;

-- The polyline a stored path sails: first segment's a, then every b, in order. Serves the chart
-- (world.fleets) and the land guard; ONE reading of "what line is this voyage on".
create or replace function voyage.course_of(p_path jsonb)
returns jsonb
language sql
immutable
as $$
  select case when p_path is null or jsonb_array_length(p_path) = 0 then '[]'::jsonb
              else jsonb_build_array(p_path->0->'a')
                   || (select coalesce(jsonb_agg(t.s->'b' order by t.ord), '[]'::jsonb)
                         from jsonb_array_elements(p_path) with ordinality t(s, ord))
         end
$$;

-- ── 5. The graph mover is DROPPED — one mover, never two ───────────────────────────────────────
drop function voyage.route(uuid, uuid, uuid[]);
drop function voyage.route_direct(uuid, uuid);
drop function voyage.path_from_nodes(uuid[]);
drop function voyage.reach_from(uuid, int, uuid);
drop function voyage.sail_refusal(uuid, uuid, numeric);
drop function voyage.depart(uuid, uuid[], timestamptz);
drop function voyage.position(uuid, timestamptz);
drop function cmd.divert(uuid, uuid);

-- ── 6. THE sailed distance, from the reach table (0046) ────────────────────────────────────────
create or replace function voyage.reach_from(p_from uuid)
returns table (port_id uuid, code text, nm numeric)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Supersedes 0019's graph Dijkstra: the figures come from public.sea_reaches — computed from
  -- the raster by the one pathfinder, Arctic closed, no Suez, no Panama — so the number a quay
  -- quotes and the water a fleet sails can no longer be two different worlds.
  select b.port_id, e.code, e.nm::numeric
    from public.sea_reaches a
   cross join lateral jsonb_each_text(a.reaches) e(code, nm)
    join public.sea_reaches b on b.code = e.code
   where a.port_id = p_from
$$;

revoke all on function voyage.reach_from(uuid) from public, anon, authenticated;

-- ── 7. THE one answer to "may this fleet sail there?" ──────────────────────────────────────────
create or replace function voyage.sail_refusal(p_fleet uuid, p_dest uuid, p_dest_point jsonb, p_nm numeric)
returns text
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
-- Supersedes 0036's leg-graph body (dropped above). What changed and what did not:
--   * she may sail from a quay OR from her own anchor — the sea is a free plane;
--   * draft and ice-closure are asked only of a HARBOUR destination: they are berth facts, and
--     open water has neither;
--   * the stores gate: a destination with a chandler needs stores for the passage; one WITHOUT
--     (a sea place, or any bare point of water) needs the ROUND TRIP — out, plus the way back
--     to provisioning: a sea place's nearest harbour by the reach table, or for a bare point
--     the way she came, which is the one water she is PROVEN able to sail. Same one-way-trap
--     rule 0036 wrote for spur legs, priced off the reach table.
declare
  f       public.fleets%rowtype;
  v_short int;
  v_flag  numeric;
  v_draft int;
  v_maxd  int;
  v_kind  text;
  v_speed numeric;
  v_days  numeric;
  v_end   numeric;
  v_back  numeric := 0;
begin
  select * into f from public.fleets where id = p_fleet;
  if f.id is null then
    return 'E_NO_SUCH_FLEET: there is no such fleet';
  end if;
  if f.status not in ('DOCKED', 'ANCHORED') then
    return format('E_NOT_DOCKED: %s is %s and must be docked or lying at anchor to sail', f.name, f.status);
  end if;

  select count(*) into v_short
    from public.ships s join public.ship_classes c on c.id = s.class_id
   where s.fleet_id = p_fleet and s.crew < c.crew_required;
  if v_short > 0 then
    return format('E_CREW_SHORT: %s ship(s) are below their required complement', v_short);
  end if;

  select coalesce(durability, 0) into v_flag from public.ships where fleet_id = p_fleet and is_flagship;
  if coalesce(v_flag, 0) <= 0 then
    return 'E_FLAGSHIP_DISABLED: the flagship cannot sail until it is repaired';
  end if;

  if p_dest is not null then
    select kind into v_kind from public.ports where id = p_dest;
    if v_kind = 'HARBOUR' then
      select max(c.draft) into v_draft from public.ships s join public.ship_classes c on c.id = s.class_id
       where s.fleet_id = p_fleet;
      select max_draft into v_maxd from public.ports where id = p_dest;
      if v_draft > v_maxd then
        return format('E_DRAFT: the deepest hull draws %s and that port takes %s', v_draft, v_maxd);
      end if;
      if (select is_ice_closed from public.ports where id = p_dest) then
        return 'E_PORT_CLOSED: that port is closed';
      end if;
    end if;
  end if;

  v_speed := voyage.fleet_speed(p_fleet);
  v_end   := voyage.endurance_days(p_fleet);
  if p_dest is not null and (select kind from public.ports where id = p_dest) = 'SEA_PLACE' then
    select min(e.nm::numeric) into v_back
      from public.sea_reaches sr
     cross join lateral jsonb_each_text(sr.reaches) e(code, nm)
      join public.ports hp on hp.code = e.code and hp.kind = 'HARBOUR'
     where sr.port_id = p_dest;
  elsif p_dest is null and p_dest_point is not null then
    v_back := p_nm;
  end if;
  v_days := ((p_nm + coalesce(v_back, 0)) / v_speed) / 24;
  if v_end < v_days * public.wc_num('endurance_margin') then
    if coalesce(v_back, 0) > 0 then
      return format('E_ENDURANCE: %s carries %s days of stores, and there is no chandler where she is bound — the round trip is %s voyage-days; you need %s — PROVISION first',
        f.name, round(v_end, 1), round(v_days, 1), round(v_days * public.wc_num('endurance_margin'), 1));
    end if;
    return format('E_ENDURANCE: %s carries %s days of stores and that route is %s voyage-days; you need %s — PROVISION first',
      f.name, round(v_end, 1), round(v_days, 1), round(v_days * public.wc_num('endurance_margin'), 1));
  end if;
  return null;
end $$;

comment on function voyage.sail_refusal(uuid, uuid, jsonb, numeric) is
  'THE one answer to "may this fleet sail there, right now?" — status, crew, flagship, berth '
  'facts for harbours, and the stores gate with the no-chandler round trip. cmd.do_sail RAISES '
  'what this returns and world.trade_routes refuses to recommend what this refuses. Supersedes '
  '0036''s leg-graph body (0047).';

revoke all on function voyage.sail_refusal(uuid, uuid, jsonb, numeric) from public, anon, authenticated;

-- ── 8. Departure: the ONE place a voyage is born ───────────────────────────────────────────────
create or replace function voyage.depart(p_fleet uuid, p_segments jsonb, p_origin_port uuid, p_dest_port uuid, p_at timestamptz default now())
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
-- Supersedes 0006's node-list body (dropped above). The path is SEGMENTS of verified open water;
-- each keeps the speed frozen for it at departure — THE WIND SEAM: when wind lands, this loop
-- multiplies v_speed by a pure function of (segment, season, world secret) and nothing else in
-- the schedule moves. A computed course is still a FIXED course once departed: closed form,
-- per-element freeze, delays as recorded sim-hours — exactly what proof 01 rests on.
declare
  v_total   numeric := 0;
  v_hours   numeric := 0;
  v_speed   numeric;
  v_profile jsonb := '[]'::jsonb;
  v_player  uuid;
  v_voyage  uuid;
  e         jsonb;
begin
  select player_id into v_player from public.fleets where id = p_fleet;
  if v_player is null then
    raise exception 'E_NO_SUCH_FLEET: %', p_fleet using errcode = 'P0001';
  end if;
  if p_segments is null or jsonb_typeof(p_segments) <> 'array' or jsonb_array_length(p_segments) < 1 then
    raise exception 'E_BAD_PATH: a voyage needs at least one segment of water' using errcode = 'P0001';
  end if;
  v_speed := voyage.fleet_speed(p_fleet);
  for e in select * from jsonb_array_elements(p_segments) loop
    v_profile := v_profile || to_jsonb(v_speed);
    v_total   := v_total + (e->>'nm')::numeric;
    v_hours   := v_hours + (e->>'nm')::numeric / v_speed;
  end loop;

  insert into public.voyages (fleet_id, player_id, path, total_nm, speed_profile, departed_at, eta,
                              origin_port_id, dest_port_id)
  values (p_fleet, v_player, p_segments, v_total, v_profile, p_at,
          p_at + make_interval(secs => (v_hours * 3600 / public.wc_num('time_compression'))::double precision),
          p_origin_port, p_dest_port)
  returning id into v_voyage;

  update public.fleets
     set status = 'SAILING', port_id = null, lat = null, lon = null, version = version + 1
   where id = p_fleet;

  return v_voyage;
end $$;

revoke all on function voyage.depart(uuid, jsonb, uuid, uuid, timestamptz) from public, anon, authenticated;

-- ── 9. The closed-form place on the water ──────────────────────────────────────────────────────
create or replace function voyage.position(p_voyage uuid, p_at timestamptz default now())
returns table (seg_index int, leg_frac numeric, nm_done numeric, total_nm numeric, lat numeric, lon numeric)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
-- Supersedes 0006's port-interpolating body (dropped above). Same rule, new geometry:
-- progress_nm is unchanged, and the point is placed LINEARLY along the segment the progress
-- falls in — the SAME interpolation voyage.path_refusal samples, so the line judged, the line
-- sailed and the point drawn are one line.
declare
  v       public.voyages%rowtype;
  v_done  numeric;
  v_acc   numeric := 0;
  i       int := 0;
  e       jsonb;
  v_nm    numeric;
begin
  select * into v from public.voyages where id = p_voyage;
  if v.id is null then
    raise exception 'E_NO_SUCH_VOYAGE: %', p_voyage using errcode = 'P0001';
  end if;
  v_done := voyage.progress_nm(p_voyage, p_at);
  for e in select * from jsonb_array_elements(v.path) loop
    v_nm := (e->>'nm')::numeric;
    if v_done <= v_acc + v_nm or i = jsonb_array_length(v.path) - 1 then
      seg_index := i;
      leg_frac  := round(least(1, greatest(0, case when v_nm = 0 then 1 else (v_done - v_acc) / v_nm end)), 6);
      nm_done   := v_done;
      total_nm  := v.total_nm;
      lat := round(((e->'a'->>0)::numeric + ((e->'b'->>0)::numeric - (e->'a'->>0)::numeric) * leg_frac), 4);
      lon := round(((e->'a'->>1)::numeric + ((e->'b'->>1)::numeric - (e->'a'->>1)::numeric) * leg_frac), 4);
      return next;
      return;
    end if;
    v_acc := v_acc + v_nm;
    i := i + 1;
  end loop;
end $$;

revoke all on function voyage.position(uuid, timestamptz) from public, anon;
grant execute on function voyage.position(uuid, timestamptz) to authenticated;

-- ── 10. THE ONE MOVER ──────────────────────────────────────────────────────────────────────────
create or replace function cmd.do_sail(p_fleet uuid, p_args jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
-- Supersedes 0019's leg-graph body whole. The client PROPOSES a course (args.path, attached by
-- cmd.issue's p_path); the server VERIFIES it against its own raster and MEASURES it itself —
-- verification is the authoritative act, and no client number is ever believed. With no course
-- attached, the straight line is tried — free, and correct exactly when it verifies — otherwise
-- the order is refused E_NO_COURSE rather than guessed at.
declare
  f         public.fleets%rowtype;
  v_dest    uuid := nullif(p_args->>'dest', '')::uuid;
  v_point   jsonb := p_args->'dest_point';
  v_course  jsonb := p_args->'path';
  v_plotted boolean := coalesce(jsonb_typeof(p_args->'path') = 'array', false);
  v_olat numeric; v_olon numeric; v_head numeric;
  v_dlat numeric; v_dlon numeric; v_tail numeric;
  v_ref    text;
  v_nm     numeric;
  v_segs   jsonb;
  v_speed  numeric;
  v_voyage uuid;
begin
  select * into f from public.fleets where id = p_fleet;

  -- the gates that need no distance, first (status, crew, flagship, and the berth facts)
  v_ref := voyage.sail_refusal(p_fleet, v_dest, v_point, 0);
  if v_ref is not null then
    raise exception '%', v_ref using errcode = 'P0001';
  end if;

  -- where she lies: a quay, or her own anchor. The approach allowance is the MEASURED snap of
  -- the place plus 25 nm slack — the same rule (snap + one cell) the client's straightener
  -- applies, held slightly looser here so a course the client passed cannot be refused for its
  -- own approach.
  if f.port_id is not null then
    select p.lat, p.lon into v_olat, v_olon from public.ports p where p.id = f.port_id;
    v_head := coalesce((select snap_nm from public.sea_reaches where port_id = f.port_id), 0) + 25;
  else
    -- her own position: the approach is MEASURED, not guessed — a fleet minutes off a river
    -- quay still stands inside that port's approach, where her verified course crosses land
    -- cells, and a flat allowance refused her own turn as E_LAND (the acceptance drive).
    v_olat := f.lat; v_olon := f.lon;
    v_head := voyage.water_snap_nm(v_olat, v_olon) + 25;
  end if;

  -- where she is bound
  if v_dest is not null then
    if v_dest = f.port_id then
      raise exception 'E_SAME_DEST: % already lies there', f.name using errcode = 'P0001';
    end if;
    select p.lat, p.lon into v_dlat, v_dlon from public.ports p where p.id = v_dest;
    if v_dlat is null then
      raise exception 'E_NO_SUCH_PORT: there is no such port' using errcode = 'P0001';
    end if;
    v_tail := coalesce((select snap_nm from public.sea_reaches where port_id = v_dest), 0) + 25;
  elsif v_point is not null then
    v_dlat := (v_point->>'lat')::numeric; v_dlon := (v_point->>'lon')::numeric;
    if v_dlat is null or v_dlon is null or abs(v_dlat) > 90 or abs(v_dlon) > 180 then
      raise exception 'E_BAD_PATH: that is not a point on the sphere' using errcode = 'P0001';
    end if;
    v_tail := voyage.water_snap_nm(v_dlat, v_dlon) + 25;
    if voyage.gc_distance_nm(v_olat::float8, v_olon::float8, v_dlat::float8, v_dlon::float8)
         <= public.wc_num('course_join_nm') then
      raise exception 'E_SAME_DEST: % already lies there', f.name using errcode = 'P0001';
    end if;
  else
    raise exception 'E_PARSE: SAIL needs a destination - a port, or a lat,lon point of open sea' using errcode = 'P0001';
  end if;

  -- the course: proposed, or the straight line when none was
  if not v_plotted then
    v_course := jsonb_build_array(jsonb_build_array(v_olat, v_olon), jsonb_build_array(v_dlat, v_dlon));
  end if;
  v_ref := voyage.path_refusal(v_course, v_olat, v_olon, v_dlat, v_dlon,
                               public.wc_num('course_join_nm'), v_head, v_tail);
  if v_ref is not null then
    if not v_plotted and v_ref like 'E_LAND:%' then
      raise exception 'E_NO_COURSE: the straight way is not open water - the chart plots the course at the moment of ordering' using errcode = 'P0001';
    end if;
    raise exception '%', v_ref using errcode = 'P0001';
  end if;

  -- THE MEASURE - the server's own, never the client's
  v_segs := voyage.segments_from_course(v_course);
  select sum((s->>'nm')::numeric) into v_nm from jsonb_array_elements(v_segs) s;

  v_ref := voyage.sail_refusal(p_fleet, v_dest, v_point, v_nm);
  if v_ref is not null then
    raise exception '%', v_ref using errcode = 'P0001';
  end if;

  v_speed := voyage.fleet_speed(p_fleet);
  v_voyage := voyage.depart(p_fleet, v_segs, f.port_id, v_dest);
  perform public.emit_event(f.player_id, 'DEPARTED', jsonb_build_object(
    'fleet', f.name, 'voyage_id', v_voyage, 'total_nm', v_nm,
    'points', jsonb_array_length(v_course),
    'dest', coalesce((select code from public.ports where id = v_dest),
                     format('%s,%s', round(v_dlat, 2), round(v_dlon, 2))),
    'eta', (select eta from public.voyages where id = v_voyage)));
  return jsonb_build_object('voyage_id', v_voyage, 'total_nm', v_nm,
                            'voyage_days', round((v_nm / v_speed) / 24, 2));
end $$;

revoke all on function cmd.do_sail(uuid, jsonb) from public, anon, authenticated;

-- ── 11. Pre-0047 voyages are carried forward: leg references become legacy segments ────────────
create or replace function voyage.convert_leg_path(p_path jsonb)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Each leg becomes one segment with the SAME nm, sea and hazard weight — the frozen contract
  -- (nm and per-element speeds are what the schedule is made of) is untouched to the byte — its
  -- endpoints the two ports' coordinates, and a 'legacy' mark: a straight line between ports is
  -- exactly the shape the old model drew, so the land guard reports these rather than walks them.
  select coalesce(jsonb_agg(jsonb_build_object(
           'a', jsonb_build_array(pa.lat, pa.lon),
           'b', jsonb_build_array(pb.lat, pb.lon),
           'nm', (t.e->>'nm')::numeric,
           'sea_id', t.e->'sea_id',
           'hazard_mult', t.e->'hazard_mult',
           'legacy', true) order by t.ord), '[]'::jsonb)
    from jsonb_array_elements(p_path) with ordinality t(e, ord)
    join public.ports pa on pa.id = (t.e->>'from_id')::uuid
    join public.ports pb on pb.id = (t.e->>'to_id')::uuid
$$;

revoke all on function voyage.convert_leg_path(jsonb) from public, anon, authenticated;

do $$
declare v_old int; v_left int;
begin
  -- MEASURED DELTA, not a bare count: how many the world held, and none left behind.
  select count(*) into v_old from public.voyages where path->0 ? 'leg_id';
  update public.voyages set path = voyage.convert_leg_path(path) where path->0 ? 'leg_id';
  select count(*) into v_left from public.voyages where path->0 ? 'leg_id';
  if v_left <> 0 then
    raise exception '0047 self-assert FAIL: % voyage(s) still carry leg-shaped paths after conversion', v_left;
  end if;
  raise notice '0047 carry-forward: % pre-0047 voyage path(s) converted to legacy-marked segments', v_old;
end $$;

-- ── 12. The slices: six live bodies, edited by exactly-once hunks ──────────────────────────────
select pg_temp.recut('voyage.settle(uuid, timestamptz)'::regprocedure, false,
  $sdo$    update public.fleets
       set status = case when (select durability from public.ships where fleet_id = p_fleet and is_flagship) <= 0
                         then 'UNABLE_TO_SAIL' else 'DOCKED' end,
           port_id = v.dest_port_id, version = version + 1
     where id = p_fleet;$sdo$,
  $sdn$    -- 0047: she docks at a HARBOUR or a SEA PLACE; at a bare point of water she comes to ANCHOR,
    -- holding the exact coordinate her course ends at. UNABLE_TO_SAIL still outranks both, and an
    -- open-water end keeps its position either way.
    update public.fleets
       set status = case when (select durability from public.ships where fleet_id = p_fleet and is_flagship) <= 0
                         then 'UNABLE_TO_SAIL'
                         when v.dest_port_id is null then 'ANCHORED'
                         else 'DOCKED' end,
           port_id = v.dest_port_id,
           lat = case when v.dest_port_id is null then (v.path->(jsonb_array_length(v.path)-1)->'b'->>0)::numeric end,
           lon = case when v.dest_port_id is null then (v.path->(jsonb_array_length(v.path)-1)->'b'->>1)::numeric end,
           version = version + 1
     where id = p_fleet;$sdn$,
  $sro$      'from', (select code from public.ports where id = v.origin_port_id),
      'to',   (select code from public.ports where id = v.dest_port_id),$sro$,
  $srn$      'from', (select code from public.ports where id = v.origin_port_id),
      'to',   (select code from public.ports where id = v.dest_port_id),
      -- 0047: an open-water end has no code; the report carries the point instead, and a screen
      -- prints the coordinate rather than inventing a name for nowhere.
      'from_point', case when v.origin_port_id is null then v.path->0->'a' end,
      'to_point',   case when v.dest_port_id  is null then v.path->(jsonb_array_length(v.path)-1)->'b' end,$srn$);

select pg_temp.recut('cmd.advance(uuid, timestamptz)'::regprocedure, false,
  $avo$    exit when f.status <> 'DOCKED';   -- SAILING / ADRIFT / UNABLE_TO_SAIL: nothing can execute$avo$,
  $avn$    -- 0047: a fleet ANCHORED at a point of open water runs her queue too — that is how a queued
    -- onward SAIL departs from a pinpointed spot. Every verb that needs a quay refuses her itself
    -- (E_NOT_DOCKED), so nothing a chandler sells can be conjured at sea by this line.
    exit when f.status not in ('DOCKED', 'ANCHORED');   -- SAILING / ADRIFT / UNABLE_TO_SAIL: nothing can execute$avn$);

select pg_temp.recut('cmd.parse(uuid, uuid, text)'::regprocedure, false,
  $pso$  if v_verb = 'SAIL' then
    -- Keywords TO / VIA are noise-tolerant (DESIGN F.1): omitting them is accepted.
    while i <= n and upper(cmd.fold(t[i])) = 'TO' loop i := i + 1; end loop;
    if i > n then
      raise exception 'E_PARSE: SAIL needs a destination port' using errcode = 'P0001';
    end if;
    v_args := jsonb_build_object('dest', cmd.resolve_port(t[i]));
    i := i + 1;
    while i <= n loop
      if upper(cmd.fold(t[i])) = 'VIA' then i := i + 1; continue; end if;
      v_via := v_via || to_jsonb(cmd.resolve_port(t[i])::text);
      i := i + 1;
    end loop;
    v_args := v_args || jsonb_build_object('via', v_via);
$pso$,
  $psn$  if v_verb = 'SAIL' then
    -- Keyword TO is noise-tolerant (DESIGN F.1): omitting it is accepted. 0047: the destination
    -- is a HARBOUR (a port token) or ANY POINT OF OPEN SEA, written lat,lon in decimal degrees
    -- ("SAIL TO 33,-15") — the map writes that token when the player pinpoints the water. VIA is
    -- retired WITH the leg graph it belonged to: a course is proposed as a polyline by the chart
    -- at the moment of ordering, not spelt port by port, so trailing tokens are a parse error
    -- rather than silently swallowed waypoints (docs/NO_SPAGHETTI.md 7C).
    while i <= n and upper(cmd.fold(t[i])) = 'TO' loop i := i + 1; end loop;
    if i > n then
      raise exception 'E_PARSE: SAIL needs a destination - a port, or a lat,lon point of open sea' using errcode = 'P0001';
    end if;
    if t[i] ~ '^-?[0-9]+(\.[0-9]+)?,-?[0-9]+(\.[0-9]+)?$' then
      v_args := jsonb_build_object('dest_point', jsonb_build_object(
                  'lat', split_part(t[i], ',', 1)::numeric,
                  'lon', split_part(t[i], ',', 2)::numeric));
      if abs((v_args->'dest_point'->>'lat')::numeric) > 90
         or abs((v_args->'dest_point'->>'lon')::numeric) > 180 then
        raise exception 'E_PARSE: "%" is not a point on the sphere', t[i] using errcode = 'P0001';
      end if;
    else
      v_args := jsonb_build_object('dest', cmd.resolve_port(t[i]));
    end if;
    i := i + 1;
    if i <= n then
      raise exception 'E_PARSE: SAIL takes one destination; "%" was left over', t[i] using errcode = 'P0001';
    end if;
$psn$);

select pg_temp.recut('cmd.verb_schema()'::regprocedure, false,
  $vso$    {"verb":"SAIL","args":[
       {"name":"fleet","type":"fleet","required":false},
       {"name":"dest","type":"port","required":true,"keyword":"TO"},
       {"name":"via","type":"port","required":false,"repeat":true,"keyword":"VIA"}],
     "help":"Put to sea and make for another port.",
     "note":"She follows the sea road, which runs longer than the line on the map. Name ports to call at on the way and she puts in at each in turn."},$vso$,
  $vsn$    {"verb":"SAIL","args":[
       {"name":"fleet","type":"fleet","required":false},
       {"name":"dest","type":"place","required":true,"keyword":"TO"}],
     "help":"Put to sea and make for a harbour or any point of open water.",
     "note":"She sails the fastest way the water allows, plotted on the chart when the order is given. Pick a harbour, or pinpoint the open sea on the map."},$vsn$);

select pg_temp.recut('world.snapshot()'::regprocedure, false,
  $sno$    'legs', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', l.id, 'from', a.code, 'to', b.code, 'nm', l.distance_nm,
        'hazard_mult', l.hazard_mult, 'notes', l.notes) order by a.code, b.code), '[]'::jsonb)
      from public.legs l join public.ports a on a.id = l.from_port_id
                         join public.ports b on b.id = l.to_port_id),
$sno$,
  $snn$    -- 0047: the 782-leg graph is gone from the wire. What water connects to what is the raster
    -- (world.sea_raster) and the sailed distances (world.reach); a lane layer drawn from legs was
    -- one of the four defects the free sea replaces (lanes across continents).
$snn$);

select pg_temp.recut('world.fleets()'::regprocedure, false,
  $fpo$    'port', (select code from public.ports where id = f.port_id),$fpo$,
  $fpn$    'port', (select code from public.ports where id = f.port_id),
    'anchor', case when f.lat is not null then jsonb_build_array(f.lat, f.lon) end,$fpn$,
  $fvo$    'voyage', (select jsonb_build_object(
                 'id', v.id, 'to', (select code from public.ports where id = v.dest_port_id),
                 'eta', v.eta, 'total_nm', v.total_nm,
                 'nm_done', voyage.progress_nm(v.id),
                 'position', (select to_jsonb(pos) from voyage.position(v.id) pos))
                 from public.voyages v where v.fleet_id = f.id and v.status = 'SAILING'),$fvo$,
  $fvn$    'voyage', (select jsonb_build_object(
                 'id', v.id, 'to', (select code from public.ports where id = v.dest_port_id),
                 -- 0047: the destination may be a bare point of water, and THE WHOLE COURSE is
                 -- served — the chart draws the polyline she actually sails, never a straight
                 -- line of its own (the served path IS the drawn path; src/chart/route.ts).
                 'dest_point', case when v.dest_port_id is null
                                    then v.path->(jsonb_array_length(v.path)-1)->'b' end,
                 'course', voyage.course_of(v.path),
                 'eta', v.eta, 'total_nm', v.total_nm,
                 'nm_done', voyage.progress_nm(v.id),
                 'position', (select to_jsonb(pos) from voyage.position(v.id) pos))
                 from public.voyages v where v.fleet_id = f.id and v.status = 'SAILING'),$fvn$);

-- ── 13. The recuts that change a signature: drop, edit the live body, recreate, re-grant ───────
select pg_temp.recut('cmd.issue(uuid, text, int)'::regprocedure, true,
  $is0$FUNCTION cmd.issue(p_fleet uuid, p_text text, p_expected_version integer DEFAULT NULL::integer)$is0$,
  $is1$FUNCTION cmd.issue(p_fleet uuid, p_text text, p_expected_version integer DEFAULT NULL::integer, p_path jsonb DEFAULT NULL::jsonb)$is1$,
  $is2$  if v_parsed->>'verb' = 'CANCEL' then$is2$,
  $is3$  -- 0047: a SAIL may carry the proposed course. It rides in the ARGS — the order may execute
  -- later, from the queue — and the server verifies it at EXECUTION, against its own raster,
  -- never at issue: what matters is the water at the moment she sails.
  if v_parsed->>'verb' = 'SAIL' and p_path is not null and jsonb_typeof(p_path) = 'array' then
    v_parsed := jsonb_set(v_parsed, '{args,path}', p_path);
  end if;

  if v_parsed->>'verb' = 'CANCEL' then$is3$);
revoke all on function cmd.issue(uuid, text, int, jsonb) from public, anon;
grant execute on function cmd.issue(uuid, text, int, jsonb) to authenticated;

select pg_temp.recut('cmd.preview(uuid, text)'::regprocedure, true,
  $pv0$FUNCTION cmd.preview(p_fleet uuid, p_text text)$pv0$,
  $pv1$FUNCTION cmd.preview(p_fleet uuid, p_text text, p_path jsonb DEFAULT NULL::jsonb)$pv1$,
  $pv2$  if v_parsed->>'verb' in ('CANCEL', 'CLEAR') then$pv2$,
  $pv3$  if v_parsed->>'verb' = 'SAIL' and p_path is not null and jsonb_typeof(p_path) = 'array' then
    v_parsed := jsonb_set(v_parsed, '{args,path}', p_path);
  end if;

  if v_parsed->>'verb' in ('CANCEL', 'CLEAR') then$pv3$,
  $pv4$  if (select status from public.fleets where id = (v_parsed->>'fleet_id')::uuid) <> 'DOCKED' then$pv4$,
  $pv5$  if (select status from public.fleets where id = (v_parsed->>'fleet_id')::uuid) not in ('DOCKED', 'ANCHORED') then$pv5$);
revoke all on function cmd.preview(uuid, text, jsonb) from public, anon;
grant execute on function cmd.preview(uuid, text, jsonb) to authenticated;

select pg_temp.recut('world.trade_routes(uuid, uuid, int, int, uuid)'::regprocedure, true,
  $tr0$FUNCTION world.trade_routes(p_from uuid, p_fleet uuid DEFAULT NULL::uuid, p_max_legs integer DEFAULT NULL::integer, p_limit integer DEFAULT NULL::integer, p_to uuid DEFAULT NULL::uuid)$tr0$,
  $tr1$FUNCTION world.trade_routes(p_from uuid, p_fleet uuid DEFAULT NULL::uuid, p_radius_nm numeric DEFAULT NULL::numeric, p_limit integer DEFAULT NULL::integer, p_to uuid DEFAULT NULL::uuid)$tr1$,
  $tr2$  v_legs    int     := greatest(1, coalesce(p_max_legs, public.wc_int('route_scan_max_legs')));$tr2$,
  $tr3$  v_radius  numeric := greatest(1, coalesce(p_radius_nm, public.wc_num('sea_scan_radius_nm')));$tr3$,
  $tr4$    select r.port_id, r.nm, r.hops
      from voyage.reach_from(p_from, case when p_to is null then v_ports else null end) r
     where (case when p_to is null then (r.hops between 1 and v_legs)
                 else (r.port_id = p_to) end)
       -- A DESTINATION THIS FLEET COULD NOT SAIL TO IS NOT A RECOMMENDATION. The gate is
       -- voyage.sail_refusal — the SAME authority cmd.do_sail raises from — so the quay cannot
       -- name a port the order would refuse. Applied only when she is lying here: a fleet at sea
       -- has no current sailing to judge, so the scan falls back to the stated default basis.
       -- The gate is her CURRENT lading: taking cargo aboard slows her, so a route within a few
       -- per cent of her endurance can still be refused once loaded (see the header).
       and (v_basis <> 'fleet' or voyage.sail_refusal(p_fleet, r.port_id, r.nm) is null)
$tr4$,
  $tr5$    -- 0047: the reach is the SAILED DISTANCE TABLE (sea_reaches, derived from the raster by the
    -- one pathfinder), not the leg graph. "Two legs out" becomes a radius in nautical miles —
    -- sea_scan_radius_nm defaults to 1,700, the measured median horizon of the old 2-leg scan
    -- across all 214 harbours — and the gate is the same one authority cmd.do_sail raises from.
    select y.port_id, y.nm
      from (select r.port_id, r.nm
              from voyage.reach_from(p_from) r
              join public.ports dp on dp.id = r.port_id and dp.kind = 'HARBOUR'
             where (p_to is null and r.nm <= v_radius) or (r.port_id = p_to)
             order by r.nm, r.port_id
             limit v_ports) y
     where (v_basis <> 'fleet' or voyage.sail_refusal(p_fleet, y.port_id, null, y.nm) is null)
$tr5$,
  $tr6$    select h.good_id, rc.port_id, rc.nm, rc.hops, h.mid as mid_here,$tr6$,
  $tr7$    select h.good_id, rc.port_id, rc.nm, h.mid as mid_here,$tr7$,
  $tr8$    select m.good_id, m.port_id, m.nm, m.hops, m.mid_there - m.mid_here as gap,$tr8$,
  $tr9$    select m.good_id, m.port_id, m.nm, m.mid_there - m.mid_here as gap,$tr9$,
  $tr10$    select p.good_id, p.port_id, p.nm, p.hops
      from pairs p$tr10$,
  $tr11$    select p.good_id, p.port_id, p.nm
      from pairs p$tr11$,
  $tr12$    select k.good_id, k.port_id, k.nm, k.hops,$tr12$,
  $tr13$    select k.good_id, k.port_id, k.nm,$tr13$,
  $tr14$             'nm', b.nm, 'legs', b.hops,$tr14$,
  $tr15$             'nm', b.nm,$tr15$,
  $tr16$       'max_legs', case when p_to is null then v_legs else null end,$tr16$,
  $tr17$       'radius_nm', case when p_to is null then v_radius else null end,$tr17$);
revoke all on function world.trade_routes(uuid, uuid, numeric, int, uuid) from public, anon;
grant execute on function world.trade_routes(uuid, uuid, numeric, int, uuid) to authenticated;

-- ── 14. THE HELM ORDER AT SEA: she turns where she is ──────────────────────────────────────────
create or replace function cmd.divert(p_fleet uuid, p_dest uuid, p_dest_point jsonb, p_path jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
-- Supersedes 0037's node-turn body (dropped above). Under the free sea she turns AT HER CLOSED-
-- FORM POSITION: the sailing voyage is truncated there and settled through the ONE arrival arm
-- (she comes to anchor at the cut point), the queue composed for the old market is cleared
-- (0037's rule kept), and the onward passage is a plain SAIL through the ONE parser and the ONE
-- mover, from the very point she holds. What has happened stays happened: kept segments are
-- byte-identical, settled days keep their PK, and the onward water is a NEW voyage.
--
-- THE BRIDGE: the client plotted from the position it last READ, and at 1 real minute = 8 sim
-- hours she has moved since. Rather than refuse honest staleness — or teleport her onto the
-- course — her TRUE position is prepended when the course starts more than course_join_nm away,
-- and the bridging water is then verified like all the rest: a cape she rounded between reads
-- refuses the divert instead of sailing her back through it.
declare
  v_player uuid := public.current_player_id();
  v_now    timestamptz := now();
  f  public.fleets%rowtype;
  v  public.voyages%rowtype;
  pos record;
  v_dest_c text;
  v_token  text;
  v_keep   jsonb := '[]'::jsonb;
  v_prof   jsonb := '[]'::jsonb;
  v_acc    numeric := 0;
  v_pnm    numeric;
  i        int := 0;
  e        jsonb;
  v_eta    timestamptz;
  v_issue  jsonb;
  v_course jsonb;
begin
  select * into f from public.fleets where id = p_fleet;
  if f.id is null or v_player is null or f.player_id <> v_player then
    return jsonb_build_object('ok', false, 'error_code', 'E_NO_SUCH_FLEET',
      'error_message', 'That fleet is not yours.', 'fixes', '[]'::jsonb);
  end if;

  -- Catch up first: an act must not reason about a stale position (D.2).
  perform voyage.settle(p_fleet, v_now);
  select * into f from public.fleets where id = p_fleet;
  if f.status <> 'SAILING' then
    return jsonb_build_object('ok', false, 'error_code', 'E_NOT_SAILING',
      'error_message', format('%s is %s, not under way - from a quay, SAIL is the order.', f.name, f.status),
      'fixes', jsonb_build_array(format('SAIL %s TO <the new port>', f.name)));
  end if;

  if p_dest is not null then
    select code into v_dest_c from public.ports where id = p_dest;
    if v_dest_c is null then
      return jsonb_build_object('ok', false, 'error_code', 'E_NO_SUCH_PORT',
        'error_message', 'There is no such port to make for.', 'fixes', '[]'::jsonb);
    end if;
    v_token := v_dest_c;
  elsif p_dest_point is not null
        and jsonb_typeof(p_dest_point->'lat') = 'number' and jsonb_typeof(p_dest_point->'lon') = 'number' then
    v_token := format('%s,%s', round((p_dest_point->>'lat')::numeric, 4), round((p_dest_point->>'lon')::numeric, 4));
    v_dest_c := v_token;
  else
    return jsonb_build_object('ok', false, 'error_code', 'E_NO_SUCH_PORT',
      'error_message', 'Name a port, or a point of open sea.', 'fixes', '[]'::jsonb);
  end if;

  select * into v from public.voyages where fleet_id = p_fleet and status = 'SAILING' for update;
  if p_dest is not null and v.dest_port_id = p_dest then
    return jsonb_build_object('ok', false, 'error_code', 'E_SAME_DEST',
      'error_message', format('%s is already bound for %s.', f.name,
        (select name from public.ports where id = p_dest)),
      'fixes', '[]'::jsonb);
  end if;

  select * into pos from voyage.position(v.id, v_now);

  -- the queue was composed for another market (0037's rule, kept) - and it is cleared BEFORE
  -- she comes to rest, or the arrival arm's own queue-run would depart her on a stale order
  -- in the very same act (found by this file's probe: a pending SAIL took her straight back
  -- out of the anchor before the onward order could be issued).
  perform cmd.clear(p_fleet);

  if pos.nm_done < 1 then
    -- She has barely left: the voyage is unmade whole rather than truncated to nothing
    -- (total_nm must stay > 0). She stands again exactly where she departed.
    update public.voyages set status = 'ABORTED' where id = v.id;
    if v.origin_port_id is not null then
      update public.fleets set status = 'DOCKED', port_id = v.origin_port_id, lat = null, lon = null,
             version = version + 1 where id = p_fleet;
    else
      update public.fleets set status = 'ANCHORED', port_id = null,
             lat = (v.path->0->'a'->>0)::numeric, lon = (v.path->0->'a'->>1)::numeric,
             version = version + 1 where id = p_fleet;
    end if;
  else
    -- Truncate at her position: kept segments byte-identical, the one under her keel cut AT the
    -- point, the unsailed tail gone. total = exactly her progress, so the recomputed ETA is the
    -- instant she holds, and the settle below arrives her THROUGH the one arrival arm.
    for e in select * from jsonb_array_elements(v.path) loop
      exit when i > pos.seg_index;
      if i < pos.seg_index then
        v_keep := v_keep || e;
        v_prof := v_prof || (v.speed_profile->i);
        v_acc  := v_acc + (e->>'nm')::numeric;
      else
        v_pnm := round(pos.nm_done - v_acc, 2);
        if v_pnm > 0 then
          v_keep := v_keep || (e || jsonb_build_object('b', jsonb_build_array(pos.lat, pos.lon), 'nm', v_pnm));
          v_prof := v_prof || (v.speed_profile->i);
        end if;
      end if;
      i := i + 1;
    end loop;
    update public.voyages
       set path = v_keep, speed_profile = v_prof,
           total_nm = (select sum((s->>'nm')::numeric) from jsonb_array_elements(v_keep) s),
           dest_port_id = null
     where id = v.id;
    v_eta := voyage.recompute_eta(v.id);
    perform voyage.settle(p_fleet, greatest(v_now, v_eta));
  end if;

  select * into f from public.fleets where id = p_fleet;
  if f.status not in ('DOCKED', 'ANCHORED') then
    raise exception 'E_DIVERT_FAILED: she did not come to rest at the turn (status %)', f.status using errcode = 'P0001';
  end if;

  -- the bridge, then the onward passage through the ONE parser and the ONE mover
  v_course := p_path;
  if v_course is not null and jsonb_typeof(v_course) = 'array' and jsonb_array_length(v_course) >= 1
     and f.lat is not null
     and voyage.gc_distance_nm(f.lat::float8, f.lon::float8,
           (v_course->0->>0)::float8, (v_course->0->>1)::float8) > public.wc_num('course_join_nm') then
    v_course := jsonb_build_array(jsonb_build_array(f.lat, f.lon)) || v_course;
  end if;
  v_issue := cmd.issue(p_fleet, 'SAIL TO ' || v_token, null, v_course);
  if coalesce(v_issue->>'ok', 'false') <> 'true' then
    -- 7C: a half-made turn (voyage truncated, no onward order) is not an acceptable else.
    -- Raising rolls the WHOLE act back, truncation included; a refused divert changes nothing.
    raise exception 'E_DIVERT_FAILED: the onward order was refused - %',
      coalesce(v_issue->>'error_message', 'no reason given') using errcode = 'P0001';
  end if;

  perform public.emit_event(f.player_id, 'DIVERTED', jsonb_build_object(
    'fleet', f.name, 'voyage_id', v.id,
    'at', format('%s,%s', round(pos.lat, 4), round(pos.lon, 4)),
    'was', coalesce((select code from public.ports where id = v.dest_port_id), 'open sea'),
    'now', v_dest_c, 'queue_cleared', true));

  return jsonb_build_object('ok', true,
    'at', format('%s,%s', round(pos.lat, 4), round(pos.lon, 4)),
    'was', coalesce((select code from public.ports where id = v.dest_port_id), 'open sea'),
    'dest', v_dest_c, 'queue', cmd.queue(p_fleet));
end $$;

comment on function cmd.divert(uuid, uuid, jsonb, jsonb) is
  'THE helm order at sea (0047): truncate the sailing voyage at her closed-form position, settle '
  'her to anchor through the one arrival arm, clear the stale queue, and depart the onward '
  'passage through the one parser and the one mover — bridged to her true position and verified '
  'as water like every other course. Supersedes 0037''s node turn.';

revoke all on function cmd.divert(uuid, uuid, jsonb, jsonb) from public, anon;
grant execute on function cmd.divert(uuid, uuid, jsonb, jsonb) to authenticated;

-- ── 15. The reads the free sea needs ───────────────────────────────────────────────────────────
create or replace function world.sea_raster()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- The one raster, served whole (~346 KB of base64, fetched once per session and cached): the
  -- client's pathfinder PROPOSES over exactly the water the server judges by, because both hold
  -- this row. Lying about it gains nothing - the server re-samples every course it is sent.
  select jsonb_build_object('cols', r.cols, 'rows', r.rows, 'cell_deg', r.cell_deg,
                            'bits_per_cell', r.bits_per_cell,
                            'cells_base64', replace(encode(r.cells, 'base64'), e'\n', ''))
    from public.sea_raster r where r.id = 1
$$;

revoke all on function world.sea_raster() from public, anon;
grant execute on function world.sea_raster() to authenticated;

create or replace function world.reach(p_from uuid)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- One place's sailed distances to everywhere: the SAIL picker's ordering and figures, priced
  -- by the same table the trade scan and the endurance gate read.
  select jsonb_build_object('from', sr.code, 'snap_nm', sr.snap_nm, 'reaches', sr.reaches)
    from public.sea_reaches sr where sr.port_id = p_from
$$;

revoke all on function world.reach(uuid) from public, anon;
grant execute on function world.reach(uuid) to authenticated;

-- ── 16. The client entry points — re-cut whole (supersedes 0037's) ─────────────────────────────
-- Changed rows only: issue/preview gain p_path, divert takes (dest, dest_point, path),
-- trade_routes' third argument is a radius in nm, and the two free-sea reads join the list.
create or replace function public.client_rpc_entry_points()
returns table (schema_name text, function_name text, arg_types text, fn regprocedure)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select t.s, t.f, t.a,
         to_regprocedure(format('%I.%I(%s)', t.s, t.f, t.a))
    from (values
      -- the reads (world)
      ('world'::text, 'snapshot'::text,      ''::text),
      ('world',       'market',              'uuid'),
      ('world',       'fleets',              ''),
      ('world',       'ledger',              'timestamptz, int'),
      ('world',       'buy_capacity',        'uuid, uuid'),
      ('world',       'price_history',       'uuid, int'),
      ('world',       'player',              ''),
      ('world',       'officers',            ''),
      ('world',       'skills',              ''),
      ('world',       'trade_routes',        'uuid, uuid, numeric, int, uuid'),
      ('world',       'haggle_state',        'uuid, uuid'),
      ('world',       'standings',           'int'),
      ('world',       'buffs',               'uuid'),
      ('world',       'provision_presets',   ''),
      -- 0047: the free sea. The raster the client searches, and one place's sailed distances.
      ('world',       'sea_raster',          ''),
      ('world',       'reach',               'uuid'),
      -- the orders (cmd)
      ('cmd',         'issue',               'uuid, text, int, jsonb'),
      ('cmd',         'preview',             'uuid, text, jsonb'),
      ('cmd',         'cancel_at',           'uuid, int'),
      ('cmd',         'clear',               'uuid, boolean'),
      ('cmd',         'verb_schema',         ''),
      ('cmd',         'hire_officer',        'text, uuid'),
      ('cmd',         'post_officer',        'text, uuid'),
      ('cmd',         'study_skill',         'text, uuid'),
      ('cmd',         'found_house',         'text, text'),
      ('cmd',         'haggle',              'uuid, uuid, text'),
      ('cmd',         'provision_preset_save',   'uuid, text, int'),
      ('cmd',         'provision_preset_delete', 'uuid'),
      ('cmd',         'provision_preset_apply',  'uuid, uuid'),
      -- 0047: the helm order at sea - turn where she is, for a port or a bare point of water.
      ('cmd',         'divert',              'uuid, uuid, jsonb, jsonb')
    ) as t(s, f, a)
$$;

-- ── 17. THE LAND GUARD: every stored course, walked ────────────────────────────────────────────
create or replace function voyage.assert_paths_water()
returns table (voyages_walked int, legacy_skipped int)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
-- Walks EVERY stored voyage path at sub-cell intervals through THE one sampler
-- (voyage.path_refusal) and raises on the first sample that is not open water — the owner's law
-- ("i don't want the fleet to ever touch land"), PROVEN rather than intended. Legacy-converted
-- paths (straight port-to-port lines, the old model's shape) are counted and skipped, never
-- silently. Non-vacuity is the CALLER's duty: 0047's probe and proof 08 assert voyages_walked
-- is not zero AND prove the guard bites by feeding it a straight line across Iberia.
declare
  v public.voyages%rowtype;
  v_course jsonb;
  v_ref text;
  v_head numeric;
  v_tail numeric;
  n_walked int := 0;
  n_legacy int := 0;
begin
  for v in select * from public.voyages loop
    if v.path->0 ? 'legacy' then
      n_legacy := n_legacy + 1;
      continue;
    end if;
    v_course := voyage.course_of(v.path);
    -- the same allowances the mover granted: a port's measured snap, or — for an open-water
    -- end — the point's own measured snap (a divert can lawfully cut a course inside a port's
    -- approach, and the guard must judge by the rule the voyage was admitted under).
    v_head := coalesce((select sr.snap_nm from public.sea_reaches sr where sr.port_id = v.origin_port_id),
                       voyage.water_snap_nm((v_course->0->>0)::numeric, (v_course->0->>1)::numeric)) + 25;
    v_tail := coalesce((select sr.snap_nm from public.sea_reaches sr where sr.port_id = v.dest_port_id),
                       voyage.water_snap_nm((v_course->(jsonb_array_length(v_course)-1)->>0)::numeric,
                                            (v_course->(jsonb_array_length(v_course)-1)->>1)::numeric)) + 25;
    v_ref := voyage.path_refusal(v_course,
               (v_course->0->>0)::numeric, (v_course->0->>1)::numeric,
               (v_course->(jsonb_array_length(v_course)-1)->>0)::numeric,
               (v_course->(jsonb_array_length(v_course)-1)->>1)::numeric,
               1, v_head, v_tail);
    if v_ref is not null then
      raise exception 'LAND GUARD: voyage % (% -> %) fails the water law: %',
        v.id,
        coalesce((select code from public.ports where id = v.origin_port_id), 'open sea'),
        coalesce((select code from public.ports where id = v.dest_port_id), 'open sea'),
        v_ref;
    end if;
    n_walked := n_walked + 1;
  end loop;
  voyages_walked := n_walked;
  legacy_skipped := n_legacy;
  return next;
end $$;

revoke all on function voyage.assert_paths_water() from public, anon, authenticated;

comment on function voyage.assert_paths_water() is
  'THE land guard (0047): walks every stored voyage course at sub-cell intervals through '
  'voyage.path_refusal and raises on the first land sample. Callers must assert voyages_walked '
  '> 0 - a guard over an empty set is decoration - and proof 08 break-tests it on every run.';

-- ── SELF-ASSERT ────────────────────────────────────────────────────────────────────────────────
do $$
declare
  c_probe  constant uuid := '00000000-0047-4000-8000-000000000001';
  c_other  constant uuid := '00000000-0047-4000-8000-000000000002';
  v_course_cad  constant jsonb := '[[38.71,-9.14],[36.875,-9.125],[36.625,-8.875],[36.53,-6.3]]'::jsonb;
  v_course_home constant jsonb := '[[36.53,-6.3],[36.625,-8.875],[36.875,-9.125],[38.71,-9.14]]'::jsonb;
  v_course_pt   constant jsonb := '[[38.71,-9.14],[33,-15]]'::jsonb;
  v_course_back constant jsonb := '[[33,-15],[38.71,-9.14]]'::jsonb;
  v_course_sal  constant jsonb := '[[38.71,-9.14],[-9.625,-35.125],[-12.625,-37.875],[-12.98,-38.49]]'::jsonb;
  v_course_turn constant jsonb := '[[36.875,-9.125],[36.625,-8.875],[36.53,-6.3]]'::jsonb;
  v_straight_bcn constant jsonb := '[[38.71,-9.14],[41.38,2.18]]'::jsonb;
  v_lis uuid; v_cad uuid; v_sal uuid; v_bcn uuid; v_pdl uuid;
  v_player uuid; v_other uuid; v_fleet uuid;
  v_res jsonb; v_fpay jsonb; v_routes jsonb;
  v public.voyages%rowtype;
  v_voyage uuid; v_old_total numeric; v_seg0 jsonb;
  v_land_msg text; v_guard_msg text;
  v_nm numeric; v_reach numeric; v_n int; v_i int;
  v_leg record; v_conv uuid; v_sim0 numeric; v_sim1 numeric;
  g record;
  v_good text;
begin
  select id into v_lis from public.ports where code = 'LIS';
  select id into v_cad from public.ports where code = 'CAD';
  select id into v_sal from public.ports where code = 'SLV';
  select id into v_bcn from public.ports where code = 'BAR';
  select id into v_pdl from public.ports where code = 'PON';
  select code into v_good from public.goods order by code limit 1;

  begin
    v_player := public.new_house(c_probe, 'Casa do Mar Livre', 'PRT');
    perform cmd.assume_identity(c_probe);
    select id into v_fleet from public.fleets where player_id = v_player;
    -- the probe owns its preconditions: watered, fed, fully crewed (README section 3)
    perform cmd.do_provision(v_fleet, jsonb_build_object('mode', 'FULL'));
    perform cmd.do_hire(v_fleet, jsonb_build_object('count',
      (select c.crew_max - sh.crew from public.ships sh
         join public.ship_classes c on c.id = sh.class_id where sh.fleet_id = v_fleet)));

    -- (a) THE LAW BITES THROUGH THE ONE ENTRY: a straight course across Iberia is refused E_LAND.
    v_res := cmd.issue(v_fleet, 'SAIL TO BAR', null, v_straight_bcn);
    if v_res->>'error_code' is distinct from 'E_LAND' then
      raise exception '0047 self-assert FAIL: a straight Lisbon-Barcelona course through cmd.issue was not refused E_LAND (got [%: %])',
        v_res->>'error_code', v_res->>'error_message';
    end if;
    v_land_msg := v_res->>'error_message';
    perform cmd.clear(v_fleet);

    -- (b) NO COURSE, NO GUESS: Lisbon-Cadiz straight is not water, so an unplotted SAIL refuses
    v_res := cmd.issue(v_fleet, 'SAIL TO CAD');
    if v_res->>'error_code' is distinct from 'E_NO_COURSE' then
      raise exception '0047 self-assert FAIL: an unplotted SAIL round a cape was not refused E_NO_COURSE (got [%])', v_res->>'error_code';
    end if;
    perform cmd.clear(v_fleet);

    -- (c) a course that joins the wrong water is refused as itself
    v_res := cmd.issue(v_fleet, 'SAIL TO CAD', null, v_course_pt);
    if v_res->>'error_code' is distinct from 'E_OFF_COURSE' then
      raise exception '0047 self-assert FAIL: a course ending 500 nm from the destination was not refused E_OFF_COURSE (got [%])', v_res->>'error_code';
    end if;
    perform cmd.clear(v_fleet);

    -- (d) THE MOVER: the real water course departs her, measured by the server
    v_res := cmd.issue(v_fleet, 'SAIL TO CAD', null, v_course_cad);
    if coalesce(v_res->>'ok', 'false') <> 'true' then
      raise exception '0047 self-assert FAIL: the real Lisbon-Cadiz course was refused: [%: %]',
        v_res->>'error_code', v_res->>'error_message';
    end if;
    select * into v from public.voyages where fleet_id = v_fleet and status = 'SAILING';
    select sum((s->>'nm')::numeric) into v_nm from jsonb_array_elements(v.path) s;
    select (reaches->>'CAD')::numeric into v_reach from public.sea_reaches where code = 'LIS';
    if abs(v.total_nm - v_nm) > 0.05 then
      raise exception '0047 self-assert FAIL: total_nm % is not the sum of its own segments %', v.total_nm, v_nm;
    end if;
    if abs(v.total_nm - v_reach) > v_reach * 0.03 then
      raise exception '0047 self-assert FAIL: the sailed course measures % nm but the reach table quotes % - the quay and the water disagree', v.total_nm, v_reach;
    end if;
    if jsonb_array_length(v.speed_profile) <> jsonb_array_length(v.path)
       or v.origin_port_id <> v_lis or v.dest_port_id <> v_cad then
      raise exception '0047 self-assert FAIL: the voyage row is misshapen (profile %, path %, origin %, dest %)',
        jsonb_array_length(v.speed_profile), jsonb_array_length(v.path), v.origin_port_id, v.dest_port_id;
    end if;
    if voyage.progress_nm(v.id, v.departed_at) <> 0
       or voyage.progress_nm(v.id, v.eta) < v.total_nm - 0.01 then
      raise exception '0047 self-assert FAIL: progress is not closed-form over the new path shape';
    end if;

    -- (e) THE WIRE: the whole course, the anchorless position, the destination code
    select f into v_fpay from jsonb_array_elements(world.fleets()) f where f->>'id' = v_fleet::text;
    if jsonb_array_length(v_fpay->'voyage'->'course') <> jsonb_array_length(v.path) + 1
       or v_fpay->'voyage'->>'to' is distinct from 'CAD'
       or (v_fpay->'voyage'->'position'->>'lat') is null
       or (v_fpay->'voyage'->'position'->>'lon') is null then
      raise exception '0047 self-assert FAIL: world.fleets does not serve the course and the position (voyage payload: %)', v_fpay->'voyage';
    end if;

    -- (f) THE QUEUE CARRIES ON ACROSS AN ARRIVAL: a homeward SAIL queued at sea departs itself
    v_res := cmd.issue(v_fleet, 'SAIL TO LIS', null, v_course_home);
    if (select count(*) from public.orders where fleet_id = v_fleet and status = 'pending') <> 1 then
      raise exception '0047 self-assert FAIL: the homeward SAIL did not queue while she was at sea';
    end if;
    v_i := 0;
    while (select status from public.fleets where id = v_fleet) <> 'DOCKED' and v_i < 20 loop
      update public.voyages set departed_at = departed_at - interval '600 hours', eta = eta - interval '600 hours'
       where fleet_id = v_fleet and status = 'SAILING';
      perform voyage.settle(v_fleet);
      v_i := v_i + 1;
      exit when (select port_id from public.fleets where id = v_fleet) = v_lis;
    end loop;
    if (select port_id from public.fleets where id = v_fleet) is distinct from v_lis then
      raise exception '0047 self-assert FAIL: the queued homeward SAIL did not carry her back to LIS (at %, status %)',
        (select coalesce(p.code, 'nowhere') from public.fleets fl left join public.ports p on p.id = fl.port_id where fl.id = v_fleet),
        (select status from public.fleets where id = v_fleet);
    end if;
    perform cmd.do_provision(v_fleet, jsonb_build_object('mode', 'FULL'));

    -- (g) PINPOINT: any water point is a destination, and she ANCHORS there
    v_res := cmd.issue(v_fleet, 'SAIL TO 33,-15', null, v_course_pt);
    if coalesce(v_res->>'ok', 'false') <> 'true' then
      raise exception '0047 self-assert FAIL: the pinpoint SAIL was refused: [%: %]', v_res->>'error_code', v_res->>'error_message';
    end if;
    select * into v from public.voyages where fleet_id = v_fleet and status = 'SAILING';
    if v.dest_port_id is not null then
      raise exception '0047 self-assert FAIL: a pinpoint voyage minted a destination port';
    end if;
    update public.voyages set departed_at = departed_at - interval '600 hours', eta = eta - interval '600 hours'
     where id = v.id;
    perform voyage.settle(v_fleet);
    if (select status from public.fleets where id = v_fleet) <> 'ANCHORED'
       or (select lat from public.fleets where id = v_fleet) <> 33
       or (select lon from public.fleets where id = v_fleet) <> -15 then
      raise exception '0047 self-assert FAIL: she did not come to ANCHOR at 33,-15 (status %, lat %, lon %)',
        (select status from public.fleets where id = v_fleet),
        (select lat from public.fleets where id = v_fleet),
        (select lon from public.fleets where id = v_fleet);
    end if;
    if not exists (select 1 from public.events ev where ev.player_id = v_player and ev.kind = 'VOYAGE_REPORT'
                    and ev.payload->'to' = 'null'::jsonb and ev.payload->'to_point' = '[33, -15]'::jsonb) then
      raise exception '0047 self-assert FAIL: the open-water arrival report does not carry the point (no to_point [33,-15])';
    end if;
    -- the quay verbs refuse her at anchor, as themselves
    v_res := cmd.issue(v_fleet, format('BUY %s 1', v_good));
    if v_res->>'error_code' is distinct from 'E_NOT_DOCKED' then
      raise exception '0047 self-assert FAIL: BUY at open anchor was not refused E_NOT_DOCKED (got [%])', v_res->>'error_code';
    end if;
    perform cmd.clear(v_fleet);

    -- (h) ...and she can always leave: home from the anchor, through the same one mover
    v_res := cmd.issue(v_fleet, 'SAIL TO LIS', null, v_course_back);
    if coalesce(v_res->>'ok', 'false') <> 'true' then
      raise exception '0047 self-assert FAIL: the SAIL home from open anchor was refused: [%: %]', v_res->>'error_code', v_res->>'error_message';
    end if;
    select * into v from public.voyages where fleet_id = v_fleet and status = 'SAILING';
    if v.origin_port_id is not null then
      raise exception '0047 self-assert FAIL: a voyage from open anchor minted an origin port';
    end if;
    update public.voyages set departed_at = departed_at - interval '600 hours', eta = eta - interval '600 hours'
     where id = v.id;
    perform voyage.settle(v_fleet);
    if (select port_id from public.fleets where id = v_fleet) is distinct from v_lis then
      raise exception '0047 self-assert FAIL: she did not dock home from the anchor';
    end if;

    -- (i) THE ONE-WAY TRAP IS REFUSED: thin stores cannot buy a passage to nowhere
    update public.ships set water_t = 1, food_t = 1 where fleet_id = v_fleet;
    v_res := cmd.issue(v_fleet, 'SAIL TO 33,-15', null, v_course_pt);
    if v_res->>'error_code' is distinct from 'E_ENDURANCE'
       or position('round trip' in coalesce(v_res->>'error_message', '')) = 0 then
      raise exception '0047 self-assert FAIL: a thin-stores pinpoint SAIL was not refused for the ROUND TRIP (got [%: %])',
        v_res->>'error_code', v_res->>'error_message';
    end if;
    perform cmd.clear(v_fleet);
    perform cmd.do_provision(v_fleet, jsonb_build_object('mode', 'FULL'));

    -- (j) THE HELM: she turns where she is. The probe owns its preconditions (README section 3):
    -- the passages behind her may have cost crew, hull and coin to the dice, and a slower,
    -- thirstier fleet was refused this 3,500 nm passage on some runs and not others. The helm
    -- test is about the TURN, not the larder or the surgeon, so she is made whole first.
    update public.ships s set crew = c.crew_max, durability = c.durability
      from public.ship_classes c where c.id = s.class_id and s.fleet_id = v_fleet;
    update public.players set ducats = 8000 where id = v_player;
    -- stores are SET, not bought: do_provision(FULL) raises E_HOLD_FULL when the casks are
    -- already topped, and whether they are depends on the run's dice. 45 crew-days of each is
    -- deterministic and comfortably clears the 3,500 nm passage's margin.
    update public.ships s
       set water_t = round(s.crew * public.wc_num('water_per_crew_day') * 45, 3),
           food_t  = round(s.crew * public.wc_num('food_per_crew_day') * 45, 3)
     where s.fleet_id = v_fleet;
    v_res := cmd.issue(v_fleet, 'SAIL TO SLV', null, v_course_sal);
    if coalesce(v_res->>'ok', 'false') <> 'true' then
      raise exception '0047 self-assert FAIL: the Salvador passage was refused: [%: %]', v_res->>'error_code', v_res->>'error_message';
    end if;
    select * into v from public.voyages where fleet_id = v_fleet and status = 'SAILING';
    v_voyage := v.id; v_old_total := v.total_nm; v_seg0 := v.path->0;
    -- put her ten sim-hours out — DERIVED from time_compression (0045 made it 9600: ten
    -- sim-hours is 3.75 real seconds; at the old 480 it was 75), so this probe cannot break
    -- again the next time the clock changes: mid-first-segment, day 1 unsettled
    update public.voyages set departed_at = departed_at - make_interval(secs => (10 * 3600 / public.wc_num('time_compression'))::double precision),
                              eta = eta - make_interval(secs => (10 * 3600 / public.wc_num('time_compression'))::double precision)
     where id = v_voyage;
    -- something pending, composed for the old destination, so the clearing is provable
    perform cmd.issue(v_fleet, 'SAIL TO PON');
    -- the refusals, while she is under way
    v_res := cmd.divert(v_fleet, v_sal, null, null);
    if v_res->>'error_code' is distinct from 'E_SAME_DEST' then
      raise exception '0047 self-assert FAIL: diverting to her own destination was not E_SAME_DEST (got [%])', v_res->>'error_code';
    end if;
    v_res := cmd.divert(v_fleet, '00000000-0047-4000-8000-00000000dead', null, null);
    if v_res->>'error_code' is distinct from 'E_NO_SUCH_PORT' then
      raise exception '0047 self-assert FAIL: diverting to a made-up port was not E_NO_SUCH_PORT (got [%])', v_res->>'error_code';
    end if;
    v_other := public.new_house(c_other, 'Casa Alheia', 'PRT');
    perform cmd.assume_identity(c_other);
    v_res := cmd.divert(v_fleet, v_cad, null, v_course_turn);
    perform cmd.assume_identity(c_probe);
    if v_res->>'error_code' is distinct from 'E_NO_SUCH_FLEET' then
      raise exception '0047 self-assert FAIL: another captain took her helm (got [%])', coalesce(v_res->>'error_code', 'ok');
    end if;
    -- THE TURN, bridged to her true position and verified as water
    v_res := cmd.divert(v_fleet, v_cad, null, v_course_turn);
    if coalesce(v_res->>'ok', 'false') <> 'true' then
      raise exception '0047 self-assert FAIL: the divert itself was refused: [%: %]', v_res->>'error_code', v_res->>'error_message';
    end if;
    select * into v from public.voyages where id = v_voyage;
    if v.status <> 'ARRIVED' or v.dest_port_id is not null
       or v.total_nm >= v_old_total or v.total_nm < 1
       or v.path->0->'a' is distinct from v_seg0->'a' then
      raise exception '0047 self-assert FAIL: the truncation is wrong (status %, dest %, total % of old %, seg0 moved: %)',
        v.status, v.dest_port_id, v.total_nm, v_old_total, (v.path->0->'a' is distinct from v_seg0->'a');
    end if;
    select * into v from public.voyages where fleet_id = v_fleet and status = 'SAILING';
    if v.id is null or v.id = v_voyage or v.origin_port_id is not null or v.dest_port_id is distinct from v_cad then
      raise exception '0047 self-assert FAIL: the onward passage is not a NEW voyage from her position to CAD';
    end if;
    if voyage.gc_distance_nm((v.path->0->'a'->>0)::float8, (v.path->0->'a'->>1)::float8,
         (select lat from voyage.position(v_voyage, now()))::float8,
         (select lon from voyage.position(v_voyage, now()))::float8) > 20 then
      raise exception '0047 self-assert FAIL: the onward course does not begin where she turned';
    end if;
    if (select count(*) from public.orders where fleet_id = v_fleet and status = 'cancelled' and raw_text = 'SAIL TO PON') <> 1 then
      raise exception '0047 self-assert FAIL: the stale queue was not cleared by the turn';
    end if;
    if not exists (select 1 from public.events ev where ev.player_id = v_player and ev.kind = 'DIVERTED'
                    and ev.payload->>'now' = 'CAD') then
      raise exception '0047 self-assert FAIL: no DIVERTED ledger line names the turn';
    end if;
    update public.voyages set departed_at = departed_at - interval '600 hours', eta = eta - interval '600 hours'
     where fleet_id = v_fleet and status = 'SAILING';
    perform voyage.settle(v_fleet);
    if (select port_id from public.fleets where id = v_fleet) is distinct from v_cad then
      raise exception '0047 self-assert FAIL: the onward passage did not dock her at CAD';
    end if;
    v_res := cmd.divert(v_fleet, v_lis, null, null);
    if v_res->>'error_code' is distinct from 'E_NOT_SAILING' then
      raise exception '0047 self-assert FAIL: a docked fleet answered her helm (got [%])', coalesce(v_res->>'error_code', 'ok');
    end if;

    -- (k) THE CARRY-FORWARD, non-vacuous: an old-shape voyage converts and its schedule holds
    select l.id, l.from_port_id, l.to_port_id, l.distance_nm, l.hazard_mult,
           (select sea_id from public.ports where id = l.to_port_id) as sea_id
      into v_leg
      from public.legs l
     where l.from_port_id = v_lis or l.to_port_id = v_lis
     order by l.distance_nm, l.id limit 1;
    insert into public.voyages (fleet_id, player_id, path, total_nm, speed_profile,
                                departed_at, eta, status, last_settled_day, origin_port_id, dest_port_id)
    values (v_fleet, v_player,
            jsonb_build_array(jsonb_build_object('leg_id', v_leg.id, 'from_id', v_leg.from_port_id,
              'to_id', v_leg.to_port_id, 'nm', v_leg.distance_nm, 'hazard_mult', v_leg.hazard_mult,
              'sea_id', v_leg.sea_id)),
            v_leg.distance_nm, '[4.5]'::jsonb,
            now() - interval '1 day', now() - interval '1 hour', 'ARRIVED', 1,
            v_leg.from_port_id, v_leg.to_port_id)
    returning id into v_conv;
    v_sim0 := voyage.sim_hours(v_conv);
    update public.voyages set path = voyage.convert_leg_path(path) where id = v_conv;
    v_sim1 := voyage.sim_hours(v_conv);
    select * into v from public.voyages where id = v_conv;
    if not (v.path->0 ? 'legacy') or v_sim0 is distinct from v_sim1
       or v.path->0->'a'->>0 is distinct from (select lat::text from public.ports where id = v_leg.from_port_id)
       or v.path->0->>'sea_id' is distinct from v_leg.sea_id::text then
      raise exception '0047 self-assert FAIL: the leg-path conversion changed the contract (legacy %, sim % -> %, a %, sea %)',
        v.path->0 ? 'legacy', v_sim0, v_sim1, v.path->0->'a', v.path->0->>'sea_id';
    end if;

    -- (l) THE LAND GUARD walks the probe's own wake, and BITES on a planted straight line
    select * into g from voyage.assert_paths_water();
    if g.voyages_walked < 4 or g.legacy_skipped < 1 then
      raise exception '0047 self-assert FAIL: the land guard walked % voyage(s) and skipped % legacy - it is asserting over too little to mean anything',
        g.voyages_walked, g.legacy_skipped;
    end if;
    insert into public.voyages (fleet_id, player_id, path, total_nm, speed_profile,
                                departed_at, eta, status, last_settled_day, origin_port_id, dest_port_id)
    values (v_fleet, v_player, voyage.segments_from_course(v_straight_bcn),
            (select sum((s->>'nm')::numeric) from jsonb_array_elements(voyage.segments_from_course(v_straight_bcn)) s),
            '[4.5, 4.5]'::jsonb, now() - interval '1 day', now() - interval '1 hour', 'ARRIVED', 1, v_lis, v_bcn);
    begin
      perform * from voyage.assert_paths_water();
      raise exception '0047 self-assert FAIL: the land guard swallowed a straight Lisbon-Barcelona voyage whole - it cannot catch anything';
    exception when others then
      if sqlerrm like '0047 self-assert FAIL%' then raise; end if;
      v_guard_msg := sqlerrm;
      if position('E_LAND' in v_guard_msg) = 0 then
        raise exception '0047 self-assert FAIL: the land guard refused the planted voyage for the wrong reason: %', v_guard_msg;
      end if;
    end;

    -- (m) THE QUAY AND THE WATER AGREE: every recommended run is priced at the reach table's nm
    perform cmd.assume_identity(c_probe);
    v_res := world.trade_routes(v_lis, null, null, null);
    if jsonb_array_length(v_res->'routes') < 1 then
      raise exception '0047 self-assert FAIL: the trade scan found nothing within % nm of Lisbon', v_res->'basis'->>'radius_nm';
    end if;
    select count(*) into v_n
      from jsonb_array_elements(v_res->'routes') rr
     where (rr->>'nm')::numeric is distinct from
           (select (reaches->>(rr->'to'->>'code'))::numeric from public.sea_reaches where code = 'LIS');
    if v_n <> 0 then
      raise exception '0047 self-assert FAIL: % trade route(s) are not priced at the reach table''s sailed nm', v_n;
    end if;
    if (v_res->'basis'->>'radius_nm')::numeric is distinct from public.wc_num('sea_scan_radius_nm')
       or v_res->'routes'->0 ? 'legs' then
      raise exception '0047 self-assert FAIL: the scan basis does not state its radius, or rows still carry graph hops';
    end if;

    raise exception '__PROBE_ROLLBACK__' using errcode = 'P0001';
  exception when others then
    if sqlerrm <> '__PROBE_ROLLBACK__' then raise; end if;
  end;

  if (select count(*) from public.players where auth_uid in (c_probe, c_other)) <> 0 then
    raise exception '0047 self-assert FAIL: probe house(s) survived the subtransaction';
  end if;

  -- (n) ONE MOVER: the graph authorities are GONE, not joined
  if to_regprocedure('voyage.route(uuid, uuid, uuid[])') is not null
     or to_regprocedure('voyage.route_direct(uuid, uuid)') is not null
     or to_regprocedure('voyage.path_from_nodes(uuid[])') is not null
     or to_regprocedure('voyage.reach_from(uuid, int, uuid)') is not null
     or to_regprocedure('voyage.sail_refusal(uuid, uuid, numeric)') is not null
     or to_regprocedure('voyage.depart(uuid, uuid[], timestamptz)') is not null
     or to_regprocedure('cmd.divert(uuid, uuid)') is not null
     or to_regprocedure('cmd.issue(uuid, text, int)') is not null
     or to_regprocedure('cmd.preview(uuid, text)') is not null
     or to_regprocedure('world.trade_routes(uuid, uuid, int, int, uuid)') is not null then
    raise exception '0047 self-assert FAIL: a graph-era movement authority still exists - the catastrophe was four overlapping movement paths, and this file exists to leave ONE';
  end if;

  -- (o) the wire and the wall
  if exists (select 1 from public.client_rpc_entry_points() e where e.fn is null)
     or not has_function_privilege('authenticated', 'cmd.issue(uuid, text, int, jsonb)', 'execute')
     or has_function_privilege('anon', 'cmd.issue(uuid, text, int, jsonb)', 'execute')
     or not has_function_privilege('authenticated', 'cmd.divert(uuid, uuid, jsonb, jsonb)', 'execute')
     or not has_function_privilege('authenticated', 'world.sea_raster()', 'execute')
     or not has_function_privilege('authenticated', 'world.reach(uuid)', 'execute')
     or has_function_privilege('anon', 'world.sea_raster()', 'execute')
     or (select count(*) from public.client_write_grants()) <> 0
     or (select count(*) from public.client_executable_writers()) <> 0
     or (select count(*) from public.caller_evaluated_functions()) <> 0 then
    raise exception '0047 self-assert FAIL: the posture is wrong - an entry point does not resolve, a grant is missing or excessive, or the read wall no longer reads zero';
  end if;

  if (world.snapshot()) ? 'legs' then
    raise exception '0047 self-assert FAIL: world.snapshot still serves the leg graph';
  end if;
  if not exists (select 1 from jsonb_array_elements(cmd.verb_schema()) vb
                  where vb->>'verb' = 'SAIL'
                    and vb->'args'->1->>'type' = 'place'
                    and jsonb_array_length(vb->'args') = 2) then
    raise exception '0047 self-assert FAIL: the served SAIL grammar is not [fleet, place]';
  end if;
  if (world.sea_raster()->>'cols')::int <> (select cols from public.sea_raster)
     or length(world.sea_raster()->>'cells_base64') < 100000 then
    raise exception '0047 self-assert FAIL: world.sea_raster does not serve the raster whole';
  end if;

  raise notice '0047 self-assert ok: THE SEA IS A FREE PLANE and there is ONE MOVER - a real house was refused a straight course across Iberia as E_LAND through cmd.issue itself ("%"), refused an unplotted cape passage E_NO_COURSE, refused a mis-joined course E_OFF_COURSE, and then SAILED: Lisbon-Cadiz on a verified water course whose server-measured total equals its own segments and the reach table''s quote to 3 percent, served whole to the chart (course + closed-form position); a homeward SAIL queued at sea departed itself on arrival; she PINPOINTED 33,-15, ANCHORED on the very point, was refused BUY there as E_NOT_DOCKED, sailed home from the anchor, and with thin stores was refused the same passage for the ROUND TRIP; the helm answered MID-OCEAN - truncated at her position to the mile, stale queue cancelled, a NEW voyage bridged from where she stood to Cadiz, docked, and a docked helm refused E_NOT_SAILING; a leg-era voyage converted with its schedule byte-identical and its legacy mark on; the LAND GUARD walked % voyage(s) (skipping % legacy) and BIT a planted straight Lisbon-Barcelona voyage ("%"); every trade recommendation is priced at the reach table''s sailed nm; the graph authorities are dropped, the catalogue resolves, and the read wall reads zero',
    v_land_msg, g.voyages_walked, g.legacy_skipped, v_guard_msg;
end $$;
